// ==============================================================
// Generated by Vitis HLS v2025.1.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module top_kernel_top_kernel_Pipeline_VITIS_LOOP_24_3 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        zext_ln26,
        A_address0,
        A_ce0,
        A_q0,
        conv_i362,
        tmp_address0,
        tmp_ce0,
        tmp_we0,
        tmp_d0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [13:0] zext_ln26;
output  [13:0] A_address0;
output   A_ce0;
input  [23:0] A_q0;
input  [23:0] conv_i362;
output  [13:0] tmp_address0;
output   tmp_ce0;
output   tmp_we0;
output  [23:0] tmp_d0;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_enable_reg_pp0_iter12;
reg    ap_enable_reg_pp0_iter13;
reg    ap_enable_reg_pp0_iter14;
reg    ap_enable_reg_pp0_iter15;
reg    ap_enable_reg_pp0_iter16;
reg    ap_enable_reg_pp0_iter17;
reg    ap_enable_reg_pp0_iter18;
reg    ap_enable_reg_pp0_iter19;
reg    ap_enable_reg_pp0_iter20;
reg    ap_enable_reg_pp0_iter21;
reg    ap_enable_reg_pp0_iter22;
reg    ap_enable_reg_pp0_iter23;
reg    ap_enable_reg_pp0_iter24;
reg    ap_enable_reg_pp0_iter25;
reg    ap_enable_reg_pp0_iter26;
reg    ap_enable_reg_pp0_iter27;
reg    ap_enable_reg_pp0_iter28;
reg    ap_enable_reg_pp0_iter29;
reg    ap_enable_reg_pp0_iter30;
reg    ap_enable_reg_pp0_iter31;
reg    ap_enable_reg_pp0_iter32;
reg    ap_enable_reg_pp0_iter33;
reg    ap_enable_reg_pp0_iter34;
reg    ap_enable_reg_pp0_iter35;
reg    ap_enable_reg_pp0_iter36;
reg    ap_enable_reg_pp0_iter37;
reg    ap_enable_reg_pp0_iter38;
reg    ap_enable_reg_pp0_iter39;
reg    ap_enable_reg_pp0_iter40;
reg    ap_enable_reg_pp0_iter41;
reg    ap_enable_reg_pp0_iter42;
reg    ap_enable_reg_pp0_iter43;
reg    ap_enable_reg_pp0_iter44;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln24_fu_118_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire  signed [39:0] conv_i362_cast_fu_106_p1;
reg  signed [39:0] conv_i362_cast_reg_271;
wire    ap_block_pp0_stage0_11001;
wire   [63:0] zext_ln26_2_fu_140_p1;
reg   [63:0] zext_ln26_2_reg_280;
reg   [63:0] zext_ln26_2_reg_280_pp0_iter1_reg;
reg   [63:0] zext_ln26_2_reg_280_pp0_iter2_reg;
reg   [63:0] zext_ln26_2_reg_280_pp0_iter3_reg;
reg   [63:0] zext_ln26_2_reg_280_pp0_iter4_reg;
reg   [63:0] zext_ln26_2_reg_280_pp0_iter5_reg;
reg   [63:0] zext_ln26_2_reg_280_pp0_iter6_reg;
reg   [63:0] zext_ln26_2_reg_280_pp0_iter7_reg;
reg   [63:0] zext_ln26_2_reg_280_pp0_iter8_reg;
reg   [63:0] zext_ln26_2_reg_280_pp0_iter9_reg;
reg   [63:0] zext_ln26_2_reg_280_pp0_iter10_reg;
reg   [63:0] zext_ln26_2_reg_280_pp0_iter11_reg;
reg   [63:0] zext_ln26_2_reg_280_pp0_iter12_reg;
reg   [63:0] zext_ln26_2_reg_280_pp0_iter13_reg;
reg   [63:0] zext_ln26_2_reg_280_pp0_iter14_reg;
reg   [63:0] zext_ln26_2_reg_280_pp0_iter15_reg;
reg   [63:0] zext_ln26_2_reg_280_pp0_iter16_reg;
reg   [63:0] zext_ln26_2_reg_280_pp0_iter17_reg;
reg   [63:0] zext_ln26_2_reg_280_pp0_iter18_reg;
reg   [63:0] zext_ln26_2_reg_280_pp0_iter19_reg;
reg   [63:0] zext_ln26_2_reg_280_pp0_iter20_reg;
reg   [63:0] zext_ln26_2_reg_280_pp0_iter21_reg;
reg   [63:0] zext_ln26_2_reg_280_pp0_iter22_reg;
reg   [63:0] zext_ln26_2_reg_280_pp0_iter23_reg;
reg   [63:0] zext_ln26_2_reg_280_pp0_iter24_reg;
reg   [63:0] zext_ln26_2_reg_280_pp0_iter25_reg;
reg   [63:0] zext_ln26_2_reg_280_pp0_iter26_reg;
reg   [63:0] zext_ln26_2_reg_280_pp0_iter27_reg;
reg   [63:0] zext_ln26_2_reg_280_pp0_iter28_reg;
reg   [63:0] zext_ln26_2_reg_280_pp0_iter29_reg;
reg   [63:0] zext_ln26_2_reg_280_pp0_iter30_reg;
reg   [63:0] zext_ln26_2_reg_280_pp0_iter31_reg;
reg   [63:0] zext_ln26_2_reg_280_pp0_iter32_reg;
reg   [63:0] zext_ln26_2_reg_280_pp0_iter33_reg;
reg   [63:0] zext_ln26_2_reg_280_pp0_iter34_reg;
reg   [63:0] zext_ln26_2_reg_280_pp0_iter35_reg;
reg   [63:0] zext_ln26_2_reg_280_pp0_iter36_reg;
reg   [63:0] zext_ln26_2_reg_280_pp0_iter37_reg;
reg   [63:0] zext_ln26_2_reg_280_pp0_iter38_reg;
reg   [63:0] zext_ln26_2_reg_280_pp0_iter39_reg;
reg   [63:0] zext_ln26_2_reg_280_pp0_iter40_reg;
reg   [63:0] zext_ln26_2_reg_280_pp0_iter41_reg;
reg   [63:0] zext_ln26_2_reg_280_pp0_iter42_reg;
reg   [63:0] zext_ln26_2_reg_280_pp0_iter43_reg;
wire    ap_block_pp0_stage0;
reg   [6:0] j_fu_64;
wire   [6:0] add_ln24_fu_124_p2;
wire    ap_loop_init;
reg   [6:0] ap_sig_allocacmp_j_1;
reg    A_ce0_local;
reg    tmp_we0_local;
wire   [23:0] select_ln26_1_fu_255_p3;
reg    tmp_ce0_local;
wire   [13:0] zext_ln26_1_fu_130_p1;
wire   [13:0] add_ln26_fu_134_p2;
wire   [39:0] grp_fu_158_p0;
wire  signed [23:0] grp_fu_158_p1;
wire   [39:0] grp_fu_158_p2;
wire   [15:0] tmp_s_fu_183_p4;
wire   [0:0] tmp_1_fu_175_p3;
wire   [0:0] icmp_ln26_1_fu_199_p2;
wire   [0:0] tmp_1_1_fu_163_p3;
wire   [0:0] or_ln26_fu_205_p2;
wire   [0:0] xor_ln26_fu_211_p2;
wire   [0:0] icmp_ln26_fu_193_p2;
wire   [0:0] xor_ln26_1_fu_223_p2;
wire   [0:0] or_ln26_1_fu_229_p2;
wire   [0:0] and_ln26_fu_217_p2;
wire   [0:0] and_ln26_1_fu_235_p2;
wire   [0:0] or_ln26_2_fu_249_p2;
wire   [23:0] select_ln26_fu_241_p3;
wire   [23:0] trunc_ln26_fu_171_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg    ap_loop_exit_ready_pp0_iter9_reg;
reg    ap_loop_exit_ready_pp0_iter10_reg;
reg    ap_loop_exit_ready_pp0_iter11_reg;
reg    ap_loop_exit_ready_pp0_iter12_reg;
reg    ap_loop_exit_ready_pp0_iter13_reg;
reg    ap_loop_exit_ready_pp0_iter14_reg;
reg    ap_loop_exit_ready_pp0_iter15_reg;
reg    ap_loop_exit_ready_pp0_iter16_reg;
reg    ap_loop_exit_ready_pp0_iter17_reg;
reg    ap_loop_exit_ready_pp0_iter18_reg;
reg    ap_loop_exit_ready_pp0_iter19_reg;
reg    ap_loop_exit_ready_pp0_iter20_reg;
reg    ap_loop_exit_ready_pp0_iter21_reg;
reg    ap_loop_exit_ready_pp0_iter22_reg;
reg    ap_loop_exit_ready_pp0_iter23_reg;
reg    ap_loop_exit_ready_pp0_iter24_reg;
reg    ap_loop_exit_ready_pp0_iter25_reg;
reg    ap_loop_exit_ready_pp0_iter26_reg;
reg    ap_loop_exit_ready_pp0_iter27_reg;
reg    ap_loop_exit_ready_pp0_iter28_reg;
reg    ap_loop_exit_ready_pp0_iter29_reg;
reg    ap_loop_exit_ready_pp0_iter30_reg;
reg    ap_loop_exit_ready_pp0_iter31_reg;
reg    ap_loop_exit_ready_pp0_iter32_reg;
reg    ap_loop_exit_ready_pp0_iter33_reg;
reg    ap_loop_exit_ready_pp0_iter34_reg;
reg    ap_loop_exit_ready_pp0_iter35_reg;
reg    ap_loop_exit_ready_pp0_iter36_reg;
reg    ap_loop_exit_ready_pp0_iter37_reg;
reg    ap_loop_exit_ready_pp0_iter38_reg;
reg    ap_loop_exit_ready_pp0_iter39_reg;
reg    ap_loop_exit_ready_pp0_iter40_reg;
reg    ap_loop_exit_ready_pp0_iter41_reg;
reg    ap_loop_exit_ready_pp0_iter42_reg;
reg    ap_loop_exit_ready_pp0_iter43_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 ap_enable_reg_pp0_iter12 = 1'b0;
#0 ap_enable_reg_pp0_iter13 = 1'b0;
#0 ap_enable_reg_pp0_iter14 = 1'b0;
#0 ap_enable_reg_pp0_iter15 = 1'b0;
#0 ap_enable_reg_pp0_iter16 = 1'b0;
#0 ap_enable_reg_pp0_iter17 = 1'b0;
#0 ap_enable_reg_pp0_iter18 = 1'b0;
#0 ap_enable_reg_pp0_iter19 = 1'b0;
#0 ap_enable_reg_pp0_iter20 = 1'b0;
#0 ap_enable_reg_pp0_iter21 = 1'b0;
#0 ap_enable_reg_pp0_iter22 = 1'b0;
#0 ap_enable_reg_pp0_iter23 = 1'b0;
#0 ap_enable_reg_pp0_iter24 = 1'b0;
#0 ap_enable_reg_pp0_iter25 = 1'b0;
#0 ap_enable_reg_pp0_iter26 = 1'b0;
#0 ap_enable_reg_pp0_iter27 = 1'b0;
#0 ap_enable_reg_pp0_iter28 = 1'b0;
#0 ap_enable_reg_pp0_iter29 = 1'b0;
#0 ap_enable_reg_pp0_iter30 = 1'b0;
#0 ap_enable_reg_pp0_iter31 = 1'b0;
#0 ap_enable_reg_pp0_iter32 = 1'b0;
#0 ap_enable_reg_pp0_iter33 = 1'b0;
#0 ap_enable_reg_pp0_iter34 = 1'b0;
#0 ap_enable_reg_pp0_iter35 = 1'b0;
#0 ap_enable_reg_pp0_iter36 = 1'b0;
#0 ap_enable_reg_pp0_iter37 = 1'b0;
#0 ap_enable_reg_pp0_iter38 = 1'b0;
#0 ap_enable_reg_pp0_iter39 = 1'b0;
#0 ap_enable_reg_pp0_iter40 = 1'b0;
#0 ap_enable_reg_pp0_iter41 = 1'b0;
#0 ap_enable_reg_pp0_iter42 = 1'b0;
#0 ap_enable_reg_pp0_iter43 = 1'b0;
#0 ap_enable_reg_pp0_iter44 = 1'b0;
#0 j_fu_64 = 7'd0;
#0 ap_done_reg = 1'b0;
end

top_kernel_sdiv_40ns_24s_40_44_1 #(
    .ID( 1 ),
    .NUM_STAGE( 44 ),
    .din0_WIDTH( 40 ),
    .din1_WIDTH( 24 ),
    .dout_WIDTH( 40 ))
sdiv_40ns_24s_40_44_1_U4(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_158_p0),
    .din1(grp_fu_158_p1),
    .ce(1'b1),
    .dout(grp_fu_158_p2)
);

top_kernel_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter43_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter12 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter13 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter14 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter15 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter15 <= ap_enable_reg_pp0_iter14;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter16 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter16 <= ap_enable_reg_pp0_iter15;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter17 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter17 <= ap_enable_reg_pp0_iter16;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter18 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter18 <= ap_enable_reg_pp0_iter17;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter19 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter19 <= ap_enable_reg_pp0_iter18;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter20 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter20 <= ap_enable_reg_pp0_iter19;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter21 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter21 <= ap_enable_reg_pp0_iter20;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter22 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter22 <= ap_enable_reg_pp0_iter21;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter23 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter23 <= ap_enable_reg_pp0_iter22;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter24 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter24 <= ap_enable_reg_pp0_iter23;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter25 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter25 <= ap_enable_reg_pp0_iter24;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter26 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter26 <= ap_enable_reg_pp0_iter25;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter27 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter27 <= ap_enable_reg_pp0_iter26;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter28 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter28 <= ap_enable_reg_pp0_iter27;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter29 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter29 <= ap_enable_reg_pp0_iter28;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter30 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter30 <= ap_enable_reg_pp0_iter29;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter31 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter31 <= ap_enable_reg_pp0_iter30;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter32 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter32 <= ap_enable_reg_pp0_iter31;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter33 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter33 <= ap_enable_reg_pp0_iter32;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter34 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter34 <= ap_enable_reg_pp0_iter33;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter35 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter35 <= ap_enable_reg_pp0_iter34;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter36 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter36 <= ap_enable_reg_pp0_iter35;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter37 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter37 <= ap_enable_reg_pp0_iter36;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter38 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter38 <= ap_enable_reg_pp0_iter37;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter39 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter39 <= ap_enable_reg_pp0_iter38;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter40 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter40 <= ap_enable_reg_pp0_iter39;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter41 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter41 <= ap_enable_reg_pp0_iter40;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter42 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter42 <= ap_enable_reg_pp0_iter41;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter43 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter43 <= ap_enable_reg_pp0_iter42;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter44 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter44 <= ap_enable_reg_pp0_iter43;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln24_fu_118_p2 == 1'd0))) begin
            j_fu_64 <= add_ln24_fu_124_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            j_fu_64 <= 7'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
        ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
        ap_loop_exit_ready_pp0_iter12_reg <= ap_loop_exit_ready_pp0_iter11_reg;
        ap_loop_exit_ready_pp0_iter13_reg <= ap_loop_exit_ready_pp0_iter12_reg;
        ap_loop_exit_ready_pp0_iter14_reg <= ap_loop_exit_ready_pp0_iter13_reg;
        ap_loop_exit_ready_pp0_iter15_reg <= ap_loop_exit_ready_pp0_iter14_reg;
        ap_loop_exit_ready_pp0_iter16_reg <= ap_loop_exit_ready_pp0_iter15_reg;
        ap_loop_exit_ready_pp0_iter17_reg <= ap_loop_exit_ready_pp0_iter16_reg;
        ap_loop_exit_ready_pp0_iter18_reg <= ap_loop_exit_ready_pp0_iter17_reg;
        ap_loop_exit_ready_pp0_iter19_reg <= ap_loop_exit_ready_pp0_iter18_reg;
        ap_loop_exit_ready_pp0_iter20_reg <= ap_loop_exit_ready_pp0_iter19_reg;
        ap_loop_exit_ready_pp0_iter21_reg <= ap_loop_exit_ready_pp0_iter20_reg;
        ap_loop_exit_ready_pp0_iter22_reg <= ap_loop_exit_ready_pp0_iter21_reg;
        ap_loop_exit_ready_pp0_iter23_reg <= ap_loop_exit_ready_pp0_iter22_reg;
        ap_loop_exit_ready_pp0_iter24_reg <= ap_loop_exit_ready_pp0_iter23_reg;
        ap_loop_exit_ready_pp0_iter25_reg <= ap_loop_exit_ready_pp0_iter24_reg;
        ap_loop_exit_ready_pp0_iter26_reg <= ap_loop_exit_ready_pp0_iter25_reg;
        ap_loop_exit_ready_pp0_iter27_reg <= ap_loop_exit_ready_pp0_iter26_reg;
        ap_loop_exit_ready_pp0_iter28_reg <= ap_loop_exit_ready_pp0_iter27_reg;
        ap_loop_exit_ready_pp0_iter29_reg <= ap_loop_exit_ready_pp0_iter28_reg;
        ap_loop_exit_ready_pp0_iter30_reg <= ap_loop_exit_ready_pp0_iter29_reg;
        ap_loop_exit_ready_pp0_iter31_reg <= ap_loop_exit_ready_pp0_iter30_reg;
        ap_loop_exit_ready_pp0_iter32_reg <= ap_loop_exit_ready_pp0_iter31_reg;
        ap_loop_exit_ready_pp0_iter33_reg <= ap_loop_exit_ready_pp0_iter32_reg;
        ap_loop_exit_ready_pp0_iter34_reg <= ap_loop_exit_ready_pp0_iter33_reg;
        ap_loop_exit_ready_pp0_iter35_reg <= ap_loop_exit_ready_pp0_iter34_reg;
        ap_loop_exit_ready_pp0_iter36_reg <= ap_loop_exit_ready_pp0_iter35_reg;
        ap_loop_exit_ready_pp0_iter37_reg <= ap_loop_exit_ready_pp0_iter36_reg;
        ap_loop_exit_ready_pp0_iter38_reg <= ap_loop_exit_ready_pp0_iter37_reg;
        ap_loop_exit_ready_pp0_iter39_reg <= ap_loop_exit_ready_pp0_iter38_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter40_reg <= ap_loop_exit_ready_pp0_iter39_reg;
        ap_loop_exit_ready_pp0_iter41_reg <= ap_loop_exit_ready_pp0_iter40_reg;
        ap_loop_exit_ready_pp0_iter42_reg <= ap_loop_exit_ready_pp0_iter41_reg;
        ap_loop_exit_ready_pp0_iter43_reg <= ap_loop_exit_ready_pp0_iter42_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
        zext_ln26_2_reg_280_pp0_iter10_reg[13 : 0] <= zext_ln26_2_reg_280_pp0_iter9_reg[13 : 0];
        zext_ln26_2_reg_280_pp0_iter11_reg[13 : 0] <= zext_ln26_2_reg_280_pp0_iter10_reg[13 : 0];
        zext_ln26_2_reg_280_pp0_iter12_reg[13 : 0] <= zext_ln26_2_reg_280_pp0_iter11_reg[13 : 0];
        zext_ln26_2_reg_280_pp0_iter13_reg[13 : 0] <= zext_ln26_2_reg_280_pp0_iter12_reg[13 : 0];
        zext_ln26_2_reg_280_pp0_iter14_reg[13 : 0] <= zext_ln26_2_reg_280_pp0_iter13_reg[13 : 0];
        zext_ln26_2_reg_280_pp0_iter15_reg[13 : 0] <= zext_ln26_2_reg_280_pp0_iter14_reg[13 : 0];
        zext_ln26_2_reg_280_pp0_iter16_reg[13 : 0] <= zext_ln26_2_reg_280_pp0_iter15_reg[13 : 0];
        zext_ln26_2_reg_280_pp0_iter17_reg[13 : 0] <= zext_ln26_2_reg_280_pp0_iter16_reg[13 : 0];
        zext_ln26_2_reg_280_pp0_iter18_reg[13 : 0] <= zext_ln26_2_reg_280_pp0_iter17_reg[13 : 0];
        zext_ln26_2_reg_280_pp0_iter19_reg[13 : 0] <= zext_ln26_2_reg_280_pp0_iter18_reg[13 : 0];
        zext_ln26_2_reg_280_pp0_iter20_reg[13 : 0] <= zext_ln26_2_reg_280_pp0_iter19_reg[13 : 0];
        zext_ln26_2_reg_280_pp0_iter21_reg[13 : 0] <= zext_ln26_2_reg_280_pp0_iter20_reg[13 : 0];
        zext_ln26_2_reg_280_pp0_iter22_reg[13 : 0] <= zext_ln26_2_reg_280_pp0_iter21_reg[13 : 0];
        zext_ln26_2_reg_280_pp0_iter23_reg[13 : 0] <= zext_ln26_2_reg_280_pp0_iter22_reg[13 : 0];
        zext_ln26_2_reg_280_pp0_iter24_reg[13 : 0] <= zext_ln26_2_reg_280_pp0_iter23_reg[13 : 0];
        zext_ln26_2_reg_280_pp0_iter25_reg[13 : 0] <= zext_ln26_2_reg_280_pp0_iter24_reg[13 : 0];
        zext_ln26_2_reg_280_pp0_iter26_reg[13 : 0] <= zext_ln26_2_reg_280_pp0_iter25_reg[13 : 0];
        zext_ln26_2_reg_280_pp0_iter27_reg[13 : 0] <= zext_ln26_2_reg_280_pp0_iter26_reg[13 : 0];
        zext_ln26_2_reg_280_pp0_iter28_reg[13 : 0] <= zext_ln26_2_reg_280_pp0_iter27_reg[13 : 0];
        zext_ln26_2_reg_280_pp0_iter29_reg[13 : 0] <= zext_ln26_2_reg_280_pp0_iter28_reg[13 : 0];
        zext_ln26_2_reg_280_pp0_iter2_reg[13 : 0] <= zext_ln26_2_reg_280_pp0_iter1_reg[13 : 0];
        zext_ln26_2_reg_280_pp0_iter30_reg[13 : 0] <= zext_ln26_2_reg_280_pp0_iter29_reg[13 : 0];
        zext_ln26_2_reg_280_pp0_iter31_reg[13 : 0] <= zext_ln26_2_reg_280_pp0_iter30_reg[13 : 0];
        zext_ln26_2_reg_280_pp0_iter32_reg[13 : 0] <= zext_ln26_2_reg_280_pp0_iter31_reg[13 : 0];
        zext_ln26_2_reg_280_pp0_iter33_reg[13 : 0] <= zext_ln26_2_reg_280_pp0_iter32_reg[13 : 0];
        zext_ln26_2_reg_280_pp0_iter34_reg[13 : 0] <= zext_ln26_2_reg_280_pp0_iter33_reg[13 : 0];
        zext_ln26_2_reg_280_pp0_iter35_reg[13 : 0] <= zext_ln26_2_reg_280_pp0_iter34_reg[13 : 0];
        zext_ln26_2_reg_280_pp0_iter36_reg[13 : 0] <= zext_ln26_2_reg_280_pp0_iter35_reg[13 : 0];
        zext_ln26_2_reg_280_pp0_iter37_reg[13 : 0] <= zext_ln26_2_reg_280_pp0_iter36_reg[13 : 0];
        zext_ln26_2_reg_280_pp0_iter38_reg[13 : 0] <= zext_ln26_2_reg_280_pp0_iter37_reg[13 : 0];
        zext_ln26_2_reg_280_pp0_iter39_reg[13 : 0] <= zext_ln26_2_reg_280_pp0_iter38_reg[13 : 0];
        zext_ln26_2_reg_280_pp0_iter3_reg[13 : 0] <= zext_ln26_2_reg_280_pp0_iter2_reg[13 : 0];
        zext_ln26_2_reg_280_pp0_iter40_reg[13 : 0] <= zext_ln26_2_reg_280_pp0_iter39_reg[13 : 0];
        zext_ln26_2_reg_280_pp0_iter41_reg[13 : 0] <= zext_ln26_2_reg_280_pp0_iter40_reg[13 : 0];
        zext_ln26_2_reg_280_pp0_iter42_reg[13 : 0] <= zext_ln26_2_reg_280_pp0_iter41_reg[13 : 0];
        zext_ln26_2_reg_280_pp0_iter43_reg[13 : 0] <= zext_ln26_2_reg_280_pp0_iter42_reg[13 : 0];
        zext_ln26_2_reg_280_pp0_iter4_reg[13 : 0] <= zext_ln26_2_reg_280_pp0_iter3_reg[13 : 0];
        zext_ln26_2_reg_280_pp0_iter5_reg[13 : 0] <= zext_ln26_2_reg_280_pp0_iter4_reg[13 : 0];
        zext_ln26_2_reg_280_pp0_iter6_reg[13 : 0] <= zext_ln26_2_reg_280_pp0_iter5_reg[13 : 0];
        zext_ln26_2_reg_280_pp0_iter7_reg[13 : 0] <= zext_ln26_2_reg_280_pp0_iter6_reg[13 : 0];
        zext_ln26_2_reg_280_pp0_iter8_reg[13 : 0] <= zext_ln26_2_reg_280_pp0_iter7_reg[13 : 0];
        zext_ln26_2_reg_280_pp0_iter9_reg[13 : 0] <= zext_ln26_2_reg_280_pp0_iter8_reg[13 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        conv_i362_cast_reg_271 <= conv_i362_cast_fu_106_p1;
        zext_ln26_2_reg_280[13 : 0] <= zext_ln26_2_fu_140_p1[13 : 0];
        zext_ln26_2_reg_280_pp0_iter1_reg[13 : 0] <= zext_ln26_2_reg_280[13 : 0];
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        A_ce0_local = 1'b1;
    end else begin
        A_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln24_fu_118_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter43_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_idle_pp0 == 1'b1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter26 == 1'b0) & (ap_enable_reg_pp0_iter25 == 1'b0) & (ap_enable_reg_pp0_iter24 == 1'b0) & (ap_enable_reg_pp0_iter23 == 1'b0) & (ap_enable_reg_pp0_iter22 == 1'b0) & (ap_enable_reg_pp0_iter21 == 1'b0) & (ap_enable_reg_pp0_iter20 == 1'b0) & (ap_enable_reg_pp0_iter19 == 1'b0) & (ap_enable_reg_pp0_iter18 == 1'b0) & (ap_enable_reg_pp0_iter17 == 1'b0) & (ap_enable_reg_pp0_iter16 == 1'b0) & (ap_enable_reg_pp0_iter15 == 1'b0) & (ap_enable_reg_pp0_iter14 == 1'b0) & (ap_enable_reg_pp0_iter13 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter44 == 1'b0) 
    & (ap_enable_reg_pp0_iter43 == 1'b0) & (ap_enable_reg_pp0_iter42 == 1'b0) & (ap_enable_reg_pp0_iter41 == 1'b0) & (ap_enable_reg_pp0_iter40 == 1'b0) & (ap_enable_reg_pp0_iter39 == 1'b0) & (ap_enable_reg_pp0_iter38 == 1'b0) & (ap_enable_reg_pp0_iter37 == 1'b0) & (ap_enable_reg_pp0_iter36 == 1'b0) & (ap_enable_reg_pp0_iter35 == 1'b0) & (ap_enable_reg_pp0_iter34 == 1'b0) & (ap_enable_reg_pp0_iter33 == 1'b0) & (ap_enable_reg_pp0_iter32 == 1'b0) & (ap_enable_reg_pp0_iter31 == 1'b0) & (ap_enable_reg_pp0_iter30 == 1'b0) & (ap_enable_reg_pp0_iter29 == 1'b0) & (ap_enable_reg_pp0_iter28 == 1'b0) & (ap_enable_reg_pp0_iter27 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_j_1 = 7'd0;
    end else begin
        ap_sig_allocacmp_j_1 = j_fu_64;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter44 == 1'b1))) begin
        tmp_ce0_local = 1'b1;
    end else begin
        tmp_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter44 == 1'b1))) begin
        tmp_we0_local = 1'b1;
    end else begin
        tmp_we0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign A_address0 = zext_ln26_2_fu_140_p1;

assign A_ce0 = A_ce0_local;

assign add_ln24_fu_124_p2 = (ap_sig_allocacmp_j_1 + 7'd1);

assign add_ln26_fu_134_p2 = (zext_ln26 + zext_ln26_1_fu_130_p1);

assign and_ln26_1_fu_235_p2 = (tmp_1_1_fu_163_p3 & or_ln26_1_fu_229_p2);

assign and_ln26_fu_217_p2 = (xor_ln26_fu_211_p2 & or_ln26_fu_205_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign conv_i362_cast_fu_106_p1 = $signed(conv_i362);

assign grp_fu_158_p0 = {{A_q0}, {16'd0}};

assign grp_fu_158_p1 = conv_i362_cast_reg_271;

assign icmp_ln24_fu_118_p2 = ((ap_sig_allocacmp_j_1 == 7'd64) ? 1'b1 : 1'b0);

assign icmp_ln26_1_fu_199_p2 = ((tmp_s_fu_183_p4 != 16'd0) ? 1'b1 : 1'b0);

assign icmp_ln26_fu_193_p2 = ((tmp_s_fu_183_p4 != 16'd65535) ? 1'b1 : 1'b0);

assign or_ln26_1_fu_229_p2 = (xor_ln26_1_fu_223_p2 | icmp_ln26_fu_193_p2);

assign or_ln26_2_fu_249_p2 = (and_ln26_fu_217_p2 | and_ln26_1_fu_235_p2);

assign or_ln26_fu_205_p2 = (tmp_1_fu_175_p3 | icmp_ln26_1_fu_199_p2);

assign select_ln26_1_fu_255_p3 = ((or_ln26_2_fu_249_p2[0:0] == 1'b1) ? select_ln26_fu_241_p3 : trunc_ln26_fu_171_p1);

assign select_ln26_fu_241_p3 = ((and_ln26_fu_217_p2[0:0] == 1'b1) ? 24'd8388607 : 24'd8388608);

assign tmp_1_1_fu_163_p3 = grp_fu_158_p2[32'd39];

assign tmp_1_fu_175_p3 = grp_fu_158_p2[32'd23];

assign tmp_address0 = zext_ln26_2_reg_280_pp0_iter43_reg;

assign tmp_ce0 = tmp_ce0_local;

assign tmp_d0 = select_ln26_1_fu_255_p3;

assign tmp_s_fu_183_p4 = {{grp_fu_158_p2[39:24]}};

assign tmp_we0 = tmp_we0_local;

assign trunc_ln26_fu_171_p1 = grp_fu_158_p2[23:0];

assign xor_ln26_1_fu_223_p2 = (tmp_1_fu_175_p3 ^ 1'd1);

assign xor_ln26_fu_211_p2 = (tmp_1_1_fu_163_p3 ^ 1'd1);

assign zext_ln26_1_fu_130_p1 = ap_sig_allocacmp_j_1;

assign zext_ln26_2_fu_140_p1 = add_ln26_fu_134_p2;

always @ (posedge ap_clk) begin
    zext_ln26_2_reg_280[63:14] <= 50'b00000000000000000000000000000000000000000000000000;
    zext_ln26_2_reg_280_pp0_iter1_reg[63:14] <= 50'b00000000000000000000000000000000000000000000000000;
    zext_ln26_2_reg_280_pp0_iter2_reg[63:14] <= 50'b00000000000000000000000000000000000000000000000000;
    zext_ln26_2_reg_280_pp0_iter3_reg[63:14] <= 50'b00000000000000000000000000000000000000000000000000;
    zext_ln26_2_reg_280_pp0_iter4_reg[63:14] <= 50'b00000000000000000000000000000000000000000000000000;
    zext_ln26_2_reg_280_pp0_iter5_reg[63:14] <= 50'b00000000000000000000000000000000000000000000000000;
    zext_ln26_2_reg_280_pp0_iter6_reg[63:14] <= 50'b00000000000000000000000000000000000000000000000000;
    zext_ln26_2_reg_280_pp0_iter7_reg[63:14] <= 50'b00000000000000000000000000000000000000000000000000;
    zext_ln26_2_reg_280_pp0_iter8_reg[63:14] <= 50'b00000000000000000000000000000000000000000000000000;
    zext_ln26_2_reg_280_pp0_iter9_reg[63:14] <= 50'b00000000000000000000000000000000000000000000000000;
    zext_ln26_2_reg_280_pp0_iter10_reg[63:14] <= 50'b00000000000000000000000000000000000000000000000000;
    zext_ln26_2_reg_280_pp0_iter11_reg[63:14] <= 50'b00000000000000000000000000000000000000000000000000;
    zext_ln26_2_reg_280_pp0_iter12_reg[63:14] <= 50'b00000000000000000000000000000000000000000000000000;
    zext_ln26_2_reg_280_pp0_iter13_reg[63:14] <= 50'b00000000000000000000000000000000000000000000000000;
    zext_ln26_2_reg_280_pp0_iter14_reg[63:14] <= 50'b00000000000000000000000000000000000000000000000000;
    zext_ln26_2_reg_280_pp0_iter15_reg[63:14] <= 50'b00000000000000000000000000000000000000000000000000;
    zext_ln26_2_reg_280_pp0_iter16_reg[63:14] <= 50'b00000000000000000000000000000000000000000000000000;
    zext_ln26_2_reg_280_pp0_iter17_reg[63:14] <= 50'b00000000000000000000000000000000000000000000000000;
    zext_ln26_2_reg_280_pp0_iter18_reg[63:14] <= 50'b00000000000000000000000000000000000000000000000000;
    zext_ln26_2_reg_280_pp0_iter19_reg[63:14] <= 50'b00000000000000000000000000000000000000000000000000;
    zext_ln26_2_reg_280_pp0_iter20_reg[63:14] <= 50'b00000000000000000000000000000000000000000000000000;
    zext_ln26_2_reg_280_pp0_iter21_reg[63:14] <= 50'b00000000000000000000000000000000000000000000000000;
    zext_ln26_2_reg_280_pp0_iter22_reg[63:14] <= 50'b00000000000000000000000000000000000000000000000000;
    zext_ln26_2_reg_280_pp0_iter23_reg[63:14] <= 50'b00000000000000000000000000000000000000000000000000;
    zext_ln26_2_reg_280_pp0_iter24_reg[63:14] <= 50'b00000000000000000000000000000000000000000000000000;
    zext_ln26_2_reg_280_pp0_iter25_reg[63:14] <= 50'b00000000000000000000000000000000000000000000000000;
    zext_ln26_2_reg_280_pp0_iter26_reg[63:14] <= 50'b00000000000000000000000000000000000000000000000000;
    zext_ln26_2_reg_280_pp0_iter27_reg[63:14] <= 50'b00000000000000000000000000000000000000000000000000;
    zext_ln26_2_reg_280_pp0_iter28_reg[63:14] <= 50'b00000000000000000000000000000000000000000000000000;
    zext_ln26_2_reg_280_pp0_iter29_reg[63:14] <= 50'b00000000000000000000000000000000000000000000000000;
    zext_ln26_2_reg_280_pp0_iter30_reg[63:14] <= 50'b00000000000000000000000000000000000000000000000000;
    zext_ln26_2_reg_280_pp0_iter31_reg[63:14] <= 50'b00000000000000000000000000000000000000000000000000;
    zext_ln26_2_reg_280_pp0_iter32_reg[63:14] <= 50'b00000000000000000000000000000000000000000000000000;
    zext_ln26_2_reg_280_pp0_iter33_reg[63:14] <= 50'b00000000000000000000000000000000000000000000000000;
    zext_ln26_2_reg_280_pp0_iter34_reg[63:14] <= 50'b00000000000000000000000000000000000000000000000000;
    zext_ln26_2_reg_280_pp0_iter35_reg[63:14] <= 50'b00000000000000000000000000000000000000000000000000;
    zext_ln26_2_reg_280_pp0_iter36_reg[63:14] <= 50'b00000000000000000000000000000000000000000000000000;
    zext_ln26_2_reg_280_pp0_iter37_reg[63:14] <= 50'b00000000000000000000000000000000000000000000000000;
    zext_ln26_2_reg_280_pp0_iter38_reg[63:14] <= 50'b00000000000000000000000000000000000000000000000000;
    zext_ln26_2_reg_280_pp0_iter39_reg[63:14] <= 50'b00000000000000000000000000000000000000000000000000;
    zext_ln26_2_reg_280_pp0_iter40_reg[63:14] <= 50'b00000000000000000000000000000000000000000000000000;
    zext_ln26_2_reg_280_pp0_iter41_reg[63:14] <= 50'b00000000000000000000000000000000000000000000000000;
    zext_ln26_2_reg_280_pp0_iter42_reg[63:14] <= 50'b00000000000000000000000000000000000000000000000000;
    zext_ln26_2_reg_280_pp0_iter43_reg[63:14] <= 50'b00000000000000000000000000000000000000000000000000;
end

endmodule //top_kernel_top_kernel_Pipeline_VITIS_LOOP_24_3
