// ==============================================================
// Generated by Vitis HLS v2025.1.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="top_kernel_top_kernel,hls_ip_2025_1_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xczu3eg-sbva484-1-e,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.276500,HLS_SYN_LAT=852994,HLS_SYN_TPT=none,HLS_SYN_MEM=22,HLS_SYN_DSP=0,HLS_SYN_FF=864,HLS_SYN_LUT=1775,HLS_VERSION=2025_1_1}" *)

module top_kernel (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        A_address0,
        A_ce0,
        A_q0,
        C_address0,
        C_ce0,
        C_we0,
        C_d0
);

parameter    ap_ST_fsm_state1 = 56'd1;
parameter    ap_ST_fsm_state2 = 56'd2;
parameter    ap_ST_fsm_state3 = 56'd4;
parameter    ap_ST_fsm_state4 = 56'd8;
parameter    ap_ST_fsm_state5 = 56'd16;
parameter    ap_ST_fsm_state6 = 56'd32;
parameter    ap_ST_fsm_state7 = 56'd64;
parameter    ap_ST_fsm_state8 = 56'd128;
parameter    ap_ST_fsm_state9 = 56'd256;
parameter    ap_ST_fsm_state10 = 56'd512;
parameter    ap_ST_fsm_state11 = 56'd1024;
parameter    ap_ST_fsm_state12 = 56'd2048;
parameter    ap_ST_fsm_state13 = 56'd4096;
parameter    ap_ST_fsm_state14 = 56'd8192;
parameter    ap_ST_fsm_state15 = 56'd16384;
parameter    ap_ST_fsm_state16 = 56'd32768;
parameter    ap_ST_fsm_state17 = 56'd65536;
parameter    ap_ST_fsm_state18 = 56'd131072;
parameter    ap_ST_fsm_state19 = 56'd262144;
parameter    ap_ST_fsm_state20 = 56'd524288;
parameter    ap_ST_fsm_state21 = 56'd1048576;
parameter    ap_ST_fsm_state22 = 56'd2097152;
parameter    ap_ST_fsm_state23 = 56'd4194304;
parameter    ap_ST_fsm_state24 = 56'd8388608;
parameter    ap_ST_fsm_state25 = 56'd16777216;
parameter    ap_ST_fsm_state26 = 56'd33554432;
parameter    ap_ST_fsm_state27 = 56'd67108864;
parameter    ap_ST_fsm_state28 = 56'd134217728;
parameter    ap_ST_fsm_state29 = 56'd268435456;
parameter    ap_ST_fsm_state30 = 56'd536870912;
parameter    ap_ST_fsm_state31 = 56'd1073741824;
parameter    ap_ST_fsm_state32 = 56'd2147483648;
parameter    ap_ST_fsm_state33 = 56'd4294967296;
parameter    ap_ST_fsm_state34 = 56'd8589934592;
parameter    ap_ST_fsm_state35 = 56'd17179869184;
parameter    ap_ST_fsm_state36 = 56'd34359738368;
parameter    ap_ST_fsm_state37 = 56'd68719476736;
parameter    ap_ST_fsm_state38 = 56'd137438953472;
parameter    ap_ST_fsm_state39 = 56'd274877906944;
parameter    ap_ST_fsm_state40 = 56'd549755813888;
parameter    ap_ST_fsm_state41 = 56'd1099511627776;
parameter    ap_ST_fsm_state42 = 56'd2199023255552;
parameter    ap_ST_fsm_state43 = 56'd4398046511104;
parameter    ap_ST_fsm_state44 = 56'd8796093022208;
parameter    ap_ST_fsm_state45 = 56'd17592186044416;
parameter    ap_ST_fsm_state46 = 56'd35184372088832;
parameter    ap_ST_fsm_state47 = 56'd70368744177664;
parameter    ap_ST_fsm_state48 = 56'd140737488355328;
parameter    ap_ST_fsm_state49 = 56'd281474976710656;
parameter    ap_ST_fsm_state50 = 56'd562949953421312;
parameter    ap_ST_fsm_state51 = 56'd1125899906842624;
parameter    ap_ST_fsm_state52 = 56'd2251799813685248;
parameter    ap_ST_fsm_state53 = 56'd4503599627370496;
parameter    ap_ST_fsm_state54 = 56'd9007199254740992;
parameter    ap_ST_fsm_state55 = 56'd18014398509481984;
parameter    ap_ST_fsm_state56 = 56'd36028797018963968;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [13:0] A_address0;
output   A_ce0;
input  [23:0] A_q0;
output  [13:0] C_address0;
output   C_ce0;
output   C_we0;
output  [23:0] C_d0;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [55:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire  signed [23:0] tmp_q0;
wire   [8:0] add_ln11_fu_298_p2;
reg   [8:0] add_ln11_reg_1188;
wire    ap_CS_fsm_state2;
wire   [13:0] tmp_s_fu_308_p3;
reg   [13:0] tmp_s_reg_1193;
wire   [6:0] add_ln15_fu_327_p2;
reg   [6:0] add_ln15_reg_1209;
wire    ap_CS_fsm_state3;
wire  signed [39:0] conv_i362_fu_411_p1;
reg  signed [39:0] conv_i362_reg_1219;
wire   [23:0] row_sum_fu_477_p3;
wire    ap_CS_fsm_state4;
wire   [6:0] add_ln23_fu_491_p2;
reg   [6:0] add_ln23_reg_1232;
wire    ap_CS_fsm_state5;
wire   [63:0] zext_ln24_1_fu_506_p1;
reg   [63:0] zext_ln24_1_reg_1237;
wire    ap_CS_fsm_state6;
wire   [6:0] add_ln29_fu_638_p2;
reg   [6:0] add_ln29_reg_1255;
wire    ap_CS_fsm_state50;
wire   [13:0] zext_ln29_fu_644_p1;
reg   [13:0] zext_ln29_reg_1260;
wire   [8:0] add_ln33_fu_654_p2;
reg   [8:0] add_ln33_reg_1269;
wire    ap_CS_fsm_state51;
wire  signed [17:0] scale_fu_757_p3;
reg  signed [17:0] scale_reg_1279;
reg   [0:0] tmp_7_reg_1285;
wire   [23:0] col_sum_fu_835_p3;
wire    ap_CS_fsm_state52;
wire  signed [47:0] conv7_i_fu_921_p1;
reg  signed [47:0] conv7_i_reg_1296;
wire    ap_CS_fsm_state53;
wire   [8:0] add_ln41_fu_931_p2;
reg   [8:0] add_ln41_reg_1304;
wire    ap_CS_fsm_state54;
wire   [63:0] zext_ln42_1_fu_954_p1;
reg   [63:0] zext_ln42_1_reg_1309;
wire   [23:0] select_ln42_3_fu_1170_p3;
reg   [23:0] select_ln42_3_reg_1319;
wire    ap_CS_fsm_state55;
reg   [6:0] j_1_reg_207;
wire   [0:0] icmp_ln11_fu_292_p2;
reg  signed [23:0] empty_reg_218;
reg   [6:0] j_2_reg_230;
wire   [0:0] icmp_ln15_fu_321_p2;
wire    ap_CS_fsm_state49;
reg   [8:0] i_1_reg_241;
wire   [0:0] icmp_ln29_fu_632_p2;
reg  signed [23:0] empty_17_reg_252;
reg   [8:0] i_2_reg_264;
wire    ap_CS_fsm_state56;
wire   [63:0] zext_ln16_1_fu_342_p1;
wire   [0:0] icmp_ln23_fu_485_p2;
wire   [63:0] zext_ln34_fu_677_p1;
wire   [0:0] icmp_ln33_fu_648_p2;
wire   [0:0] icmp_ln41_fu_925_p2;
reg   [8:0] i_fu_136;
reg   [6:0] j_fu_140;
reg    A_ce0_local;
reg   [13:0] A_address0_local;
reg    tmp_we0_local;
wire   [23:0] select_ln24_1_fu_620_p3;
reg    tmp_ce0_local;
reg   [13:0] tmp_address0_local;
reg    C_we0_local;
reg    C_ce0_local;
wire  signed [23:0] mul_ln42_fu_275_p1;
wire   [41:0] mul_ln38_fu_279_p1;
wire   [7:0] trunc_ln11_fu_304_p1;
wire   [13:0] zext_ln16_fu_333_p1;
wire   [13:0] add_ln16_2_fu_337_p2;
wire  signed [24:0] sext_ln20_fu_347_p1;
wire   [24:0] add_ln20_fu_351_p2;
wire   [0:0] tmp_1_1_fu_357_p3;
wire   [0:0] tmp_1_fu_369_p3;
wire   [0:0] xor_ln20_fu_377_p2;
wire   [0:0] and_ln20_fu_383_p2;
wire   [0:0] xor_ln20_1_fu_389_p2;
wire   [23:0] select_ln20_fu_395_p3;
wire   [23:0] denom_fu_365_p1;
wire   [23:0] denom_1_fu_403_p3;
wire  signed [23:0] sext_ln16_1_fu_419_p0;
wire  signed [23:0] add_ln16_fu_423_p0;
wire  signed [24:0] sext_ln16_1_fu_419_p1;
wire  signed [24:0] sext_ln16_fu_415_p1;
wire   [24:0] add_ln16_1_fu_429_p2;
wire   [23:0] add_ln16_fu_423_p2;
wire   [0:0] tmp_2_fu_435_p3;
wire   [0:0] tmp_3_fu_443_p3;
wire   [0:0] xor_ln16_fu_451_p2;
wire   [0:0] and_ln16_fu_457_p2;
wire   [0:0] xor_ln16_1_fu_463_p2;
wire   [23:0] select_ln16_fu_469_p3;
wire   [13:0] zext_ln24_fu_497_p1;
wire   [13:0] add_ln24_fu_501_p2;
wire   [39:0] grp_fu_523_p0;
wire  signed [23:0] grp_fu_523_p1;
wire   [39:0] grp_fu_523_p2;
wire   [15:0] tmp_10_fu_548_p4;
wire   [0:0] tmp_13_fu_540_p3;
wire   [0:0] icmp_ln24_1_fu_564_p2;
wire   [0:0] tmp_12_fu_528_p3;
wire   [0:0] or_ln24_fu_570_p2;
wire   [0:0] xor_ln24_fu_576_p2;
wire   [0:0] icmp_ln24_fu_558_p2;
wire   [0:0] xor_ln24_1_fu_588_p2;
wire   [0:0] or_ln24_1_fu_594_p2;
wire   [0:0] and_ln24_fu_582_p2;
wire   [0:0] and_ln24_1_fu_600_p2;
wire   [0:0] or_ln24_2_fu_614_p2;
wire   [23:0] select_ln24_fu_606_p3;
wire   [23:0] trunc_ln24_fu_536_p1;
wire   [7:0] trunc_ln33_fu_660_p1;
wire   [13:0] tmp_8_fu_664_p3;
wire   [13:0] add_ln34_2_fu_672_p2;
wire  signed [39:0] shl_ln_fu_682_p3;
wire   [80:0] mul_ln38_fu_279_p2;
wire   [80:0] sub_ln38_fu_695_p2;
wire   [0:0] tmp_4_fu_701_p3;
wire   [16:0] tmp_19_cast_fu_709_p4;
wire   [16:0] tmp_20_cast_fu_729_p4;
wire   [16:0] select_ln38_1_fu_739_p3;
wire   [17:0] zext_ln38_fu_747_p1;
wire   [17:0] sub_ln38_1_fu_751_p2;
wire   [17:0] tmp_20_cast3_fu_719_p4;
wire  signed [23:0] sext_ln34_1_fu_777_p0;
wire  signed [23:0] add_ln34_fu_781_p0;
wire  signed [24:0] sext_ln34_1_fu_777_p1;
wire  signed [24:0] sext_ln34_fu_773_p1;
wire   [24:0] add_ln34_1_fu_787_p2;
wire   [23:0] add_ln34_fu_781_p2;
wire   [0:0] tmp_9_fu_793_p3;
wire   [0:0] tmp_11_fu_801_p3;
wire   [0:0] xor_ln34_fu_809_p2;
wire   [0:0] and_ln34_fu_815_p2;
wire   [0:0] xor_ln34_1_fu_821_p2;
wire   [23:0] select_ln34_fu_827_p3;
wire  signed [39:0] sext_ln38_1_fu_843_p1;
wire   [0:0] tmp_6_fu_857_p3;
wire   [0:0] tmp_5_fu_846_p3;
wire   [0:0] or_ln38_fu_865_p2;
wire   [0:0] xor_ln38_fu_870_p2;
wire   [0:0] and_ln38_2_fu_882_p2;
wire   [0:0] xor_ln38_1_fu_887_p2;
wire   [0:0] and_ln38_fu_876_p2;
wire   [0:0] and_ln38_1_fu_893_p2;
wire   [0:0] or_ln38_1_fu_907_p2;
wire   [23:0] select_ln38_fu_899_p3;
wire  signed [23:0] sext_ln38_2_fu_854_p1;
wire   [23:0] scale_1_fu_913_p3;
wire   [7:0] trunc_ln41_fu_937_p1;
wire   [13:0] tmp_14_fu_941_p3;
wire   [13:0] add_ln42_1_fu_949_p2;
wire   [47:0] mul_ln42_fu_275_p2;
wire   [0:0] tmp_18_fu_986_p3;
wire   [23:0] trunc_ln2_fu_976_p4;
wire   [23:0] zext_ln42_fu_1002_p1;
wire   [23:0] add_ln42_fu_1006_p2;
wire   [0:0] tmp_20_fu_1012_p3;
wire   [0:0] tmp_19_fu_994_p3;
wire   [0:0] xor_ln42_fu_1020_p2;
wire   [6:0] tmp_16_fu_1040_p3;
wire   [7:0] tmp_17_fu_1054_p3;
wire   [0:0] and_ln42_fu_1026_p2;
wire   [0:0] icmp_ln42_1_fu_1062_p2;
wire   [0:0] icmp_ln42_2_fu_1068_p2;
wire   [0:0] tmp_21_fu_1032_p3;
wire   [0:0] icmp_ln42_fu_1048_p2;
wire   [0:0] xor_ln42_1_fu_1082_p2;
wire   [0:0] and_ln42_1_fu_1088_p2;
wire   [0:0] select_ln42_fu_1074_p3;
wire   [0:0] xor_ln42_2_fu_1108_p2;
wire   [0:0] tmp_15_fu_968_p3;
wire   [0:0] or_ln42_fu_1114_p2;
wire   [0:0] xor_ln42_3_fu_1120_p2;
wire   [0:0] select_ln42_1_fu_1094_p3;
wire   [0:0] and_ln42_2_fu_1102_p2;
wire   [0:0] and_ln42_4_fu_1132_p2;
wire   [0:0] or_ln42_2_fu_1138_p2;
wire   [0:0] xor_ln42_4_fu_1144_p2;
wire   [0:0] and_ln42_3_fu_1126_p2;
wire   [0:0] and_ln42_5_fu_1150_p2;
wire   [0:0] or_ln42_1_fu_1164_p2;
wire   [23:0] select_ln42_2_fu_1156_p3;
reg    grp_fu_523_ap_start;
wire    grp_fu_523_ap_done;
reg   [55:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
wire    ap_ST_fsm_state17_blk;
wire    ap_ST_fsm_state18_blk;
wire    ap_ST_fsm_state19_blk;
wire    ap_ST_fsm_state20_blk;
wire    ap_ST_fsm_state21_blk;
wire    ap_ST_fsm_state22_blk;
wire    ap_ST_fsm_state23_blk;
wire    ap_ST_fsm_state24_blk;
wire    ap_ST_fsm_state25_blk;
wire    ap_ST_fsm_state26_blk;
wire    ap_ST_fsm_state27_blk;
wire    ap_ST_fsm_state28_blk;
wire    ap_ST_fsm_state29_blk;
wire    ap_ST_fsm_state30_blk;
wire    ap_ST_fsm_state31_blk;
wire    ap_ST_fsm_state32_blk;
wire    ap_ST_fsm_state33_blk;
wire    ap_ST_fsm_state34_blk;
wire    ap_ST_fsm_state35_blk;
wire    ap_ST_fsm_state36_blk;
wire    ap_ST_fsm_state37_blk;
wire    ap_ST_fsm_state38_blk;
wire    ap_ST_fsm_state39_blk;
wire    ap_ST_fsm_state40_blk;
wire    ap_ST_fsm_state41_blk;
wire    ap_ST_fsm_state42_blk;
wire    ap_ST_fsm_state43_blk;
wire    ap_ST_fsm_state44_blk;
wire    ap_ST_fsm_state45_blk;
wire    ap_ST_fsm_state46_blk;
wire    ap_ST_fsm_state47_blk;
wire    ap_ST_fsm_state48_blk;
wire    ap_ST_fsm_state49_blk;
wire    ap_ST_fsm_state50_blk;
wire    ap_ST_fsm_state51_blk;
wire    ap_ST_fsm_state52_blk;
wire    ap_ST_fsm_state53_blk;
wire    ap_ST_fsm_state54_blk;
wire    ap_ST_fsm_state55_blk;
wire    ap_ST_fsm_state56_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 56'd1;
#0 i_fu_136 = 9'd0;
#0 j_fu_140 = 7'd0;
end

top_kernel_tmp_RAM_AUTO_1R1W #(
    .DataWidth( 24 ),
    .AddressRange( 16384 ),
    .AddressWidth( 14 ))
tmp_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(tmp_address0_local),
    .ce0(tmp_ce0_local),
    .we0(tmp_we0_local),
    .d0(select_ln24_1_fu_620_p3),
    .q0(tmp_q0)
);

top_kernel_mul_24s_24s_48_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 24 ),
    .din1_WIDTH( 24 ),
    .dout_WIDTH( 48 ))
mul_24s_24s_48_1_1_U1(
    .din0(tmp_q0),
    .din1(mul_ln42_fu_275_p1),
    .dout(mul_ln42_fu_275_p2)
);

top_kernel_mul_40s_42ns_81_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 40 ),
    .din1_WIDTH( 42 ),
    .dout_WIDTH( 81 ))
mul_40s_42ns_81_1_1_U2(
    .din0(shl_ln_fu_682_p3),
    .din1(mul_ln38_fu_279_p1),
    .dout(mul_ln38_fu_279_p2)
);

top_kernel_sdiv_40ns_24s_40_44_seq_1 #(
    .ID( 1 ),
    .NUM_STAGE( 44 ),
    .din0_WIDTH( 40 ),
    .din1_WIDTH( 24 ),
    .dout_WIDTH( 40 ))
sdiv_40ns_24s_40_44_seq_1_U3(
    .clk(ap_clk),
    .reset(ap_rst),
    .start(grp_fu_523_ap_start),
    .done(grp_fu_523_ap_done),
    .din0(grp_fu_523_p0),
    .din1(grp_fu_523_p1),
    .ce(1'b1),
    .dout(grp_fu_523_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state52)) begin
        empty_17_reg_252 <= col_sum_fu_835_p3;
    end else if (((icmp_ln29_fu_632_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state50))) begin
        empty_17_reg_252 <= 24'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        empty_reg_218 <= row_sum_fu_477_p3;
    end else if (((icmp_ln11_fu_292_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        empty_reg_218 <= 24'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state52)) begin
        i_1_reg_241 <= add_ln33_reg_1269;
    end else if (((icmp_ln29_fu_632_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state50))) begin
        i_1_reg_241 <= 9'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state56)) begin
        i_2_reg_264 <= add_ln41_reg_1304;
    end else if ((1'b1 == ap_CS_fsm_state53)) begin
        i_2_reg_264 <= 9'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        i_fu_136 <= 9'd0;
    end else if (((icmp_ln23_fu_485_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state5))) begin
        i_fu_136 <= add_ln11_reg_1188;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        j_1_reg_207 <= add_ln15_reg_1209;
    end else if (((icmp_ln11_fu_292_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        j_1_reg_207 <= 7'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state49)) begin
        j_2_reg_230 <= add_ln23_reg_1232;
    end else if (((icmp_ln15_fu_321_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        j_2_reg_230 <= 7'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln11_fu_292_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        j_fu_140 <= 7'd0;
    end else if (((icmp_ln41_fu_925_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state54))) begin
        j_fu_140 <= add_ln29_reg_1255;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        add_ln11_reg_1188 <= add_ln11_fu_298_p2;
        tmp_s_reg_1193[13 : 6] <= tmp_s_fu_308_p3[13 : 6];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        add_ln15_reg_1209 <= add_ln15_fu_327_p2;
        conv_i362_reg_1219 <= conv_i362_fu_411_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        add_ln23_reg_1232 <= add_ln23_fu_491_p2;
        zext_ln24_1_reg_1237[13 : 0] <= zext_ln24_1_fu_506_p1[13 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state50)) begin
        add_ln29_reg_1255 <= add_ln29_fu_638_p2;
        zext_ln29_reg_1260[6 : 0] <= zext_ln29_fu_644_p1[6 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state51)) begin
        add_ln33_reg_1269 <= add_ln33_fu_654_p2;
        scale_reg_1279 <= scale_fu_757_p3;
        tmp_7_reg_1285 <= scale_fu_757_p3[32'd17];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state54)) begin
        add_ln41_reg_1304 <= add_ln41_fu_931_p2;
        zext_ln42_1_reg_1309[13 : 0] <= zext_ln42_1_fu_954_p1[13 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state53)) begin
        conv7_i_reg_1296 <= conv7_i_fu_921_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state55)) begin
        select_ln42_3_reg_1319 <= select_ln42_3_fu_1170_p3;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        A_address0_local = zext_ln24_1_fu_506_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        A_address0_local = zext_ln16_1_fu_342_p1;
    end else begin
        A_address0_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state3))) begin
        A_ce0_local = 1'b1;
    end else begin
        A_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state56)) begin
        C_ce0_local = 1'b1;
    end else begin
        C_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state56)) begin
        C_we0_local = 1'b1;
    end else begin
        C_we0_local = 1'b0;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state12_blk = 1'b0;

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state14_blk = 1'b0;

assign ap_ST_fsm_state15_blk = 1'b0;

assign ap_ST_fsm_state16_blk = 1'b0;

assign ap_ST_fsm_state17_blk = 1'b0;

assign ap_ST_fsm_state18_blk = 1'b0;

assign ap_ST_fsm_state19_blk = 1'b0;

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state20_blk = 1'b0;

assign ap_ST_fsm_state21_blk = 1'b0;

assign ap_ST_fsm_state22_blk = 1'b0;

assign ap_ST_fsm_state23_blk = 1'b0;

assign ap_ST_fsm_state24_blk = 1'b0;

assign ap_ST_fsm_state25_blk = 1'b0;

assign ap_ST_fsm_state26_blk = 1'b0;

assign ap_ST_fsm_state27_blk = 1'b0;

assign ap_ST_fsm_state28_blk = 1'b0;

assign ap_ST_fsm_state29_blk = 1'b0;

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state30_blk = 1'b0;

assign ap_ST_fsm_state31_blk = 1'b0;

assign ap_ST_fsm_state32_blk = 1'b0;

assign ap_ST_fsm_state33_blk = 1'b0;

assign ap_ST_fsm_state34_blk = 1'b0;

assign ap_ST_fsm_state35_blk = 1'b0;

assign ap_ST_fsm_state36_blk = 1'b0;

assign ap_ST_fsm_state37_blk = 1'b0;

assign ap_ST_fsm_state38_blk = 1'b0;

assign ap_ST_fsm_state39_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state40_blk = 1'b0;

assign ap_ST_fsm_state41_blk = 1'b0;

assign ap_ST_fsm_state42_blk = 1'b0;

assign ap_ST_fsm_state43_blk = 1'b0;

assign ap_ST_fsm_state44_blk = 1'b0;

assign ap_ST_fsm_state45_blk = 1'b0;

assign ap_ST_fsm_state46_blk = 1'b0;

assign ap_ST_fsm_state47_blk = 1'b0;

assign ap_ST_fsm_state48_blk = 1'b0;

assign ap_ST_fsm_state49_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state50_blk = 1'b0;

assign ap_ST_fsm_state51_blk = 1'b0;

assign ap_ST_fsm_state52_blk = 1'b0;

assign ap_ST_fsm_state53_blk = 1'b0;

assign ap_ST_fsm_state54_blk = 1'b0;

assign ap_ST_fsm_state55_blk = 1'b0;

assign ap_ST_fsm_state56_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((icmp_ln29_fu_632_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state50))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln29_fu_632_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state50))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_fu_523_ap_start = 1'b1;
    end else begin
        grp_fu_523_ap_start = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state54)) begin
        tmp_address0_local = zext_ln42_1_fu_954_p1;
    end else if ((1'b1 == ap_CS_fsm_state51)) begin
        tmp_address0_local = zext_ln34_fu_677_p1;
    end else if ((1'b1 == ap_CS_fsm_state49)) begin
        tmp_address0_local = zext_ln24_1_reg_1237;
    end else begin
        tmp_address0_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state49) | (1'b1 == ap_CS_fsm_state54) | (1'b1 == ap_CS_fsm_state51))) begin
        tmp_ce0_local = 1'b1;
    end else begin
        tmp_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state49)) begin
        tmp_we0_local = 1'b1;
    end else begin
        tmp_we0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_ln11_fu_292_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state50;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((icmp_ln15_fu_321_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state5 : begin
            if (((icmp_ln23_fu_485_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state24;
        end
        ap_ST_fsm_state24 : begin
            ap_NS_fsm = ap_ST_fsm_state25;
        end
        ap_ST_fsm_state25 : begin
            ap_NS_fsm = ap_ST_fsm_state26;
        end
        ap_ST_fsm_state26 : begin
            ap_NS_fsm = ap_ST_fsm_state27;
        end
        ap_ST_fsm_state27 : begin
            ap_NS_fsm = ap_ST_fsm_state28;
        end
        ap_ST_fsm_state28 : begin
            ap_NS_fsm = ap_ST_fsm_state29;
        end
        ap_ST_fsm_state29 : begin
            ap_NS_fsm = ap_ST_fsm_state30;
        end
        ap_ST_fsm_state30 : begin
            ap_NS_fsm = ap_ST_fsm_state31;
        end
        ap_ST_fsm_state31 : begin
            ap_NS_fsm = ap_ST_fsm_state32;
        end
        ap_ST_fsm_state32 : begin
            ap_NS_fsm = ap_ST_fsm_state33;
        end
        ap_ST_fsm_state33 : begin
            ap_NS_fsm = ap_ST_fsm_state34;
        end
        ap_ST_fsm_state34 : begin
            ap_NS_fsm = ap_ST_fsm_state35;
        end
        ap_ST_fsm_state35 : begin
            ap_NS_fsm = ap_ST_fsm_state36;
        end
        ap_ST_fsm_state36 : begin
            ap_NS_fsm = ap_ST_fsm_state37;
        end
        ap_ST_fsm_state37 : begin
            ap_NS_fsm = ap_ST_fsm_state38;
        end
        ap_ST_fsm_state38 : begin
            ap_NS_fsm = ap_ST_fsm_state39;
        end
        ap_ST_fsm_state39 : begin
            ap_NS_fsm = ap_ST_fsm_state40;
        end
        ap_ST_fsm_state40 : begin
            ap_NS_fsm = ap_ST_fsm_state41;
        end
        ap_ST_fsm_state41 : begin
            ap_NS_fsm = ap_ST_fsm_state42;
        end
        ap_ST_fsm_state42 : begin
            ap_NS_fsm = ap_ST_fsm_state43;
        end
        ap_ST_fsm_state43 : begin
            ap_NS_fsm = ap_ST_fsm_state44;
        end
        ap_ST_fsm_state44 : begin
            ap_NS_fsm = ap_ST_fsm_state45;
        end
        ap_ST_fsm_state45 : begin
            ap_NS_fsm = ap_ST_fsm_state46;
        end
        ap_ST_fsm_state46 : begin
            ap_NS_fsm = ap_ST_fsm_state47;
        end
        ap_ST_fsm_state47 : begin
            ap_NS_fsm = ap_ST_fsm_state48;
        end
        ap_ST_fsm_state48 : begin
            ap_NS_fsm = ap_ST_fsm_state49;
        end
        ap_ST_fsm_state49 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state50 : begin
            if (((icmp_ln29_fu_632_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state50))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state51;
            end
        end
        ap_ST_fsm_state51 : begin
            if (((icmp_ln33_fu_648_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state51))) begin
                ap_NS_fsm = ap_ST_fsm_state53;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state52;
            end
        end
        ap_ST_fsm_state52 : begin
            ap_NS_fsm = ap_ST_fsm_state51;
        end
        ap_ST_fsm_state53 : begin
            ap_NS_fsm = ap_ST_fsm_state54;
        end
        ap_ST_fsm_state54 : begin
            if (((icmp_ln41_fu_925_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state54))) begin
                ap_NS_fsm = ap_ST_fsm_state50;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state55;
            end
        end
        ap_ST_fsm_state55 : begin
            ap_NS_fsm = ap_ST_fsm_state56;
        end
        ap_ST_fsm_state56 : begin
            ap_NS_fsm = ap_ST_fsm_state54;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign A_address0 = A_address0_local;

assign A_ce0 = A_ce0_local;

assign C_address0 = zext_ln42_1_reg_1309;

assign C_ce0 = C_ce0_local;

assign C_d0 = select_ln42_3_reg_1319;

assign C_we0 = C_we0_local;

assign add_ln11_fu_298_p2 = (i_fu_136 + 9'd1);

assign add_ln15_fu_327_p2 = (j_1_reg_207 + 7'd1);

assign add_ln16_1_fu_429_p2 = ($signed(sext_ln16_1_fu_419_p1) + $signed(sext_ln16_fu_415_p1));

assign add_ln16_2_fu_337_p2 = (tmp_s_reg_1193 + zext_ln16_fu_333_p1);

assign add_ln16_fu_423_p0 = A_q0;

assign add_ln16_fu_423_p2 = ($signed(add_ln16_fu_423_p0) + $signed(empty_reg_218));

assign add_ln20_fu_351_p2 = ($signed(sext_ln20_fu_347_p1) + $signed(25'd65536));

assign add_ln23_fu_491_p2 = (j_2_reg_230 + 7'd1);

assign add_ln24_fu_501_p2 = (tmp_s_reg_1193 + zext_ln24_fu_497_p1);

assign add_ln29_fu_638_p2 = (j_fu_140 + 7'd1);

assign add_ln33_fu_654_p2 = (i_1_reg_241 + 9'd1);

assign add_ln34_1_fu_787_p2 = ($signed(sext_ln34_1_fu_777_p1) + $signed(sext_ln34_fu_773_p1));

assign add_ln34_2_fu_672_p2 = (tmp_8_fu_664_p3 + zext_ln29_reg_1260);

assign add_ln34_fu_781_p0 = tmp_q0;

assign add_ln34_fu_781_p2 = ($signed(add_ln34_fu_781_p0) + $signed(empty_17_reg_252));

assign add_ln41_fu_931_p2 = (i_2_reg_264 + 9'd1);

assign add_ln42_1_fu_949_p2 = (tmp_14_fu_941_p3 + zext_ln29_reg_1260);

assign add_ln42_fu_1006_p2 = (trunc_ln2_fu_976_p4 + zext_ln42_fu_1002_p1);

assign and_ln16_fu_457_p2 = (xor_ln16_fu_451_p2 & tmp_3_fu_443_p3);

assign and_ln20_fu_383_p2 = (xor_ln20_fu_377_p2 & tmp_1_fu_369_p3);

assign and_ln24_1_fu_600_p2 = (tmp_12_fu_528_p3 & or_ln24_1_fu_594_p2);

assign and_ln24_fu_582_p2 = (xor_ln24_fu_576_p2 & or_ln24_fu_570_p2);

assign and_ln34_fu_815_p2 = (xor_ln34_fu_809_p2 & tmp_11_fu_801_p3);

assign and_ln38_1_fu_893_p2 = (xor_ln38_1_fu_887_p2 & tmp_5_fu_846_p3);

assign and_ln38_2_fu_882_p2 = (tmp_7_reg_1285 & tmp_6_fu_857_p3);

assign and_ln38_fu_876_p2 = (xor_ln38_fu_870_p2 & or_ln38_fu_865_p2);

assign and_ln42_1_fu_1088_p2 = (xor_ln42_1_fu_1082_p2 & icmp_ln42_fu_1048_p2);

assign and_ln42_2_fu_1102_p2 = (icmp_ln42_1_fu_1062_p2 & and_ln42_fu_1026_p2);

assign and_ln42_3_fu_1126_p2 = (xor_ln42_3_fu_1120_p2 & or_ln42_fu_1114_p2);

assign and_ln42_4_fu_1132_p2 = (tmp_20_fu_1012_p3 & select_ln42_1_fu_1094_p3);

assign and_ln42_5_fu_1150_p2 = (xor_ln42_4_fu_1144_p2 & tmp_15_fu_968_p3);

assign and_ln42_fu_1026_p2 = (xor_ln42_fu_1020_p2 & tmp_19_fu_994_p3);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state49 = ap_CS_fsm[32'd48];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state50 = ap_CS_fsm[32'd49];

assign ap_CS_fsm_state51 = ap_CS_fsm[32'd50];

assign ap_CS_fsm_state52 = ap_CS_fsm[32'd51];

assign ap_CS_fsm_state53 = ap_CS_fsm[32'd52];

assign ap_CS_fsm_state54 = ap_CS_fsm[32'd53];

assign ap_CS_fsm_state55 = ap_CS_fsm[32'd54];

assign ap_CS_fsm_state56 = ap_CS_fsm[32'd55];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign col_sum_fu_835_p3 = ((xor_ln34_1_fu_821_p2[0:0] == 1'b1) ? select_ln34_fu_827_p3 : add_ln34_fu_781_p2);

assign conv7_i_fu_921_p1 = $signed(scale_1_fu_913_p3);

assign conv_i362_fu_411_p1 = $signed(denom_1_fu_403_p3);

assign denom_1_fu_403_p3 = ((xor_ln20_1_fu_389_p2[0:0] == 1'b1) ? select_ln20_fu_395_p3 : denom_fu_365_p1);

assign denom_fu_365_p1 = add_ln20_fu_351_p2[23:0];

assign grp_fu_523_p0 = {{A_q0}, {16'd0}};

assign grp_fu_523_p1 = conv_i362_reg_1219;

assign icmp_ln11_fu_292_p2 = ((i_fu_136 == 9'd256) ? 1'b1 : 1'b0);

assign icmp_ln15_fu_321_p2 = ((j_1_reg_207 == 7'd64) ? 1'b1 : 1'b0);

assign icmp_ln23_fu_485_p2 = ((j_2_reg_230 == 7'd64) ? 1'b1 : 1'b0);

assign icmp_ln24_1_fu_564_p2 = ((tmp_10_fu_548_p4 != 16'd0) ? 1'b1 : 1'b0);

assign icmp_ln24_fu_558_p2 = ((tmp_10_fu_548_p4 != 16'd65535) ? 1'b1 : 1'b0);

assign icmp_ln29_fu_632_p2 = ((j_fu_140 == 7'd64) ? 1'b1 : 1'b0);

assign icmp_ln33_fu_648_p2 = ((i_1_reg_241 == 9'd256) ? 1'b1 : 1'b0);

assign icmp_ln41_fu_925_p2 = ((i_2_reg_264 == 9'd256) ? 1'b1 : 1'b0);

assign icmp_ln42_1_fu_1062_p2 = ((tmp_17_fu_1054_p3 == 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln42_2_fu_1068_p2 = ((tmp_17_fu_1054_p3 == 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln42_fu_1048_p2 = ((tmp_16_fu_1040_p3 == 7'd127) ? 1'b1 : 1'b0);

assign mul_ln38_fu_279_p1 = 81'd1099511758849;

assign mul_ln42_fu_275_p1 = conv7_i_reg_1296;

assign or_ln24_1_fu_594_p2 = (xor_ln24_1_fu_588_p2 | icmp_ln24_fu_558_p2);

assign or_ln24_2_fu_614_p2 = (and_ln24_fu_582_p2 | and_ln24_1_fu_600_p2);

assign or_ln24_fu_570_p2 = (tmp_13_fu_540_p3 | icmp_ln24_1_fu_564_p2);

assign or_ln38_1_fu_907_p2 = (and_ln38_fu_876_p2 | and_ln38_1_fu_893_p2);

assign or_ln38_fu_865_p2 = (tmp_7_reg_1285 | tmp_6_fu_857_p3);

assign or_ln42_1_fu_1164_p2 = (and_ln42_5_fu_1150_p2 | and_ln42_3_fu_1126_p2);

assign or_ln42_2_fu_1138_p2 = (and_ln42_4_fu_1132_p2 | and_ln42_2_fu_1102_p2);

assign or_ln42_fu_1114_p2 = (xor_ln42_2_fu_1108_p2 | tmp_20_fu_1012_p3);

assign row_sum_fu_477_p3 = ((xor_ln16_1_fu_463_p2[0:0] == 1'b1) ? select_ln16_fu_469_p3 : add_ln16_fu_423_p2);

assign scale_1_fu_913_p3 = ((or_ln38_1_fu_907_p2[0:0] == 1'b1) ? select_ln38_fu_899_p3 : sext_ln38_2_fu_854_p1);

assign scale_fu_757_p3 = ((tmp_4_fu_701_p3[0:0] == 1'b1) ? sub_ln38_1_fu_751_p2 : tmp_20_cast3_fu_719_p4);

assign select_ln16_fu_469_p3 = ((and_ln16_fu_457_p2[0:0] == 1'b1) ? 24'd8388607 : 24'd8388608);

assign select_ln20_fu_395_p3 = ((and_ln20_fu_383_p2[0:0] == 1'b1) ? 24'd8388607 : 24'd8388608);

assign select_ln24_1_fu_620_p3 = ((or_ln24_2_fu_614_p2[0:0] == 1'b1) ? select_ln24_fu_606_p3 : trunc_ln24_fu_536_p1);

assign select_ln24_fu_606_p3 = ((and_ln24_fu_582_p2[0:0] == 1'b1) ? 24'd8388607 : 24'd8388608);

assign select_ln34_fu_827_p3 = ((and_ln34_fu_815_p2[0:0] == 1'b1) ? 24'd8388607 : 24'd8388608);

assign select_ln38_1_fu_739_p3 = ((tmp_4_fu_701_p3[0:0] == 1'b1) ? tmp_19_cast_fu_709_p4 : tmp_20_cast_fu_729_p4);

assign select_ln38_fu_899_p3 = ((and_ln38_fu_876_p2[0:0] == 1'b1) ? 24'd8388607 : 24'd8388608);

assign select_ln42_1_fu_1094_p3 = ((and_ln42_fu_1026_p2[0:0] == 1'b1) ? and_ln42_1_fu_1088_p2 : icmp_ln42_1_fu_1062_p2);

assign select_ln42_2_fu_1156_p3 = ((and_ln42_3_fu_1126_p2[0:0] == 1'b1) ? 24'd8388607 : 24'd8388608);

assign select_ln42_3_fu_1170_p3 = ((or_ln42_1_fu_1164_p2[0:0] == 1'b1) ? select_ln42_2_fu_1156_p3 : add_ln42_fu_1006_p2);

assign select_ln42_fu_1074_p3 = ((and_ln42_fu_1026_p2[0:0] == 1'b1) ? icmp_ln42_1_fu_1062_p2 : icmp_ln42_2_fu_1068_p2);

assign sext_ln16_1_fu_419_p0 = A_q0;

assign sext_ln16_1_fu_419_p1 = sext_ln16_1_fu_419_p0;

assign sext_ln16_fu_415_p1 = empty_reg_218;

assign sext_ln20_fu_347_p1 = empty_reg_218;

assign sext_ln34_1_fu_777_p0 = tmp_q0;

assign sext_ln34_1_fu_777_p1 = sext_ln34_1_fu_777_p0;

assign sext_ln34_fu_773_p1 = empty_17_reg_252;

assign sext_ln38_1_fu_843_p1 = scale_reg_1279;

assign sext_ln38_2_fu_854_p1 = scale_reg_1279;

assign shl_ln_fu_682_p3 = {{empty_17_reg_252}, {16'd0}};

assign sub_ln38_1_fu_751_p2 = (18'd0 - zext_ln38_fu_747_p1);

assign sub_ln38_fu_695_p2 = (81'd0 - mul_ln38_fu_279_p2);

assign tmp_10_fu_548_p4 = {{grp_fu_523_p2[39:24]}};

assign tmp_11_fu_801_p3 = add_ln34_fu_781_p2[32'd23];

assign tmp_12_fu_528_p3 = grp_fu_523_p2[32'd39];

assign tmp_13_fu_540_p3 = grp_fu_523_p2[32'd23];

assign tmp_14_fu_941_p3 = {{trunc_ln41_fu_937_p1}, {6'd0}};

assign tmp_15_fu_968_p3 = mul_ln42_fu_275_p2[32'd47];

assign tmp_16_fu_1040_p3 = {{mul_ln42_fu_275_p2[47:41]}};

assign tmp_17_fu_1054_p3 = {{mul_ln42_fu_275_p2[47:40]}};

assign tmp_18_fu_986_p3 = mul_ln42_fu_275_p2[32'd15];

assign tmp_19_cast_fu_709_p4 = {{sub_ln38_fu_695_p2[79:63]}};

assign tmp_19_fu_994_p3 = mul_ln42_fu_275_p2[32'd39];

assign tmp_1_1_fu_357_p3 = add_ln20_fu_351_p2[32'd24];

assign tmp_1_fu_369_p3 = add_ln20_fu_351_p2[32'd23];

assign tmp_20_cast3_fu_719_p4 = {{mul_ln38_fu_279_p2[80:63]}};

assign tmp_20_cast_fu_729_p4 = {{mul_ln38_fu_279_p2[79:63]}};

assign tmp_20_fu_1012_p3 = add_ln42_fu_1006_p2[32'd23];

assign tmp_21_fu_1032_p3 = mul_ln42_fu_275_p2[32'd40];

assign tmp_2_fu_435_p3 = add_ln16_1_fu_429_p2[32'd24];

assign tmp_3_fu_443_p3 = add_ln16_fu_423_p2[32'd23];

assign tmp_4_fu_701_p3 = empty_17_reg_252[32'd23];

assign tmp_5_fu_846_p3 = sext_ln38_1_fu_843_p1[32'd39];

assign tmp_6_fu_857_p3 = sext_ln38_1_fu_843_p1[32'd23];

assign tmp_8_fu_664_p3 = {{trunc_ln33_fu_660_p1}, {6'd0}};

assign tmp_9_fu_793_p3 = add_ln34_1_fu_787_p2[32'd24];

assign tmp_s_fu_308_p3 = {{trunc_ln11_fu_304_p1}, {6'd0}};

assign trunc_ln11_fu_304_p1 = i_fu_136[7:0];

assign trunc_ln24_fu_536_p1 = grp_fu_523_p2[23:0];

assign trunc_ln2_fu_976_p4 = {{mul_ln42_fu_275_p2[39:16]}};

assign trunc_ln33_fu_660_p1 = i_1_reg_241[7:0];

assign trunc_ln41_fu_937_p1 = i_2_reg_264[7:0];

assign xor_ln16_1_fu_463_p2 = (tmp_3_fu_443_p3 ^ tmp_2_fu_435_p3);

assign xor_ln16_fu_451_p2 = (tmp_2_fu_435_p3 ^ 1'd1);

assign xor_ln20_1_fu_389_p2 = (tmp_1_fu_369_p3 ^ tmp_1_1_fu_357_p3);

assign xor_ln20_fu_377_p2 = (tmp_1_1_fu_357_p3 ^ 1'd1);

assign xor_ln24_1_fu_588_p2 = (tmp_13_fu_540_p3 ^ 1'd1);

assign xor_ln24_fu_576_p2 = (tmp_12_fu_528_p3 ^ 1'd1);

assign xor_ln34_1_fu_821_p2 = (tmp_9_fu_793_p3 ^ tmp_11_fu_801_p3);

assign xor_ln34_fu_809_p2 = (tmp_9_fu_793_p3 ^ 1'd1);

assign xor_ln38_1_fu_887_p2 = (1'd1 ^ and_ln38_2_fu_882_p2);

assign xor_ln38_fu_870_p2 = (tmp_5_fu_846_p3 ^ 1'd1);

assign xor_ln42_1_fu_1082_p2 = (tmp_21_fu_1032_p3 ^ 1'd1);

assign xor_ln42_2_fu_1108_p2 = (select_ln42_fu_1074_p3 ^ 1'd1);

assign xor_ln42_3_fu_1120_p2 = (tmp_15_fu_968_p3 ^ 1'd1);

assign xor_ln42_4_fu_1144_p2 = (or_ln42_2_fu_1138_p2 ^ 1'd1);

assign xor_ln42_fu_1020_p2 = (tmp_20_fu_1012_p3 ^ 1'd1);

assign zext_ln16_1_fu_342_p1 = add_ln16_2_fu_337_p2;

assign zext_ln16_fu_333_p1 = j_1_reg_207;

assign zext_ln24_1_fu_506_p1 = add_ln24_fu_501_p2;

assign zext_ln24_fu_497_p1 = j_2_reg_230;

assign zext_ln29_fu_644_p1 = j_fu_140;

assign zext_ln34_fu_677_p1 = add_ln34_2_fu_672_p2;

assign zext_ln38_fu_747_p1 = select_ln38_1_fu_739_p3;

assign zext_ln42_1_fu_954_p1 = add_ln42_1_fu_949_p2;

assign zext_ln42_fu_1002_p1 = tmp_18_fu_986_p3;

always @ (posedge ap_clk) begin
    tmp_s_reg_1193[5:0] <= 6'b000000;
    zext_ln24_1_reg_1237[63:14] <= 50'b00000000000000000000000000000000000000000000000000;
    zext_ln29_reg_1260[13:7] <= 7'b0000000;
    zext_ln42_1_reg_1309[63:14] <= 50'b00000000000000000000000000000000000000000000000000;
end

endmodule //top_kernel
