-- ==============================================================
-- Generated by Vitis HLS v2025.1.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity top_kernel_top_kernel_Pipeline_VITIS_LOOP_24_3 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    zext_ln26 : IN STD_LOGIC_VECTOR (13 downto 0);
    A_address0 : OUT STD_LOGIC_VECTOR (13 downto 0);
    A_ce0 : OUT STD_LOGIC;
    A_q0 : IN STD_LOGIC_VECTOR (23 downto 0);
    conv_i362 : IN STD_LOGIC_VECTOR (23 downto 0);
    tmp_address0 : OUT STD_LOGIC_VECTOR (13 downto 0);
    tmp_ce0 : OUT STD_LOGIC;
    tmp_we0 : OUT STD_LOGIC;
    tmp_d0 : OUT STD_LOGIC_VECTOR (23 downto 0) );
end;


architecture behav of top_kernel_top_kernel_Pipeline_VITIS_LOOP_24_3 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv7_40 : STD_LOGIC_VECTOR (6 downto 0) := "1000000";
    constant ap_const_lv7_1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv32_27 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100111";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_18 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011000";
    constant ap_const_lv16_FFFF : STD_LOGIC_VECTOR (15 downto 0) := "1111111111111111";
    constant ap_const_lv24_7FFFFF : STD_LOGIC_VECTOR (23 downto 0) := "011111111111111111111111";
    constant ap_const_lv24_800000 : STD_LOGIC_VECTOR (23 downto 0) := "100000000000000000000000";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter7 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter8 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter9 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter10 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter11 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter12 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter13 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter14 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter15 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter16 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter17 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter18 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter19 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter20 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter21 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter22 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter23 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter24 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter25 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter26 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter27 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter28 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter29 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter30 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter31 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter32 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter33 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter34 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter35 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter36 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter37 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter38 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter39 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter40 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter41 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter42 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter43 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter44 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln24_fu_118_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal conv_i362_cast_fu_106_p1 : STD_LOGIC_VECTOR (39 downto 0);
    signal conv_i362_cast_reg_271 : STD_LOGIC_VECTOR (39 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal zext_ln26_2_fu_140_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln26_2_reg_280 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln26_2_reg_280_pp0_iter1_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln26_2_reg_280_pp0_iter2_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln26_2_reg_280_pp0_iter3_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln26_2_reg_280_pp0_iter4_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln26_2_reg_280_pp0_iter5_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln26_2_reg_280_pp0_iter6_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln26_2_reg_280_pp0_iter7_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln26_2_reg_280_pp0_iter8_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln26_2_reg_280_pp0_iter9_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln26_2_reg_280_pp0_iter10_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln26_2_reg_280_pp0_iter11_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln26_2_reg_280_pp0_iter12_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln26_2_reg_280_pp0_iter13_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln26_2_reg_280_pp0_iter14_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln26_2_reg_280_pp0_iter15_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln26_2_reg_280_pp0_iter16_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln26_2_reg_280_pp0_iter17_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln26_2_reg_280_pp0_iter18_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln26_2_reg_280_pp0_iter19_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln26_2_reg_280_pp0_iter20_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln26_2_reg_280_pp0_iter21_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln26_2_reg_280_pp0_iter22_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln26_2_reg_280_pp0_iter23_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln26_2_reg_280_pp0_iter24_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln26_2_reg_280_pp0_iter25_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln26_2_reg_280_pp0_iter26_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln26_2_reg_280_pp0_iter27_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln26_2_reg_280_pp0_iter28_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln26_2_reg_280_pp0_iter29_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln26_2_reg_280_pp0_iter30_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln26_2_reg_280_pp0_iter31_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln26_2_reg_280_pp0_iter32_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln26_2_reg_280_pp0_iter33_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln26_2_reg_280_pp0_iter34_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln26_2_reg_280_pp0_iter35_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln26_2_reg_280_pp0_iter36_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln26_2_reg_280_pp0_iter37_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln26_2_reg_280_pp0_iter38_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln26_2_reg_280_pp0_iter39_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln26_2_reg_280_pp0_iter40_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln26_2_reg_280_pp0_iter41_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln26_2_reg_280_pp0_iter42_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln26_2_reg_280_pp0_iter43_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal j_fu_64 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    signal add_ln24_fu_124_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_j_1 : STD_LOGIC_VECTOR (6 downto 0);
    signal A_ce0_local : STD_LOGIC;
    signal tmp_we0_local : STD_LOGIC;
    signal select_ln26_1_fu_255_p3 : STD_LOGIC_VECTOR (23 downto 0);
    signal tmp_ce0_local : STD_LOGIC;
    signal zext_ln26_1_fu_130_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal add_ln26_fu_134_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal grp_fu_158_p0 : STD_LOGIC_VECTOR (39 downto 0);
    signal grp_fu_158_p1 : STD_LOGIC_VECTOR (23 downto 0);
    signal grp_fu_158_p2 : STD_LOGIC_VECTOR (39 downto 0);
    signal tmp_s_fu_183_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_6_fu_175_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln26_1_fu_199_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_1_fu_163_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln26_fu_205_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln26_fu_211_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln26_fu_193_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln26_1_fu_223_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln26_1_fu_229_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln26_fu_217_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln26_1_fu_235_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln26_2_fu_249_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln26_fu_241_p3 : STD_LOGIC_VECTOR (23 downto 0);
    signal trunc_ln26_fu_171_p1 : STD_LOGIC_VECTOR (23 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter5_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter6_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter7_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter8_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter9_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter10_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter11_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter12_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter13_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter14_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter15_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter16_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter17_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter18_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter19_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter20_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter21_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter22_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter23_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter24_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter25_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter26_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter27_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter28_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter29_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter30_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter31_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter32_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter33_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter34_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter35_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter36_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter37_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter38_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter39_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter40_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter41_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter42_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter43_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component top_kernel_sdiv_40ns_24s_40_44_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (39 downto 0);
        din1 : IN STD_LOGIC_VECTOR (23 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (39 downto 0) );
    end component;


    component top_kernel_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    sdiv_40ns_24s_40_44_1_U4 : component top_kernel_sdiv_40ns_24s_40_44_1
    generic map (
        ID => 1,
        NUM_STAGE => 44,
        din0_WIDTH => 40,
        din1_WIDTH => 24,
        dout_WIDTH => 40)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_158_p0,
        din1 => grp_fu_158_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_158_p2);

    flow_control_loop_pipe_sequential_init_U : component top_kernel_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready_pp0_iter43_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter10_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter10 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter11_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter11 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter12_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter12 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter13_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter13 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter14_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter14 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter15_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter15 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter15 <= ap_enable_reg_pp0_iter14;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter16_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter16 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter16 <= ap_enable_reg_pp0_iter15;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter17_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter17 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter17 <= ap_enable_reg_pp0_iter16;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter18_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter18 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter18 <= ap_enable_reg_pp0_iter17;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter19_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter19 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter19 <= ap_enable_reg_pp0_iter18;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter20_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter20 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter20 <= ap_enable_reg_pp0_iter19;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter21_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter21 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter21 <= ap_enable_reg_pp0_iter20;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter22_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter22 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter22 <= ap_enable_reg_pp0_iter21;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter23_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter23 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter23 <= ap_enable_reg_pp0_iter22;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter24_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter24 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter24 <= ap_enable_reg_pp0_iter23;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter25_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter25 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter25 <= ap_enable_reg_pp0_iter24;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter26_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter26 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter26 <= ap_enable_reg_pp0_iter25;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter27_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter27 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter27 <= ap_enable_reg_pp0_iter26;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter28_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter28 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter28 <= ap_enable_reg_pp0_iter27;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter29_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter29 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter29 <= ap_enable_reg_pp0_iter28;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter30_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter30 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter30 <= ap_enable_reg_pp0_iter29;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter31_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter31 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter31 <= ap_enable_reg_pp0_iter30;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter32_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter32 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter32 <= ap_enable_reg_pp0_iter31;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter33_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter33 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter33 <= ap_enable_reg_pp0_iter32;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter34_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter34 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter34 <= ap_enable_reg_pp0_iter33;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter35_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter35 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter35 <= ap_enable_reg_pp0_iter34;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter36_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter36 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter36 <= ap_enable_reg_pp0_iter35;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter37_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter37 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter37 <= ap_enable_reg_pp0_iter36;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter38_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter38 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter38 <= ap_enable_reg_pp0_iter37;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter39_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter39 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter39 <= ap_enable_reg_pp0_iter38;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter40_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter40 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter40 <= ap_enable_reg_pp0_iter39;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter41_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter41 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter41 <= ap_enable_reg_pp0_iter40;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter42_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter42 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter42 <= ap_enable_reg_pp0_iter41;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter43_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter43 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter43 <= ap_enable_reg_pp0_iter42;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter44_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter44 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter44 <= ap_enable_reg_pp0_iter43;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter7_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter7 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter8_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter8 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter9_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter9 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
                end if; 
            end if;
        end if;
    end process;


    j_fu_64_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln24_fu_118_p2 = ap_const_lv1_0))) then 
                    j_fu_64 <= add_ln24_fu_124_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    j_fu_64 <= ap_const_lv7_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
                ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
                ap_loop_exit_ready_pp0_iter12_reg <= ap_loop_exit_ready_pp0_iter11_reg;
                ap_loop_exit_ready_pp0_iter13_reg <= ap_loop_exit_ready_pp0_iter12_reg;
                ap_loop_exit_ready_pp0_iter14_reg <= ap_loop_exit_ready_pp0_iter13_reg;
                ap_loop_exit_ready_pp0_iter15_reg <= ap_loop_exit_ready_pp0_iter14_reg;
                ap_loop_exit_ready_pp0_iter16_reg <= ap_loop_exit_ready_pp0_iter15_reg;
                ap_loop_exit_ready_pp0_iter17_reg <= ap_loop_exit_ready_pp0_iter16_reg;
                ap_loop_exit_ready_pp0_iter18_reg <= ap_loop_exit_ready_pp0_iter17_reg;
                ap_loop_exit_ready_pp0_iter19_reg <= ap_loop_exit_ready_pp0_iter18_reg;
                ap_loop_exit_ready_pp0_iter20_reg <= ap_loop_exit_ready_pp0_iter19_reg;
                ap_loop_exit_ready_pp0_iter21_reg <= ap_loop_exit_ready_pp0_iter20_reg;
                ap_loop_exit_ready_pp0_iter22_reg <= ap_loop_exit_ready_pp0_iter21_reg;
                ap_loop_exit_ready_pp0_iter23_reg <= ap_loop_exit_ready_pp0_iter22_reg;
                ap_loop_exit_ready_pp0_iter24_reg <= ap_loop_exit_ready_pp0_iter23_reg;
                ap_loop_exit_ready_pp0_iter25_reg <= ap_loop_exit_ready_pp0_iter24_reg;
                ap_loop_exit_ready_pp0_iter26_reg <= ap_loop_exit_ready_pp0_iter25_reg;
                ap_loop_exit_ready_pp0_iter27_reg <= ap_loop_exit_ready_pp0_iter26_reg;
                ap_loop_exit_ready_pp0_iter28_reg <= ap_loop_exit_ready_pp0_iter27_reg;
                ap_loop_exit_ready_pp0_iter29_reg <= ap_loop_exit_ready_pp0_iter28_reg;
                ap_loop_exit_ready_pp0_iter30_reg <= ap_loop_exit_ready_pp0_iter29_reg;
                ap_loop_exit_ready_pp0_iter31_reg <= ap_loop_exit_ready_pp0_iter30_reg;
                ap_loop_exit_ready_pp0_iter32_reg <= ap_loop_exit_ready_pp0_iter31_reg;
                ap_loop_exit_ready_pp0_iter33_reg <= ap_loop_exit_ready_pp0_iter32_reg;
                ap_loop_exit_ready_pp0_iter34_reg <= ap_loop_exit_ready_pp0_iter33_reg;
                ap_loop_exit_ready_pp0_iter35_reg <= ap_loop_exit_ready_pp0_iter34_reg;
                ap_loop_exit_ready_pp0_iter36_reg <= ap_loop_exit_ready_pp0_iter35_reg;
                ap_loop_exit_ready_pp0_iter37_reg <= ap_loop_exit_ready_pp0_iter36_reg;
                ap_loop_exit_ready_pp0_iter38_reg <= ap_loop_exit_ready_pp0_iter37_reg;
                ap_loop_exit_ready_pp0_iter39_reg <= ap_loop_exit_ready_pp0_iter38_reg;
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                ap_loop_exit_ready_pp0_iter40_reg <= ap_loop_exit_ready_pp0_iter39_reg;
                ap_loop_exit_ready_pp0_iter41_reg <= ap_loop_exit_ready_pp0_iter40_reg;
                ap_loop_exit_ready_pp0_iter42_reg <= ap_loop_exit_ready_pp0_iter41_reg;
                ap_loop_exit_ready_pp0_iter43_reg <= ap_loop_exit_ready_pp0_iter42_reg;
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
                ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
                ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
                ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
                ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
                ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
                    zext_ln26_2_reg_280_pp0_iter10_reg(13 downto 0) <= zext_ln26_2_reg_280_pp0_iter9_reg(13 downto 0);
                    zext_ln26_2_reg_280_pp0_iter11_reg(13 downto 0) <= zext_ln26_2_reg_280_pp0_iter10_reg(13 downto 0);
                    zext_ln26_2_reg_280_pp0_iter12_reg(13 downto 0) <= zext_ln26_2_reg_280_pp0_iter11_reg(13 downto 0);
                    zext_ln26_2_reg_280_pp0_iter13_reg(13 downto 0) <= zext_ln26_2_reg_280_pp0_iter12_reg(13 downto 0);
                    zext_ln26_2_reg_280_pp0_iter14_reg(13 downto 0) <= zext_ln26_2_reg_280_pp0_iter13_reg(13 downto 0);
                    zext_ln26_2_reg_280_pp0_iter15_reg(13 downto 0) <= zext_ln26_2_reg_280_pp0_iter14_reg(13 downto 0);
                    zext_ln26_2_reg_280_pp0_iter16_reg(13 downto 0) <= zext_ln26_2_reg_280_pp0_iter15_reg(13 downto 0);
                    zext_ln26_2_reg_280_pp0_iter17_reg(13 downto 0) <= zext_ln26_2_reg_280_pp0_iter16_reg(13 downto 0);
                    zext_ln26_2_reg_280_pp0_iter18_reg(13 downto 0) <= zext_ln26_2_reg_280_pp0_iter17_reg(13 downto 0);
                    zext_ln26_2_reg_280_pp0_iter19_reg(13 downto 0) <= zext_ln26_2_reg_280_pp0_iter18_reg(13 downto 0);
                    zext_ln26_2_reg_280_pp0_iter20_reg(13 downto 0) <= zext_ln26_2_reg_280_pp0_iter19_reg(13 downto 0);
                    zext_ln26_2_reg_280_pp0_iter21_reg(13 downto 0) <= zext_ln26_2_reg_280_pp0_iter20_reg(13 downto 0);
                    zext_ln26_2_reg_280_pp0_iter22_reg(13 downto 0) <= zext_ln26_2_reg_280_pp0_iter21_reg(13 downto 0);
                    zext_ln26_2_reg_280_pp0_iter23_reg(13 downto 0) <= zext_ln26_2_reg_280_pp0_iter22_reg(13 downto 0);
                    zext_ln26_2_reg_280_pp0_iter24_reg(13 downto 0) <= zext_ln26_2_reg_280_pp0_iter23_reg(13 downto 0);
                    zext_ln26_2_reg_280_pp0_iter25_reg(13 downto 0) <= zext_ln26_2_reg_280_pp0_iter24_reg(13 downto 0);
                    zext_ln26_2_reg_280_pp0_iter26_reg(13 downto 0) <= zext_ln26_2_reg_280_pp0_iter25_reg(13 downto 0);
                    zext_ln26_2_reg_280_pp0_iter27_reg(13 downto 0) <= zext_ln26_2_reg_280_pp0_iter26_reg(13 downto 0);
                    zext_ln26_2_reg_280_pp0_iter28_reg(13 downto 0) <= zext_ln26_2_reg_280_pp0_iter27_reg(13 downto 0);
                    zext_ln26_2_reg_280_pp0_iter29_reg(13 downto 0) <= zext_ln26_2_reg_280_pp0_iter28_reg(13 downto 0);
                    zext_ln26_2_reg_280_pp0_iter2_reg(13 downto 0) <= zext_ln26_2_reg_280_pp0_iter1_reg(13 downto 0);
                    zext_ln26_2_reg_280_pp0_iter30_reg(13 downto 0) <= zext_ln26_2_reg_280_pp0_iter29_reg(13 downto 0);
                    zext_ln26_2_reg_280_pp0_iter31_reg(13 downto 0) <= zext_ln26_2_reg_280_pp0_iter30_reg(13 downto 0);
                    zext_ln26_2_reg_280_pp0_iter32_reg(13 downto 0) <= zext_ln26_2_reg_280_pp0_iter31_reg(13 downto 0);
                    zext_ln26_2_reg_280_pp0_iter33_reg(13 downto 0) <= zext_ln26_2_reg_280_pp0_iter32_reg(13 downto 0);
                    zext_ln26_2_reg_280_pp0_iter34_reg(13 downto 0) <= zext_ln26_2_reg_280_pp0_iter33_reg(13 downto 0);
                    zext_ln26_2_reg_280_pp0_iter35_reg(13 downto 0) <= zext_ln26_2_reg_280_pp0_iter34_reg(13 downto 0);
                    zext_ln26_2_reg_280_pp0_iter36_reg(13 downto 0) <= zext_ln26_2_reg_280_pp0_iter35_reg(13 downto 0);
                    zext_ln26_2_reg_280_pp0_iter37_reg(13 downto 0) <= zext_ln26_2_reg_280_pp0_iter36_reg(13 downto 0);
                    zext_ln26_2_reg_280_pp0_iter38_reg(13 downto 0) <= zext_ln26_2_reg_280_pp0_iter37_reg(13 downto 0);
                    zext_ln26_2_reg_280_pp0_iter39_reg(13 downto 0) <= zext_ln26_2_reg_280_pp0_iter38_reg(13 downto 0);
                    zext_ln26_2_reg_280_pp0_iter3_reg(13 downto 0) <= zext_ln26_2_reg_280_pp0_iter2_reg(13 downto 0);
                    zext_ln26_2_reg_280_pp0_iter40_reg(13 downto 0) <= zext_ln26_2_reg_280_pp0_iter39_reg(13 downto 0);
                    zext_ln26_2_reg_280_pp0_iter41_reg(13 downto 0) <= zext_ln26_2_reg_280_pp0_iter40_reg(13 downto 0);
                    zext_ln26_2_reg_280_pp0_iter42_reg(13 downto 0) <= zext_ln26_2_reg_280_pp0_iter41_reg(13 downto 0);
                    zext_ln26_2_reg_280_pp0_iter43_reg(13 downto 0) <= zext_ln26_2_reg_280_pp0_iter42_reg(13 downto 0);
                    zext_ln26_2_reg_280_pp0_iter4_reg(13 downto 0) <= zext_ln26_2_reg_280_pp0_iter3_reg(13 downto 0);
                    zext_ln26_2_reg_280_pp0_iter5_reg(13 downto 0) <= zext_ln26_2_reg_280_pp0_iter4_reg(13 downto 0);
                    zext_ln26_2_reg_280_pp0_iter6_reg(13 downto 0) <= zext_ln26_2_reg_280_pp0_iter5_reg(13 downto 0);
                    zext_ln26_2_reg_280_pp0_iter7_reg(13 downto 0) <= zext_ln26_2_reg_280_pp0_iter6_reg(13 downto 0);
                    zext_ln26_2_reg_280_pp0_iter8_reg(13 downto 0) <= zext_ln26_2_reg_280_pp0_iter7_reg(13 downto 0);
                    zext_ln26_2_reg_280_pp0_iter9_reg(13 downto 0) <= zext_ln26_2_reg_280_pp0_iter8_reg(13 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                conv_i362_cast_reg_271 <= conv_i362_cast_fu_106_p1;
                    zext_ln26_2_reg_280(13 downto 0) <= zext_ln26_2_fu_140_p1(13 downto 0);
                    zext_ln26_2_reg_280_pp0_iter1_reg(13 downto 0) <= zext_ln26_2_reg_280(13 downto 0);
            end if;
        end if;
    end process;
    zext_ln26_2_reg_280(63 downto 14) <= "00000000000000000000000000000000000000000000000000";
    zext_ln26_2_reg_280_pp0_iter1_reg(63 downto 14) <= "00000000000000000000000000000000000000000000000000";
    zext_ln26_2_reg_280_pp0_iter2_reg(63 downto 14) <= "00000000000000000000000000000000000000000000000000";
    zext_ln26_2_reg_280_pp0_iter3_reg(63 downto 14) <= "00000000000000000000000000000000000000000000000000";
    zext_ln26_2_reg_280_pp0_iter4_reg(63 downto 14) <= "00000000000000000000000000000000000000000000000000";
    zext_ln26_2_reg_280_pp0_iter5_reg(63 downto 14) <= "00000000000000000000000000000000000000000000000000";
    zext_ln26_2_reg_280_pp0_iter6_reg(63 downto 14) <= "00000000000000000000000000000000000000000000000000";
    zext_ln26_2_reg_280_pp0_iter7_reg(63 downto 14) <= "00000000000000000000000000000000000000000000000000";
    zext_ln26_2_reg_280_pp0_iter8_reg(63 downto 14) <= "00000000000000000000000000000000000000000000000000";
    zext_ln26_2_reg_280_pp0_iter9_reg(63 downto 14) <= "00000000000000000000000000000000000000000000000000";
    zext_ln26_2_reg_280_pp0_iter10_reg(63 downto 14) <= "00000000000000000000000000000000000000000000000000";
    zext_ln26_2_reg_280_pp0_iter11_reg(63 downto 14) <= "00000000000000000000000000000000000000000000000000";
    zext_ln26_2_reg_280_pp0_iter12_reg(63 downto 14) <= "00000000000000000000000000000000000000000000000000";
    zext_ln26_2_reg_280_pp0_iter13_reg(63 downto 14) <= "00000000000000000000000000000000000000000000000000";
    zext_ln26_2_reg_280_pp0_iter14_reg(63 downto 14) <= "00000000000000000000000000000000000000000000000000";
    zext_ln26_2_reg_280_pp0_iter15_reg(63 downto 14) <= "00000000000000000000000000000000000000000000000000";
    zext_ln26_2_reg_280_pp0_iter16_reg(63 downto 14) <= "00000000000000000000000000000000000000000000000000";
    zext_ln26_2_reg_280_pp0_iter17_reg(63 downto 14) <= "00000000000000000000000000000000000000000000000000";
    zext_ln26_2_reg_280_pp0_iter18_reg(63 downto 14) <= "00000000000000000000000000000000000000000000000000";
    zext_ln26_2_reg_280_pp0_iter19_reg(63 downto 14) <= "00000000000000000000000000000000000000000000000000";
    zext_ln26_2_reg_280_pp0_iter20_reg(63 downto 14) <= "00000000000000000000000000000000000000000000000000";
    zext_ln26_2_reg_280_pp0_iter21_reg(63 downto 14) <= "00000000000000000000000000000000000000000000000000";
    zext_ln26_2_reg_280_pp0_iter22_reg(63 downto 14) <= "00000000000000000000000000000000000000000000000000";
    zext_ln26_2_reg_280_pp0_iter23_reg(63 downto 14) <= "00000000000000000000000000000000000000000000000000";
    zext_ln26_2_reg_280_pp0_iter24_reg(63 downto 14) <= "00000000000000000000000000000000000000000000000000";
    zext_ln26_2_reg_280_pp0_iter25_reg(63 downto 14) <= "00000000000000000000000000000000000000000000000000";
    zext_ln26_2_reg_280_pp0_iter26_reg(63 downto 14) <= "00000000000000000000000000000000000000000000000000";
    zext_ln26_2_reg_280_pp0_iter27_reg(63 downto 14) <= "00000000000000000000000000000000000000000000000000";
    zext_ln26_2_reg_280_pp0_iter28_reg(63 downto 14) <= "00000000000000000000000000000000000000000000000000";
    zext_ln26_2_reg_280_pp0_iter29_reg(63 downto 14) <= "00000000000000000000000000000000000000000000000000";
    zext_ln26_2_reg_280_pp0_iter30_reg(63 downto 14) <= "00000000000000000000000000000000000000000000000000";
    zext_ln26_2_reg_280_pp0_iter31_reg(63 downto 14) <= "00000000000000000000000000000000000000000000000000";
    zext_ln26_2_reg_280_pp0_iter32_reg(63 downto 14) <= "00000000000000000000000000000000000000000000000000";
    zext_ln26_2_reg_280_pp0_iter33_reg(63 downto 14) <= "00000000000000000000000000000000000000000000000000";
    zext_ln26_2_reg_280_pp0_iter34_reg(63 downto 14) <= "00000000000000000000000000000000000000000000000000";
    zext_ln26_2_reg_280_pp0_iter35_reg(63 downto 14) <= "00000000000000000000000000000000000000000000000000";
    zext_ln26_2_reg_280_pp0_iter36_reg(63 downto 14) <= "00000000000000000000000000000000000000000000000000";
    zext_ln26_2_reg_280_pp0_iter37_reg(63 downto 14) <= "00000000000000000000000000000000000000000000000000";
    zext_ln26_2_reg_280_pp0_iter38_reg(63 downto 14) <= "00000000000000000000000000000000000000000000000000";
    zext_ln26_2_reg_280_pp0_iter39_reg(63 downto 14) <= "00000000000000000000000000000000000000000000000000";
    zext_ln26_2_reg_280_pp0_iter40_reg(63 downto 14) <= "00000000000000000000000000000000000000000000000000";
    zext_ln26_2_reg_280_pp0_iter41_reg(63 downto 14) <= "00000000000000000000000000000000000000000000000000";
    zext_ln26_2_reg_280_pp0_iter42_reg(63 downto 14) <= "00000000000000000000000000000000000000000000000000";
    zext_ln26_2_reg_280_pp0_iter43_reg(63 downto 14) <= "00000000000000000000000000000000000000000000000000";

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    A_address0 <= zext_ln26_2_fu_140_p1(14 - 1 downto 0);
    A_ce0 <= A_ce0_local;

    A_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            A_ce0_local <= ap_const_logic_1;
        else 
            A_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    add_ln24_fu_124_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_j_1) + unsigned(ap_const_lv7_1));
    add_ln26_fu_134_p2 <= std_logic_vector(unsigned(zext_ln26) + unsigned(zext_ln26_1_fu_130_p1));
    and_ln26_1_fu_235_p2 <= (tmp_1_fu_163_p3 and or_ln26_1_fu_229_p2);
    and_ln26_fu_217_p2 <= (xor_ln26_fu_211_p2 and or_ln26_fu_205_p2);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln24_fu_118_p2)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln24_fu_118_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter43_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter43_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_idle_pp0 = ap_const_logic_1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7, ap_enable_reg_pp0_iter8, ap_enable_reg_pp0_iter9, ap_enable_reg_pp0_iter10, ap_enable_reg_pp0_iter11, ap_enable_reg_pp0_iter12, ap_enable_reg_pp0_iter13, ap_enable_reg_pp0_iter14, ap_enable_reg_pp0_iter15, ap_enable_reg_pp0_iter16, ap_enable_reg_pp0_iter17, ap_enable_reg_pp0_iter18, ap_enable_reg_pp0_iter19, ap_enable_reg_pp0_iter20, ap_enable_reg_pp0_iter21, ap_enable_reg_pp0_iter22, ap_enable_reg_pp0_iter23, ap_enable_reg_pp0_iter24, ap_enable_reg_pp0_iter25, ap_enable_reg_pp0_iter26, ap_enable_reg_pp0_iter27, ap_enable_reg_pp0_iter28, ap_enable_reg_pp0_iter29, ap_enable_reg_pp0_iter30, ap_enable_reg_pp0_iter31, ap_enable_reg_pp0_iter32, ap_enable_reg_pp0_iter33, ap_enable_reg_pp0_iter34, ap_enable_reg_pp0_iter35, ap_enable_reg_pp0_iter36, ap_enable_reg_pp0_iter37, ap_enable_reg_pp0_iter38, ap_enable_reg_pp0_iter39, ap_enable_reg_pp0_iter40, ap_enable_reg_pp0_iter41, ap_enable_reg_pp0_iter42, ap_enable_reg_pp0_iter43, ap_enable_reg_pp0_iter44)
    begin
        if (((ap_enable_reg_pp0_iter26 = ap_const_logic_0) and (ap_enable_reg_pp0_iter25 = ap_const_logic_0) and (ap_enable_reg_pp0_iter24 = ap_const_logic_0) and (ap_enable_reg_pp0_iter23 = ap_const_logic_0) and (ap_enable_reg_pp0_iter22 = ap_const_logic_0) and (ap_enable_reg_pp0_iter21 = ap_const_logic_0) and (ap_enable_reg_pp0_iter20 = ap_const_logic_0) and (ap_enable_reg_pp0_iter19 = ap_const_logic_0) and (ap_enable_reg_pp0_iter18 = ap_const_logic_0) and (ap_enable_reg_pp0_iter17 = ap_const_logic_0) and (ap_enable_reg_pp0_iter16 = ap_const_logic_0) and (ap_enable_reg_pp0_iter15 = ap_const_logic_0) and (ap_enable_reg_pp0_iter14 = ap_const_logic_0) and (ap_enable_reg_pp0_iter13 = ap_const_logic_0) and (ap_enable_reg_pp0_iter12 = ap_const_logic_0) and (ap_enable_reg_pp0_iter11 = ap_const_logic_0) and (ap_enable_reg_pp0_iter10 = ap_const_logic_0) and (ap_enable_reg_pp0_iter9 = ap_const_logic_0) and (ap_enable_reg_pp0_iter8 = ap_const_logic_0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = 
    ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0) and (ap_enable_reg_pp0_iter44 = ap_const_logic_0) and (ap_enable_reg_pp0_iter43 = ap_const_logic_0) and (ap_enable_reg_pp0_iter42 = ap_const_logic_0) and (ap_enable_reg_pp0_iter41 = ap_const_logic_0) and (ap_enable_reg_pp0_iter40 = ap_const_logic_0) and (ap_enable_reg_pp0_iter39 = ap_const_logic_0) and (ap_enable_reg_pp0_iter38 = ap_const_logic_0) and (ap_enable_reg_pp0_iter37 = ap_const_logic_0) and (ap_enable_reg_pp0_iter36 = ap_const_logic_0) and (ap_enable_reg_pp0_iter35 = ap_const_logic_0) and (ap_enable_reg_pp0_iter34 = ap_const_logic_0) and (ap_enable_reg_pp0_iter33 = ap_const_logic_0) and (ap_enable_reg_pp0_iter32 = ap_const_logic_0) and (ap_enable_reg_pp0_iter31 = ap_const_logic_0) and (ap_enable_reg_pp0_iter30 
    = ap_const_logic_0) and (ap_enable_reg_pp0_iter29 = ap_const_logic_0) and (ap_enable_reg_pp0_iter28 = ap_const_logic_0) and (ap_enable_reg_pp0_iter27 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_j_1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, j_fu_64, ap_loop_init)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            ap_sig_allocacmp_j_1 <= ap_const_lv7_0;
        else 
            ap_sig_allocacmp_j_1 <= j_fu_64;
        end if; 
    end process;

        conv_i362_cast_fu_106_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(conv_i362),40));

    grp_fu_158_p0 <= (A_q0 & ap_const_lv16_0);
    grp_fu_158_p1 <= conv_i362_cast_reg_271(24 - 1 downto 0);
    icmp_ln24_fu_118_p2 <= "1" when (ap_sig_allocacmp_j_1 = ap_const_lv7_40) else "0";
    icmp_ln26_1_fu_199_p2 <= "0" when (tmp_s_fu_183_p4 = ap_const_lv16_0) else "1";
    icmp_ln26_fu_193_p2 <= "0" when (tmp_s_fu_183_p4 = ap_const_lv16_FFFF) else "1";
    or_ln26_1_fu_229_p2 <= (xor_ln26_1_fu_223_p2 or icmp_ln26_fu_193_p2);
    or_ln26_2_fu_249_p2 <= (and_ln26_fu_217_p2 or and_ln26_1_fu_235_p2);
    or_ln26_fu_205_p2 <= (tmp_6_fu_175_p3 or icmp_ln26_1_fu_199_p2);
    select_ln26_1_fu_255_p3 <= 
        select_ln26_fu_241_p3 when (or_ln26_2_fu_249_p2(0) = '1') else 
        trunc_ln26_fu_171_p1;
    select_ln26_fu_241_p3 <= 
        ap_const_lv24_7FFFFF when (and_ln26_fu_217_p2(0) = '1') else 
        ap_const_lv24_800000;
    tmp_1_fu_163_p3 <= grp_fu_158_p2(39 downto 39);
    tmp_6_fu_175_p3 <= grp_fu_158_p2(23 downto 23);
    tmp_address0 <= zext_ln26_2_reg_280_pp0_iter43_reg(14 - 1 downto 0);
    tmp_ce0 <= tmp_ce0_local;

    tmp_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter44, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter44 = ap_const_logic_1))) then 
            tmp_ce0_local <= ap_const_logic_1;
        else 
            tmp_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    tmp_d0 <= select_ln26_1_fu_255_p3;
    tmp_s_fu_183_p4 <= grp_fu_158_p2(39 downto 24);
    tmp_we0 <= tmp_we0_local;

    tmp_we0_local_assign_proc : process(ap_enable_reg_pp0_iter44, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter44 = ap_const_logic_1))) then 
            tmp_we0_local <= ap_const_logic_1;
        else 
            tmp_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    trunc_ln26_fu_171_p1 <= grp_fu_158_p2(24 - 1 downto 0);
    xor_ln26_1_fu_223_p2 <= (tmp_6_fu_175_p3 xor ap_const_lv1_1);
    xor_ln26_fu_211_p2 <= (tmp_1_fu_163_p3 xor ap_const_lv1_1);
    zext_ln26_1_fu_130_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_sig_allocacmp_j_1),14));
    zext_ln26_2_fu_140_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln26_fu_134_p2),64));
end behav;
