-- ==============================================================
-- Generated by Vitis HLS v2025.1.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity top_kernel is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    A_address0 : OUT STD_LOGIC_VECTOR (13 downto 0);
    A_ce0 : OUT STD_LOGIC;
    A_q0 : IN STD_LOGIC_VECTOR (23 downto 0);
    C_address0 : OUT STD_LOGIC_VECTOR (13 downto 0);
    C_ce0 : OUT STD_LOGIC;
    C_we0 : OUT STD_LOGIC;
    C_d0 : OUT STD_LOGIC_VECTOR (23 downto 0) );
end;


architecture behav of top_kernel is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "top_kernel_top_kernel,hls_ip_2025_1_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xczu3eg-sbva484-1-e,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.276500,HLS_SYN_LAT=128002,HLS_SYN_TPT=none,HLS_SYN_MEM=22,HLS_SYN_DSP=0,HLS_SYN_FF=3980,HLS_SYN_LUT=4086,HLS_VERSION=2025_1_1}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (11 downto 0) := "000000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (11 downto 0) := "000000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (11 downto 0) := "000000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (11 downto 0) := "000000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (11 downto 0) := "000000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (11 downto 0) := "000000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (11 downto 0) := "000001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (11 downto 0) := "000010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (11 downto 0) := "000100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (11 downto 0) := "001000000000";
    constant ap_ST_fsm_state11 : STD_LOGIC_VECTOR (11 downto 0) := "010000000000";
    constant ap_ST_fsm_state12 : STD_LOGIC_VECTOR (11 downto 0) := "100000000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv24_0 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000000";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv81_10000020001 : STD_LOGIC_VECTOR (80 downto 0) := "000000000000000000000000000000000000000010000000000000000000000100000000000000001";
    constant ap_const_lv9_100 : STD_LOGIC_VECTOR (8 downto 0) := "100000000";
    constant ap_const_lv9_1 : STD_LOGIC_VECTOR (8 downto 0) := "000000001";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv25_10000 : STD_LOGIC_VECTOR (24 downto 0) := "0000000010000000000000000";
    constant ap_const_lv32_18 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011000";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv24_7FFFFF : STD_LOGIC_VECTOR (23 downto 0) := "011111111111111111111111";
    constant ap_const_lv24_800000 : STD_LOGIC_VECTOR (23 downto 0) := "100000000000000000000000";
    constant ap_const_lv7_40 : STD_LOGIC_VECTOR (6 downto 0) := "1000000";
    constant ap_const_lv7_1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv81_0 : STD_LOGIC_VECTOR (80 downto 0) := "000000000000000000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv32_4F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001001111";
    constant ap_const_lv32_50 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001010000";
    constant ap_const_lv18_0 : STD_LOGIC_VECTOR (17 downto 0) := "000000000000000000";
    constant ap_const_lv32_11 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010001";
    constant ap_const_lv32_27 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100111";
    constant ap_const_lv32_2F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101111";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv32_28 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101000";
    constant ap_const_lv32_29 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101001";
    constant ap_const_lv7_7F : STD_LOGIC_VECTOR (6 downto 0) := "1111111";
    constant ap_const_lv8_FF : STD_LOGIC_VECTOR (7 downto 0) := "11111111";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";

    signal ap_CS_fsm : STD_LOGIC_VECTOR (11 downto 0) := "000000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal tmp_address0 : STD_LOGIC_VECTOR (13 downto 0);
    signal tmp_ce0 : STD_LOGIC;
    signal tmp_we0 : STD_LOGIC;
    signal tmp_q0 : STD_LOGIC_VECTOR (23 downto 0);
    signal tmp_s_fu_265_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal tmp_s_reg_917 : STD_LOGIC_VECTOR (13 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal denom_1_fu_343_p3 : STD_LOGIC_VECTOR (23 downto 0);
    signal denom_1_reg_930 : STD_LOGIC_VECTOR (23 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal add_ln31_fu_361_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln31_reg_938 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal zext_ln31_fu_367_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal zext_ln31_reg_943 : STD_LOGIC_VECTOR (13 downto 0);
    signal add_ln35_fu_377_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln35_reg_952 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal scale_fu_480_p3 : STD_LOGIC_VECTOR (17 downto 0);
    signal scale_reg_962 : STD_LOGIC_VECTOR (17 downto 0);
    signal tmp_7_reg_968 : STD_LOGIC_VECTOR (0 downto 0);
    signal col_sum_fu_558_p3 : STD_LOGIC_VECTOR (23 downto 0);
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal conv7_i_fu_644_p1 : STD_LOGIC_VECTOR (47 downto 0);
    signal conv7_i_reg_979 : STD_LOGIC_VECTOR (47 downto 0);
    signal ap_CS_fsm_state9 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state9 : signal is "none";
    signal add_ln43_fu_654_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln43_reg_987 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_CS_fsm_state10 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state10 : signal is "none";
    signal zext_ln44_1_fu_677_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln44_1_reg_992 : STD_LOGIC_VECTOR (63 downto 0);
    signal select_ln44_3_fu_893_p3 : STD_LOGIC_VECTOR (23 downto 0);
    signal select_ln44_3_reg_1002 : STD_LOGIC_VECTOR (23 downto 0);
    signal ap_CS_fsm_state11 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state11 : signal is "none";
    signal grp_top_kernel_Pipeline_VITIS_LOOP_15_2_fu_214_ap_start : STD_LOGIC;
    signal grp_top_kernel_Pipeline_VITIS_LOOP_15_2_fu_214_ap_done : STD_LOGIC;
    signal grp_top_kernel_Pipeline_VITIS_LOOP_15_2_fu_214_ap_idle : STD_LOGIC;
    signal grp_top_kernel_Pipeline_VITIS_LOOP_15_2_fu_214_ap_ready : STD_LOGIC;
    signal grp_top_kernel_Pipeline_VITIS_LOOP_15_2_fu_214_A_address0 : STD_LOGIC_VECTOR (13 downto 0);
    signal grp_top_kernel_Pipeline_VITIS_LOOP_15_2_fu_214_A_ce0 : STD_LOGIC;
    signal grp_top_kernel_Pipeline_VITIS_LOOP_15_2_fu_214_p_out : STD_LOGIC_VECTOR (23 downto 0);
    signal grp_top_kernel_Pipeline_VITIS_LOOP_15_2_fu_214_p_out_ap_vld : STD_LOGIC;
    signal grp_top_kernel_Pipeline_VITIS_LOOP_24_3_fu_222_ap_start : STD_LOGIC;
    signal grp_top_kernel_Pipeline_VITIS_LOOP_24_3_fu_222_ap_done : STD_LOGIC;
    signal grp_top_kernel_Pipeline_VITIS_LOOP_24_3_fu_222_ap_idle : STD_LOGIC;
    signal grp_top_kernel_Pipeline_VITIS_LOOP_24_3_fu_222_ap_ready : STD_LOGIC;
    signal grp_top_kernel_Pipeline_VITIS_LOOP_24_3_fu_222_A_address0 : STD_LOGIC_VECTOR (13 downto 0);
    signal grp_top_kernel_Pipeline_VITIS_LOOP_24_3_fu_222_A_ce0 : STD_LOGIC;
    signal grp_top_kernel_Pipeline_VITIS_LOOP_24_3_fu_222_tmp_address0 : STD_LOGIC_VECTOR (13 downto 0);
    signal grp_top_kernel_Pipeline_VITIS_LOOP_24_3_fu_222_tmp_ce0 : STD_LOGIC;
    signal grp_top_kernel_Pipeline_VITIS_LOOP_24_3_fu_222_tmp_we0 : STD_LOGIC;
    signal grp_top_kernel_Pipeline_VITIS_LOOP_24_3_fu_222_tmp_d0 : STD_LOGIC_VECTOR (23 downto 0);
    signal i_1_reg_180 : STD_LOGIC_VECTOR (8 downto 0);
    signal icmp_ln31_fu_355_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal empty_reg_191 : STD_LOGIC_VECTOR (23 downto 0);
    signal i_2_reg_203 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_CS_fsm_state12 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state12 : signal is "none";
    signal grp_top_kernel_Pipeline_VITIS_LOOP_15_2_fu_214_ap_start_reg : STD_LOGIC := '0';
    signal icmp_ln11_fu_249_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal grp_top_kernel_Pipeline_VITIS_LOOP_24_3_fu_222_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal zext_ln36_fu_400_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal icmp_ln35_fu_371_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln43_fu_648_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal i_fu_134 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    signal add_ln11_fu_255_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal j_fu_142 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    signal tmp_ce0_local : STD_LOGIC;
    signal tmp_address0_local : STD_LOGIC_VECTOR (13 downto 0);
    signal C_we0_local : STD_LOGIC;
    signal C_ce0_local : STD_LOGIC;
    signal mul_ln44_fu_232_p1 : STD_LOGIC_VECTOR (23 downto 0);
    signal mul_ln40_fu_236_p1 : STD_LOGIC_VECTOR (41 downto 0);
    signal trunc_ln11_fu_261_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal sext_ln21_fu_287_p1 : STD_LOGIC_VECTOR (24 downto 0);
    signal add_ln21_fu_291_p2 : STD_LOGIC_VECTOR (24 downto 0);
    signal tmp_1_2_fu_297_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_3_fu_309_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln21_fu_317_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln21_fu_323_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln21_1_fu_329_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln21_fu_335_p3 : STD_LOGIC_VECTOR (23 downto 0);
    signal denom_fu_305_p1 : STD_LOGIC_VECTOR (23 downto 0);
    signal trunc_ln35_fu_383_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_1_fu_387_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal add_ln36_2_fu_395_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal shl_ln_fu_405_p3 : STD_LOGIC_VECTOR (39 downto 0);
    signal mul_ln40_fu_236_p2 : STD_LOGIC_VECTOR (80 downto 0);
    signal sub_ln40_fu_418_p2 : STD_LOGIC_VECTOR (80 downto 0);
    signal tmp_4_fu_424_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_19_cast_fu_432_p4 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_20_cast_fu_452_p4 : STD_LOGIC_VECTOR (16 downto 0);
    signal select_ln40_1_fu_462_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal zext_ln40_fu_470_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal sub_ln40_1_fu_474_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal tmp_20_cast4_fu_442_p4 : STD_LOGIC_VECTOR (17 downto 0);
    signal sext_ln36_1_fu_500_p0 : STD_LOGIC_VECTOR (23 downto 0);
    signal add_ln36_fu_504_p0 : STD_LOGIC_VECTOR (23 downto 0);
    signal sext_ln36_1_fu_500_p1 : STD_LOGIC_VECTOR (24 downto 0);
    signal sext_ln36_fu_496_p1 : STD_LOGIC_VECTOR (24 downto 0);
    signal add_ln36_1_fu_510_p2 : STD_LOGIC_VECTOR (24 downto 0);
    signal add_ln36_fu_504_p2 : STD_LOGIC_VECTOR (23 downto 0);
    signal tmp_8_fu_516_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_9_fu_524_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln36_fu_532_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln36_fu_538_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln36_1_fu_544_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln36_fu_550_p3 : STD_LOGIC_VECTOR (23 downto 0);
    signal sext_ln40_1_fu_566_p1 : STD_LOGIC_VECTOR (39 downto 0);
    signal tmp_6_fu_580_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_5_fu_569_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln40_fu_588_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln40_fu_593_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln40_2_fu_605_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln40_1_fu_610_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln40_fu_599_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln40_1_fu_616_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln40_1_fu_630_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln40_fu_622_p3 : STD_LOGIC_VECTOR (23 downto 0);
    signal sext_ln40_2_fu_577_p1 : STD_LOGIC_VECTOR (23 downto 0);
    signal scale_1_fu_636_p3 : STD_LOGIC_VECTOR (23 downto 0);
    signal trunc_ln43_fu_660_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_2_fu_664_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal add_ln44_1_fu_672_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal mul_ln44_fu_232_p2 : STD_LOGIC_VECTOR (47 downto 0);
    signal tmp_11_fu_709_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln2_fu_699_p4 : STD_LOGIC_VECTOR (23 downto 0);
    signal zext_ln44_fu_725_p1 : STD_LOGIC_VECTOR (23 downto 0);
    signal add_ln44_fu_729_p2 : STD_LOGIC_VECTOR (23 downto 0);
    signal tmp_13_fu_735_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_12_fu_717_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln44_fu_743_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_15_fu_763_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_16_fu_777_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal and_ln44_fu_749_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln44_1_fu_785_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln44_2_fu_791_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_14_fu_755_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln44_fu_771_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln44_1_fu_805_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln44_1_fu_811_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln44_fu_797_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln44_2_fu_831_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_10_fu_691_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln44_fu_837_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln44_3_fu_843_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln44_1_fu_817_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln44_2_fu_825_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln44_4_fu_855_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln44_2_fu_861_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln44_4_fu_867_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln44_3_fu_849_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln44_5_fu_873_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln44_1_fu_887_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln44_2_fu_879_p3 : STD_LOGIC_VECTOR (23 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_ST_fsm_state9_blk : STD_LOGIC;
    signal ap_ST_fsm_state10_blk : STD_LOGIC;
    signal ap_ST_fsm_state11_blk : STD_LOGIC;
    signal ap_ST_fsm_state12_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component top_kernel_top_kernel_Pipeline_VITIS_LOOP_15_2 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        zext_ln26 : IN STD_LOGIC_VECTOR (13 downto 0);
        A_address0 : OUT STD_LOGIC_VECTOR (13 downto 0);
        A_ce0 : OUT STD_LOGIC;
        A_q0 : IN STD_LOGIC_VECTOR (23 downto 0);
        p_out : OUT STD_LOGIC_VECTOR (23 downto 0);
        p_out_ap_vld : OUT STD_LOGIC );
    end component;


    component top_kernel_top_kernel_Pipeline_VITIS_LOOP_24_3 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        zext_ln26 : IN STD_LOGIC_VECTOR (13 downto 0);
        A_address0 : OUT STD_LOGIC_VECTOR (13 downto 0);
        A_ce0 : OUT STD_LOGIC;
        A_q0 : IN STD_LOGIC_VECTOR (23 downto 0);
        conv_i362 : IN STD_LOGIC_VECTOR (23 downto 0);
        tmp_address0 : OUT STD_LOGIC_VECTOR (13 downto 0);
        tmp_ce0 : OUT STD_LOGIC;
        tmp_we0 : OUT STD_LOGIC;
        tmp_d0 : OUT STD_LOGIC_VECTOR (23 downto 0) );
    end component;


    component top_kernel_mul_24s_24s_48_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (23 downto 0);
        din1 : IN STD_LOGIC_VECTOR (23 downto 0);
        dout : OUT STD_LOGIC_VECTOR (47 downto 0) );
    end component;


    component top_kernel_mul_40s_42ns_81_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (39 downto 0);
        din1 : IN STD_LOGIC_VECTOR (41 downto 0);
        dout : OUT STD_LOGIC_VECTOR (80 downto 0) );
    end component;


    component top_kernel_tmp_RAM_AUTO_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (13 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (23 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (23 downto 0) );
    end component;



begin
    tmp_U : component top_kernel_tmp_RAM_AUTO_1R1W
    generic map (
        DataWidth => 24,
        AddressRange => 16384,
        AddressWidth => 14)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => tmp_address0,
        ce0 => tmp_ce0,
        we0 => tmp_we0,
        d0 => grp_top_kernel_Pipeline_VITIS_LOOP_24_3_fu_222_tmp_d0,
        q0 => tmp_q0);

    grp_top_kernel_Pipeline_VITIS_LOOP_15_2_fu_214 : component top_kernel_top_kernel_Pipeline_VITIS_LOOP_15_2
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_top_kernel_Pipeline_VITIS_LOOP_15_2_fu_214_ap_start,
        ap_done => grp_top_kernel_Pipeline_VITIS_LOOP_15_2_fu_214_ap_done,
        ap_idle => grp_top_kernel_Pipeline_VITIS_LOOP_15_2_fu_214_ap_idle,
        ap_ready => grp_top_kernel_Pipeline_VITIS_LOOP_15_2_fu_214_ap_ready,
        zext_ln26 => tmp_s_reg_917,
        A_address0 => grp_top_kernel_Pipeline_VITIS_LOOP_15_2_fu_214_A_address0,
        A_ce0 => grp_top_kernel_Pipeline_VITIS_LOOP_15_2_fu_214_A_ce0,
        A_q0 => A_q0,
        p_out => grp_top_kernel_Pipeline_VITIS_LOOP_15_2_fu_214_p_out,
        p_out_ap_vld => grp_top_kernel_Pipeline_VITIS_LOOP_15_2_fu_214_p_out_ap_vld);

    grp_top_kernel_Pipeline_VITIS_LOOP_24_3_fu_222 : component top_kernel_top_kernel_Pipeline_VITIS_LOOP_24_3
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_top_kernel_Pipeline_VITIS_LOOP_24_3_fu_222_ap_start,
        ap_done => grp_top_kernel_Pipeline_VITIS_LOOP_24_3_fu_222_ap_done,
        ap_idle => grp_top_kernel_Pipeline_VITIS_LOOP_24_3_fu_222_ap_idle,
        ap_ready => grp_top_kernel_Pipeline_VITIS_LOOP_24_3_fu_222_ap_ready,
        zext_ln26 => tmp_s_reg_917,
        A_address0 => grp_top_kernel_Pipeline_VITIS_LOOP_24_3_fu_222_A_address0,
        A_ce0 => grp_top_kernel_Pipeline_VITIS_LOOP_24_3_fu_222_A_ce0,
        A_q0 => A_q0,
        conv_i362 => denom_1_reg_930,
        tmp_address0 => grp_top_kernel_Pipeline_VITIS_LOOP_24_3_fu_222_tmp_address0,
        tmp_ce0 => grp_top_kernel_Pipeline_VITIS_LOOP_24_3_fu_222_tmp_ce0,
        tmp_we0 => grp_top_kernel_Pipeline_VITIS_LOOP_24_3_fu_222_tmp_we0,
        tmp_d0 => grp_top_kernel_Pipeline_VITIS_LOOP_24_3_fu_222_tmp_d0);

    mul_24s_24s_48_1_1_U10 : component top_kernel_mul_24s_24s_48_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 24,
        din1_WIDTH => 24,
        dout_WIDTH => 48)
    port map (
        din0 => tmp_q0,
        din1 => mul_ln44_fu_232_p1,
        dout => mul_ln44_fu_232_p2);

    mul_40s_42ns_81_1_1_U11 : component top_kernel_mul_40s_42ns_81_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 40,
        din1_WIDTH => 42,
        dout_WIDTH => 81)
    port map (
        din0 => shl_ln_fu_405_p3,
        din1 => mul_ln40_fu_236_p1,
        dout => mul_ln40_fu_236_p2);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_top_kernel_Pipeline_VITIS_LOOP_15_2_fu_214_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_top_kernel_Pipeline_VITIS_LOOP_15_2_fu_214_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln11_fu_249_p2 = ap_const_lv1_0))) then 
                    grp_top_kernel_Pipeline_VITIS_LOOP_15_2_fu_214_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_top_kernel_Pipeline_VITIS_LOOP_15_2_fu_214_ap_ready = ap_const_logic_1)) then 
                    grp_top_kernel_Pipeline_VITIS_LOOP_15_2_fu_214_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_top_kernel_Pipeline_VITIS_LOOP_24_3_fu_222_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_top_kernel_Pipeline_VITIS_LOOP_24_3_fu_222_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
                    grp_top_kernel_Pipeline_VITIS_LOOP_24_3_fu_222_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_top_kernel_Pipeline_VITIS_LOOP_24_3_fu_222_ap_ready = ap_const_logic_1)) then 
                    grp_top_kernel_Pipeline_VITIS_LOOP_24_3_fu_222_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    empty_reg_191_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
                empty_reg_191 <= col_sum_fu_558_p3;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state6) and (icmp_ln31_fu_355_p2 = ap_const_lv1_0))) then 
                empty_reg_191 <= ap_const_lv24_0;
            end if; 
        end if;
    end process;

    i_1_reg_180_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
                i_1_reg_180 <= add_ln35_reg_952;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state6) and (icmp_ln31_fu_355_p2 = ap_const_lv1_0))) then 
                i_1_reg_180 <= ap_const_lv9_0;
            end if; 
        end if;
    end process;

    i_2_reg_203_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state12)) then 
                i_2_reg_203 <= add_ln43_reg_987;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
                i_2_reg_203 <= ap_const_lv9_0;
            end if; 
        end if;
    end process;

    i_fu_134_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                i_fu_134 <= ap_const_lv9_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln11_fu_249_p2 = ap_const_lv1_0))) then 
                i_fu_134 <= add_ln11_fu_255_p2;
            end if; 
        end if;
    end process;

    j_fu_142_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln11_fu_249_p2 = ap_const_lv1_1))) then 
                j_fu_142 <= ap_const_lv7_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state10) and (icmp_ln43_fu_648_p2 = ap_const_lv1_1))) then 
                j_fu_142 <= add_ln31_reg_938;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state6)) then
                add_ln31_reg_938 <= add_ln31_fu_361_p2;
                    zext_ln31_reg_943(6 downto 0) <= zext_ln31_fu_367_p1(6 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state7)) then
                add_ln35_reg_952 <= add_ln35_fu_377_p2;
                scale_reg_962 <= scale_fu_480_p3;
                tmp_7_reg_968 <= scale_fu_480_p3(17 downto 17);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state10)) then
                add_ln43_reg_987 <= add_ln43_fu_654_p2;
                    zext_ln44_1_reg_992(13 downto 0) <= zext_ln44_1_fu_677_p1(13 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state9)) then
                conv7_i_reg_979 <= conv7_i_fu_644_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
                denom_1_reg_930 <= denom_1_fu_343_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state11)) then
                select_ln44_3_reg_1002 <= select_ln44_3_fu_893_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                    tmp_s_reg_917(13 downto 6) <= tmp_s_fu_265_p3(13 downto 6);
            end if;
        end if;
    end process;
    tmp_s_reg_917(5 downto 0) <= "000000";
    zext_ln31_reg_943(13 downto 7) <= "0000000";
    zext_ln44_1_reg_992(63 downto 14) <= "00000000000000000000000000000000000000000000000000";

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state2, ap_CS_fsm_state6, ap_CS_fsm_state7, ap_CS_fsm_state10, grp_top_kernel_Pipeline_VITIS_LOOP_15_2_fu_214_ap_done, grp_top_kernel_Pipeline_VITIS_LOOP_24_3_fu_222_ap_done, icmp_ln31_fu_355_p2, icmp_ln11_fu_249_p2, ap_CS_fsm_state3, ap_CS_fsm_state5, icmp_ln35_fu_371_p2, icmp_ln43_fu_648_p2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln11_fu_249_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state6;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state3 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_top_kernel_Pipeline_VITIS_LOOP_15_2_fu_214_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state5) and (grp_top_kernel_Pipeline_VITIS_LOOP_24_3_fu_222_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when ap_ST_fsm_state6 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state6) and (icmp_ln31_fu_355_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state7;
                end if;
            when ap_ST_fsm_state7 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state7) and (icmp_ln35_fu_371_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state9;
                else
                    ap_NS_fsm <= ap_ST_fsm_state8;
                end if;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state9 => 
                ap_NS_fsm <= ap_ST_fsm_state10;
            when ap_ST_fsm_state10 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state10) and (icmp_ln43_fu_648_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state6;
                else
                    ap_NS_fsm <= ap_ST_fsm_state11;
                end if;
            when ap_ST_fsm_state11 => 
                ap_NS_fsm <= ap_ST_fsm_state12;
            when ap_ST_fsm_state12 => 
                ap_NS_fsm <= ap_ST_fsm_state10;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXXXX";
        end case;
    end process;

    A_address0_assign_proc : process(grp_top_kernel_Pipeline_VITIS_LOOP_15_2_fu_214_A_address0, grp_top_kernel_Pipeline_VITIS_LOOP_24_3_fu_222_A_address0, ap_CS_fsm_state3, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            A_address0 <= grp_top_kernel_Pipeline_VITIS_LOOP_24_3_fu_222_A_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            A_address0 <= grp_top_kernel_Pipeline_VITIS_LOOP_15_2_fu_214_A_address0;
        else 
            A_address0 <= "XXXXXXXXXXXXXX";
        end if; 
    end process;


    A_ce0_assign_proc : process(grp_top_kernel_Pipeline_VITIS_LOOP_15_2_fu_214_A_ce0, grp_top_kernel_Pipeline_VITIS_LOOP_24_3_fu_222_A_ce0, ap_CS_fsm_state3, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            A_ce0 <= grp_top_kernel_Pipeline_VITIS_LOOP_24_3_fu_222_A_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            A_ce0 <= grp_top_kernel_Pipeline_VITIS_LOOP_15_2_fu_214_A_ce0;
        else 
            A_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    C_address0 <= zext_ln44_1_reg_992(14 - 1 downto 0);
    C_ce0 <= C_ce0_local;

    C_ce0_local_assign_proc : process(ap_CS_fsm_state12)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state12)) then 
            C_ce0_local <= ap_const_logic_1;
        else 
            C_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    C_d0 <= select_ln44_3_reg_1002;
    C_we0 <= C_we0_local;

    C_we0_local_assign_proc : process(ap_CS_fsm_state12)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state12)) then 
            C_we0_local <= ap_const_logic_1;
        else 
            C_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    add_ln11_fu_255_p2 <= std_logic_vector(unsigned(i_fu_134) + unsigned(ap_const_lv9_1));
    add_ln21_fu_291_p2 <= std_logic_vector(signed(sext_ln21_fu_287_p1) + signed(ap_const_lv25_10000));
    add_ln31_fu_361_p2 <= std_logic_vector(unsigned(j_fu_142) + unsigned(ap_const_lv7_1));
    add_ln35_fu_377_p2 <= std_logic_vector(unsigned(i_1_reg_180) + unsigned(ap_const_lv9_1));
    add_ln36_1_fu_510_p2 <= std_logic_vector(signed(sext_ln36_1_fu_500_p1) + signed(sext_ln36_fu_496_p1));
    add_ln36_2_fu_395_p2 <= std_logic_vector(unsigned(tmp_1_fu_387_p3) + unsigned(zext_ln31_reg_943));
    add_ln36_fu_504_p0 <= tmp_q0;
    add_ln36_fu_504_p2 <= std_logic_vector(signed(add_ln36_fu_504_p0) + signed(empty_reg_191));
    add_ln43_fu_654_p2 <= std_logic_vector(unsigned(i_2_reg_203) + unsigned(ap_const_lv9_1));
    add_ln44_1_fu_672_p2 <= std_logic_vector(unsigned(tmp_2_fu_664_p3) + unsigned(zext_ln31_reg_943));
    add_ln44_fu_729_p2 <= std_logic_vector(unsigned(trunc_ln2_fu_699_p4) + unsigned(zext_ln44_fu_725_p1));
    and_ln21_fu_323_p2 <= (xor_ln21_fu_317_p2 and tmp_3_fu_309_p3);
    and_ln36_fu_538_p2 <= (xor_ln36_fu_532_p2 and tmp_9_fu_524_p3);
    and_ln40_1_fu_616_p2 <= (xor_ln40_1_fu_610_p2 and tmp_5_fu_569_p3);
    and_ln40_2_fu_605_p2 <= (tmp_7_reg_968 and tmp_6_fu_580_p3);
    and_ln40_fu_599_p2 <= (xor_ln40_fu_593_p2 and or_ln40_fu_588_p2);
    and_ln44_1_fu_811_p2 <= (xor_ln44_1_fu_805_p2 and icmp_ln44_fu_771_p2);
    and_ln44_2_fu_825_p2 <= (icmp_ln44_1_fu_785_p2 and and_ln44_fu_749_p2);
    and_ln44_3_fu_849_p2 <= (xor_ln44_3_fu_843_p2 and or_ln44_fu_837_p2);
    and_ln44_4_fu_855_p2 <= (tmp_13_fu_735_p3 and select_ln44_1_fu_817_p3);
    and_ln44_5_fu_873_p2 <= (xor_ln44_4_fu_867_p2 and tmp_10_fu_691_p3);
    and_ln44_fu_749_p2 <= (xor_ln44_fu_743_p2 and tmp_12_fu_717_p3);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state10 <= ap_CS_fsm(9);
    ap_CS_fsm_state11 <= ap_CS_fsm(10);
    ap_CS_fsm_state12 <= ap_CS_fsm(11);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);
    ap_CS_fsm_state9 <= ap_CS_fsm(8);
    ap_ST_fsm_state10_blk <= ap_const_logic_0;
    ap_ST_fsm_state11_blk <= ap_const_logic_0;
    ap_ST_fsm_state12_blk <= ap_const_logic_0;

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;

    ap_ST_fsm_state3_blk_assign_proc : process(grp_top_kernel_Pipeline_VITIS_LOOP_15_2_fu_214_ap_done)
    begin
        if ((grp_top_kernel_Pipeline_VITIS_LOOP_15_2_fu_214_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state3_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state3_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state4_blk <= ap_const_logic_0;

    ap_ST_fsm_state5_blk_assign_proc : process(grp_top_kernel_Pipeline_VITIS_LOOP_24_3_fu_222_ap_done)
    begin
        if ((grp_top_kernel_Pipeline_VITIS_LOOP_24_3_fu_222_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state5_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state5_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state6_blk <= ap_const_logic_0;
    ap_ST_fsm_state7_blk <= ap_const_logic_0;
    ap_ST_fsm_state8_blk <= ap_const_logic_0;
    ap_ST_fsm_state9_blk <= ap_const_logic_0;

    ap_done_assign_proc : process(ap_CS_fsm_state6, icmp_ln31_fu_355_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state6) and (icmp_ln31_fu_355_p2 = ap_const_lv1_1))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state6, icmp_ln31_fu_355_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state6) and (icmp_ln31_fu_355_p2 = ap_const_lv1_1))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    col_sum_fu_558_p3 <= 
        select_ln36_fu_550_p3 when (xor_ln36_1_fu_544_p2(0) = '1') else 
        add_ln36_fu_504_p2;
        conv7_i_fu_644_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(scale_1_fu_636_p3),48));

    denom_1_fu_343_p3 <= 
        select_ln21_fu_335_p3 when (xor_ln21_1_fu_329_p2(0) = '1') else 
        denom_fu_305_p1;
    denom_fu_305_p1 <= add_ln21_fu_291_p2(24 - 1 downto 0);
    grp_top_kernel_Pipeline_VITIS_LOOP_15_2_fu_214_ap_start <= grp_top_kernel_Pipeline_VITIS_LOOP_15_2_fu_214_ap_start_reg;
    grp_top_kernel_Pipeline_VITIS_LOOP_24_3_fu_222_ap_start <= grp_top_kernel_Pipeline_VITIS_LOOP_24_3_fu_222_ap_start_reg;
    icmp_ln11_fu_249_p2 <= "1" when (i_fu_134 = ap_const_lv9_100) else "0";
    icmp_ln31_fu_355_p2 <= "1" when (j_fu_142 = ap_const_lv7_40) else "0";
    icmp_ln35_fu_371_p2 <= "1" when (i_1_reg_180 = ap_const_lv9_100) else "0";
    icmp_ln43_fu_648_p2 <= "1" when (i_2_reg_203 = ap_const_lv9_100) else "0";
    icmp_ln44_1_fu_785_p2 <= "1" when (tmp_16_fu_777_p3 = ap_const_lv8_FF) else "0";
    icmp_ln44_2_fu_791_p2 <= "1" when (tmp_16_fu_777_p3 = ap_const_lv8_0) else "0";
    icmp_ln44_fu_771_p2 <= "1" when (tmp_15_fu_763_p3 = ap_const_lv7_7F) else "0";
    mul_ln40_fu_236_p1 <= ap_const_lv81_10000020001(42 - 1 downto 0);
    mul_ln44_fu_232_p1 <= conv7_i_reg_979(24 - 1 downto 0);
    or_ln40_1_fu_630_p2 <= (and_ln40_fu_599_p2 or and_ln40_1_fu_616_p2);
    or_ln40_fu_588_p2 <= (tmp_7_reg_968 or tmp_6_fu_580_p3);
    or_ln44_1_fu_887_p2 <= (and_ln44_5_fu_873_p2 or and_ln44_3_fu_849_p2);
    or_ln44_2_fu_861_p2 <= (and_ln44_4_fu_855_p2 or and_ln44_2_fu_825_p2);
    or_ln44_fu_837_p2 <= (xor_ln44_2_fu_831_p2 or tmp_13_fu_735_p3);
    scale_1_fu_636_p3 <= 
        select_ln40_fu_622_p3 when (or_ln40_1_fu_630_p2(0) = '1') else 
        sext_ln40_2_fu_577_p1;
    scale_fu_480_p3 <= 
        sub_ln40_1_fu_474_p2 when (tmp_4_fu_424_p3(0) = '1') else 
        tmp_20_cast4_fu_442_p4;
    select_ln21_fu_335_p3 <= 
        ap_const_lv24_7FFFFF when (and_ln21_fu_323_p2(0) = '1') else 
        ap_const_lv24_800000;
    select_ln36_fu_550_p3 <= 
        ap_const_lv24_7FFFFF when (and_ln36_fu_538_p2(0) = '1') else 
        ap_const_lv24_800000;
    select_ln40_1_fu_462_p3 <= 
        tmp_19_cast_fu_432_p4 when (tmp_4_fu_424_p3(0) = '1') else 
        tmp_20_cast_fu_452_p4;
    select_ln40_fu_622_p3 <= 
        ap_const_lv24_7FFFFF when (and_ln40_fu_599_p2(0) = '1') else 
        ap_const_lv24_800000;
    select_ln44_1_fu_817_p3 <= 
        and_ln44_1_fu_811_p2 when (and_ln44_fu_749_p2(0) = '1') else 
        icmp_ln44_1_fu_785_p2;
    select_ln44_2_fu_879_p3 <= 
        ap_const_lv24_7FFFFF when (and_ln44_3_fu_849_p2(0) = '1') else 
        ap_const_lv24_800000;
    select_ln44_3_fu_893_p3 <= 
        select_ln44_2_fu_879_p3 when (or_ln44_1_fu_887_p2(0) = '1') else 
        add_ln44_fu_729_p2;
    select_ln44_fu_797_p3 <= 
        icmp_ln44_1_fu_785_p2 when (and_ln44_fu_749_p2(0) = '1') else 
        icmp_ln44_2_fu_791_p2;
        sext_ln21_fu_287_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(grp_top_kernel_Pipeline_VITIS_LOOP_15_2_fu_214_p_out),25));

    sext_ln36_1_fu_500_p0 <= tmp_q0;
        sext_ln36_1_fu_500_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln36_1_fu_500_p0),25));

        sext_ln36_fu_496_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(empty_reg_191),25));

        sext_ln40_1_fu_566_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(scale_reg_962),40));

        sext_ln40_2_fu_577_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(scale_reg_962),24));

    shl_ln_fu_405_p3 <= (empty_reg_191 & ap_const_lv16_0);
    sub_ln40_1_fu_474_p2 <= std_logic_vector(unsigned(ap_const_lv18_0) - unsigned(zext_ln40_fu_470_p1));
    sub_ln40_fu_418_p2 <= std_logic_vector(unsigned(ap_const_lv81_0) - unsigned(mul_ln40_fu_236_p2));
    tmp_10_fu_691_p3 <= mul_ln44_fu_232_p2(47 downto 47);
    tmp_11_fu_709_p3 <= mul_ln44_fu_232_p2(15 downto 15);
    tmp_12_fu_717_p3 <= mul_ln44_fu_232_p2(39 downto 39);
    tmp_13_fu_735_p3 <= add_ln44_fu_729_p2(23 downto 23);
    tmp_14_fu_755_p3 <= mul_ln44_fu_232_p2(40 downto 40);
    tmp_15_fu_763_p3 <= mul_ln44_fu_232_p2(47 downto 41);
    tmp_16_fu_777_p3 <= mul_ln44_fu_232_p2(47 downto 40);
    tmp_19_cast_fu_432_p4 <= sub_ln40_fu_418_p2(79 downto 63);
    tmp_1_2_fu_297_p3 <= add_ln21_fu_291_p2(24 downto 24);
    tmp_1_fu_387_p3 <= (trunc_ln35_fu_383_p1 & ap_const_lv6_0);
    tmp_20_cast4_fu_442_p4 <= mul_ln40_fu_236_p2(80 downto 63);
    tmp_20_cast_fu_452_p4 <= mul_ln40_fu_236_p2(79 downto 63);
    tmp_2_fu_664_p3 <= (trunc_ln43_fu_660_p1 & ap_const_lv6_0);
    tmp_3_fu_309_p3 <= add_ln21_fu_291_p2(23 downto 23);
    tmp_4_fu_424_p3 <= empty_reg_191(23 downto 23);
    tmp_5_fu_569_p3 <= sext_ln40_1_fu_566_p1(39 downto 39);
    tmp_6_fu_580_p3 <= sext_ln40_1_fu_566_p1(23 downto 23);
    tmp_8_fu_516_p3 <= add_ln36_1_fu_510_p2(24 downto 24);
    tmp_9_fu_524_p3 <= add_ln36_fu_504_p2(23 downto 23);

    tmp_address0_assign_proc : process(grp_top_kernel_Pipeline_VITIS_LOOP_24_3_fu_222_tmp_address0, ap_CS_fsm_state5, tmp_address0_local)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            tmp_address0 <= grp_top_kernel_Pipeline_VITIS_LOOP_24_3_fu_222_tmp_address0;
        else 
            tmp_address0 <= tmp_address0_local;
        end if; 
    end process;


    tmp_address0_local_assign_proc : process(ap_CS_fsm_state7, ap_CS_fsm_state10, zext_ln44_1_fu_677_p1, zext_ln36_fu_400_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            tmp_address0_local <= zext_ln44_1_fu_677_p1(14 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            tmp_address0_local <= zext_ln36_fu_400_p1(14 - 1 downto 0);
        else 
            tmp_address0_local <= "XXXXXXXXXXXXXX";
        end if; 
    end process;


    tmp_ce0_assign_proc : process(grp_top_kernel_Pipeline_VITIS_LOOP_24_3_fu_222_tmp_ce0, ap_CS_fsm_state5, tmp_ce0_local)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            tmp_ce0 <= grp_top_kernel_Pipeline_VITIS_LOOP_24_3_fu_222_tmp_ce0;
        else 
            tmp_ce0 <= tmp_ce0_local;
        end if; 
    end process;


    tmp_ce0_local_assign_proc : process(ap_CS_fsm_state7, ap_CS_fsm_state10)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state7) or (ap_const_logic_1 = ap_CS_fsm_state10))) then 
            tmp_ce0_local <= ap_const_logic_1;
        else 
            tmp_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    tmp_s_fu_265_p3 <= (trunc_ln11_fu_261_p1 & ap_const_lv6_0);

    tmp_we0_assign_proc : process(grp_top_kernel_Pipeline_VITIS_LOOP_24_3_fu_222_tmp_we0, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            tmp_we0 <= grp_top_kernel_Pipeline_VITIS_LOOP_24_3_fu_222_tmp_we0;
        else 
            tmp_we0 <= ap_const_logic_0;
        end if; 
    end process;

    trunc_ln11_fu_261_p1 <= i_fu_134(8 - 1 downto 0);
    trunc_ln2_fu_699_p4 <= mul_ln44_fu_232_p2(39 downto 16);
    trunc_ln35_fu_383_p1 <= i_1_reg_180(8 - 1 downto 0);
    trunc_ln43_fu_660_p1 <= i_2_reg_203(8 - 1 downto 0);
    xor_ln21_1_fu_329_p2 <= (tmp_3_fu_309_p3 xor tmp_1_2_fu_297_p3);
    xor_ln21_fu_317_p2 <= (tmp_1_2_fu_297_p3 xor ap_const_lv1_1);
    xor_ln36_1_fu_544_p2 <= (tmp_9_fu_524_p3 xor tmp_8_fu_516_p3);
    xor_ln36_fu_532_p2 <= (tmp_8_fu_516_p3 xor ap_const_lv1_1);
    xor_ln40_1_fu_610_p2 <= (ap_const_lv1_1 xor and_ln40_2_fu_605_p2);
    xor_ln40_fu_593_p2 <= (tmp_5_fu_569_p3 xor ap_const_lv1_1);
    xor_ln44_1_fu_805_p2 <= (tmp_14_fu_755_p3 xor ap_const_lv1_1);
    xor_ln44_2_fu_831_p2 <= (select_ln44_fu_797_p3 xor ap_const_lv1_1);
    xor_ln44_3_fu_843_p2 <= (tmp_10_fu_691_p3 xor ap_const_lv1_1);
    xor_ln44_4_fu_867_p2 <= (or_ln44_2_fu_861_p2 xor ap_const_lv1_1);
    xor_ln44_fu_743_p2 <= (tmp_13_fu_735_p3 xor ap_const_lv1_1);
    zext_ln31_fu_367_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(j_fu_142),14));
    zext_ln36_fu_400_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln36_2_fu_395_p2),64));
    zext_ln40_fu_470_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln40_1_fu_462_p3),18));
    zext_ln44_1_fu_677_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln44_1_fu_672_p2),64));
    zext_ln44_fu_725_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_11_fu_709_p3),24));
end behav;
