-- ==============================================================
-- Generated by Vitis HLS v2025.1.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity top_kernel_top_kernel_Pipeline_VITIS_LOOP_44_6 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    zext_ln31 : IN STD_LOGIC_VECTOR (5 downto 0);
    C_address0 : OUT STD_LOGIC_VECTOR (13 downto 0);
    C_ce0 : OUT STD_LOGIC;
    C_we0 : OUT STD_LOGIC;
    C_d0 : OUT STD_LOGIC_VECTOR (23 downto 0);
    conv7_i : IN STD_LOGIC_VECTOR (23 downto 0);
    tmp_address0 : OUT STD_LOGIC_VECTOR (13 downto 0);
    tmp_ce0 : OUT STD_LOGIC;
    tmp_q0 : IN STD_LOGIC_VECTOR (23 downto 0) );
end;


architecture behav of top_kernel_top_kernel_Pipeline_VITIS_LOOP_44_6 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    constant ap_const_lv9_100 : STD_LOGIC_VECTOR (8 downto 0) := "100000000";
    constant ap_const_lv9_1 : STD_LOGIC_VECTOR (8 downto 0) := "000000001";
    constant ap_const_lv32_2F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101111";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_27 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100111";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_28 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101000";
    constant ap_const_lv32_29 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101001";
    constant ap_const_lv7_7F : STD_LOGIC_VECTOR (6 downto 0) := "1111111";
    constant ap_const_lv8_FF : STD_LOGIC_VECTOR (7 downto 0) := "11111111";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv24_7FFFFF : STD_LOGIC_VECTOR (23 downto 0) := "011111111111111111111111";
    constant ap_const_lv24_800000 : STD_LOGIC_VECTOR (23 downto 0) := "100000000000000000000000";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln44_fu_138_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal conv7_i_cast_fu_126_p1 : STD_LOGIC_VECTOR (47 downto 0);
    signal conv7_i_cast_reg_394 : STD_LOGIC_VECTOR (47 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal zext_ln46_1_fu_162_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln46_1_reg_403 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln46_1_reg_403_pp0_iter1_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal select_ln46_3_fu_379_p3 : STD_LOGIC_VECTOR (23 downto 0);
    signal select_ln46_3_reg_413 : STD_LOGIC_VECTOR (23 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal i_fu_80 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    signal add_ln44_fu_144_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_i_1 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_ce0_local : STD_LOGIC;
    signal C_we0_local : STD_LOGIC;
    signal C_ce0_local : STD_LOGIC;
    signal mul_ln46_fu_122_p1 : STD_LOGIC_VECTOR (23 downto 0);
    signal trunc_ln44_fu_150_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln46_1_fu_154_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal mul_ln46_fu_122_p2 : STD_LOGIC_VECTOR (47 downto 0);
    signal tmp_1_fu_195_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln2_fu_185_p4 : STD_LOGIC_VECTOR (23 downto 0);
    signal zext_ln46_fu_211_p1 : STD_LOGIC_VECTOR (23 downto 0);
    signal add_ln46_fu_215_p2 : STD_LOGIC_VECTOR (23 downto 0);
    signal tmp_3_fu_221_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_2_fu_203_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln46_fu_229_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_s_fu_249_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_5_fu_263_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal and_ln46_fu_235_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln46_1_fu_271_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln46_2_fu_277_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_4_fu_241_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln46_fu_257_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln46_1_fu_291_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln46_1_fu_297_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln46_fu_283_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln46_2_fu_317_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_1_1_fu_177_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln46_fu_323_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln46_3_fu_329_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln46_1_fu_303_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln46_2_fu_311_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln46_4_fu_341_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln46_2_fu_347_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln46_4_fu_353_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln46_3_fu_335_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln46_5_fu_359_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln46_1_fu_373_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln46_2_fu_365_p3 : STD_LOGIC_VECTOR (23 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component top_kernel_mul_24s_24s_48_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (23 downto 0);
        din1 : IN STD_LOGIC_VECTOR (23 downto 0);
        dout : OUT STD_LOGIC_VECTOR (47 downto 0) );
    end component;


    component top_kernel_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    mul_24s_24s_48_1_1_U13 : component top_kernel_mul_24s_24s_48_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 24,
        din1_WIDTH => 24,
        dout_WIDTH => 48)
    port map (
        din0 => tmp_q0,
        din1 => mul_ln46_fu_122_p1,
        dout => mul_ln46_fu_122_p2);

    flow_control_loop_pipe_sequential_init_U : component top_kernel_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    i_fu_80_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln44_fu_138_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    i_fu_80 <= add_ln44_fu_144_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    i_fu_80 <= ap_const_lv9_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                conv7_i_cast_reg_394 <= conv7_i_cast_fu_126_p1;
                select_ln46_3_reg_413 <= select_ln46_3_fu_379_p3;
                    zext_ln46_1_reg_403(13 downto 0) <= zext_ln46_1_fu_162_p1(13 downto 0);
                    zext_ln46_1_reg_403_pp0_iter1_reg(13 downto 0) <= zext_ln46_1_reg_403(13 downto 0);
            end if;
        end if;
    end process;
    zext_ln46_1_reg_403(63 downto 14) <= "00000000000000000000000000000000000000000000000000";
    zext_ln46_1_reg_403_pp0_iter1_reg(63 downto 14) <= "00000000000000000000000000000000000000000000000000";

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    C_address0 <= zext_ln46_1_reg_403_pp0_iter1_reg(14 - 1 downto 0);
    C_ce0 <= C_ce0_local;

    C_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            C_ce0_local <= ap_const_logic_1;
        else 
            C_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    C_d0 <= select_ln46_3_reg_413;
    C_we0 <= C_we0_local;

    C_we0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            C_we0_local <= ap_const_logic_1;
        else 
            C_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    add_ln44_fu_144_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_i_1) + unsigned(ap_const_lv9_1));
    add_ln46_1_fu_154_p3 <= (trunc_ln44_fu_150_p1 & zext_ln31);
    add_ln46_fu_215_p2 <= std_logic_vector(unsigned(trunc_ln2_fu_185_p4) + unsigned(zext_ln46_fu_211_p1));
    and_ln46_1_fu_297_p2 <= (xor_ln46_1_fu_291_p2 and icmp_ln46_fu_257_p2);
    and_ln46_2_fu_311_p2 <= (icmp_ln46_1_fu_271_p2 and and_ln46_fu_235_p2);
    and_ln46_3_fu_335_p2 <= (xor_ln46_3_fu_329_p2 and or_ln46_fu_323_p2);
    and_ln46_4_fu_341_p2 <= (tmp_3_fu_221_p3 and select_ln46_1_fu_303_p3);
    and_ln46_5_fu_359_p2 <= (xor_ln46_4_fu_353_p2 and tmp_1_1_fu_177_p3);
    and_ln46_fu_235_p2 <= (xor_ln46_fu_229_p2 and tmp_2_fu_203_p3);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln44_fu_138_p2)
    begin
        if (((icmp_ln44_fu_138_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_i_1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, i_fu_80, ap_loop_init)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_i_1 <= ap_const_lv9_0;
        else 
            ap_sig_allocacmp_i_1 <= i_fu_80;
        end if; 
    end process;

        conv7_i_cast_fu_126_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(conv7_i),48));

    icmp_ln44_fu_138_p2 <= "1" when (ap_sig_allocacmp_i_1 = ap_const_lv9_100) else "0";
    icmp_ln46_1_fu_271_p2 <= "1" when (tmp_5_fu_263_p3 = ap_const_lv8_FF) else "0";
    icmp_ln46_2_fu_277_p2 <= "1" when (tmp_5_fu_263_p3 = ap_const_lv8_0) else "0";
    icmp_ln46_fu_257_p2 <= "1" when (tmp_s_fu_249_p3 = ap_const_lv7_7F) else "0";
    mul_ln46_fu_122_p1 <= conv7_i_cast_reg_394(24 - 1 downto 0);
    or_ln46_1_fu_373_p2 <= (and_ln46_5_fu_359_p2 or and_ln46_3_fu_335_p2);
    or_ln46_2_fu_347_p2 <= (and_ln46_4_fu_341_p2 or and_ln46_2_fu_311_p2);
    or_ln46_fu_323_p2 <= (xor_ln46_2_fu_317_p2 or tmp_3_fu_221_p3);
    select_ln46_1_fu_303_p3 <= 
        and_ln46_1_fu_297_p2 when (and_ln46_fu_235_p2(0) = '1') else 
        icmp_ln46_1_fu_271_p2;
    select_ln46_2_fu_365_p3 <= 
        ap_const_lv24_7FFFFF when (and_ln46_3_fu_335_p2(0) = '1') else 
        ap_const_lv24_800000;
    select_ln46_3_fu_379_p3 <= 
        select_ln46_2_fu_365_p3 when (or_ln46_1_fu_373_p2(0) = '1') else 
        add_ln46_fu_215_p2;
    select_ln46_fu_283_p3 <= 
        icmp_ln46_1_fu_271_p2 when (and_ln46_fu_235_p2(0) = '1') else 
        icmp_ln46_2_fu_277_p2;
    tmp_1_1_fu_177_p3 <= mul_ln46_fu_122_p2(47 downto 47);
    tmp_1_fu_195_p3 <= mul_ln46_fu_122_p2(15 downto 15);
    tmp_2_fu_203_p3 <= mul_ln46_fu_122_p2(39 downto 39);
    tmp_3_fu_221_p3 <= add_ln46_fu_215_p2(23 downto 23);
    tmp_4_fu_241_p3 <= mul_ln46_fu_122_p2(40 downto 40);
    tmp_5_fu_263_p3 <= mul_ln46_fu_122_p2(47 downto 40);
    tmp_address0 <= zext_ln46_1_fu_162_p1(14 - 1 downto 0);
    tmp_ce0 <= tmp_ce0_local;

    tmp_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            tmp_ce0_local <= ap_const_logic_1;
        else 
            tmp_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    tmp_s_fu_249_p3 <= mul_ln46_fu_122_p2(47 downto 41);
    trunc_ln2_fu_185_p4 <= mul_ln46_fu_122_p2(39 downto 16);
    trunc_ln44_fu_150_p1 <= ap_sig_allocacmp_i_1(8 - 1 downto 0);
    xor_ln46_1_fu_291_p2 <= (tmp_4_fu_241_p3 xor ap_const_lv1_1);
    xor_ln46_2_fu_317_p2 <= (select_ln46_fu_283_p3 xor ap_const_lv1_1);
    xor_ln46_3_fu_329_p2 <= (tmp_1_1_fu_177_p3 xor ap_const_lv1_1);
    xor_ln46_4_fu_353_p2 <= (or_ln46_2_fu_347_p2 xor ap_const_lv1_1);
    xor_ln46_fu_229_p2 <= (tmp_3_fu_221_p3 xor ap_const_lv1_1);
    zext_ln46_1_fu_162_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln46_1_fu_154_p3),64));
    zext_ln46_fu_211_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_1_fu_195_p3),24));
end behav;
