// ==============================================================
// Generated by Vitis HLS v2025.1.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module top_kernel_top_kernel_Pipeline_VITIS_LOOP_35_5 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        zext_ln31,
        p_out,
        p_out_ap_vld,
        tmp_address0,
        tmp_ce0,
        tmp_q0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [5:0] zext_ln31;
output  [23:0] p_out;
output   p_out_ap_vld;
output  [13:0] tmp_address0;
output   tmp_ce0;
input  [23:0] tmp_q0;

reg ap_idle;
reg p_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln35_fu_99_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
wire   [63:0] zext_ln37_fu_123_p1;
wire    ap_block_pp0_stage0;
reg   [23:0] empty_fu_52;
wire   [23:0] select_ln37_1_fu_198_p3;
wire    ap_loop_init;
reg   [8:0] i_1_fu_56;
wire   [8:0] add_ln35_fu_105_p2;
reg   [8:0] ap_sig_allocacmp_i;
wire    ap_block_pp0_stage0_01001;
reg    tmp_ce0_local;
wire   [7:0] trunc_ln35_fu_111_p1;
wire   [13:0] add_ln37_2_fu_115_p3;
wire  signed [23:0] sext_ln37_fu_136_p0;
wire  signed [23:0] sext_ln37_1_fu_140_p0;
wire  signed [23:0] add_ln37_fu_144_p0;
wire  signed [23:0] add_ln37_fu_144_p1;
wire  signed [24:0] sext_ln37_1_fu_140_p1;
wire  signed [24:0] sext_ln37_fu_136_p1;
wire   [24:0] add_ln37_1_fu_150_p2;
wire   [23:0] add_ln37_fu_144_p2;
wire   [0:0] tmp_1_fu_156_p3;
wire   [0:0] tmp_5_fu_164_p3;
wire   [0:0] xor_ln37_fu_172_p2;
wire   [0:0] and_ln37_fu_178_p2;
wire   [0:0] xor_ln37_1_fu_184_p2;
wire   [23:0] select_ln37_fu_190_p3;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 empty_fu_52 = 24'd0;
#0 i_1_fu_56 = 9'd0;
#0 ap_done_reg = 1'b0;
end

top_kernel_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            empty_fu_52 <= 24'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            empty_fu_52 <= select_ln37_1_fu_198_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln35_fu_99_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_1_fu_56 <= add_ln35_fu_105_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_1_fu_56 <= 9'd0;
        end
    end
end

always @ (*) begin
    if (((icmp_ln35_fu_99_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_i = 9'd0;
    end else begin
        ap_sig_allocacmp_i = i_1_fu_56;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln35_fu_99_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_out_ap_vld = 1'b1;
    end else begin
        p_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        tmp_ce0_local = 1'b1;
    end else begin
        tmp_ce0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln35_fu_105_p2 = (ap_sig_allocacmp_i + 9'd1);

assign add_ln37_1_fu_150_p2 = ($signed(sext_ln37_1_fu_140_p1) + $signed(sext_ln37_fu_136_p1));

assign add_ln37_2_fu_115_p3 = {{trunc_ln35_fu_111_p1}, {zext_ln31}};

assign add_ln37_fu_144_p0 = tmp_q0;

assign add_ln37_fu_144_p1 = empty_fu_52;

assign add_ln37_fu_144_p2 = ($signed(add_ln37_fu_144_p0) + $signed(add_ln37_fu_144_p1));

assign and_ln37_fu_178_p2 = (xor_ln37_fu_172_p2 & tmp_5_fu_164_p3);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign icmp_ln35_fu_99_p2 = ((ap_sig_allocacmp_i == 9'd256) ? 1'b1 : 1'b0);

assign p_out = empty_fu_52;

assign select_ln37_1_fu_198_p3 = ((xor_ln37_1_fu_184_p2[0:0] == 1'b1) ? select_ln37_fu_190_p3 : add_ln37_fu_144_p2);

assign select_ln37_fu_190_p3 = ((and_ln37_fu_178_p2[0:0] == 1'b1) ? 24'd8388607 : 24'd8388608);

assign sext_ln37_1_fu_140_p0 = tmp_q0;

assign sext_ln37_1_fu_140_p1 = sext_ln37_1_fu_140_p0;

assign sext_ln37_fu_136_p0 = empty_fu_52;

assign sext_ln37_fu_136_p1 = sext_ln37_fu_136_p0;

assign tmp_1_fu_156_p3 = add_ln37_1_fu_150_p2[32'd24];

assign tmp_5_fu_164_p3 = add_ln37_fu_144_p2[32'd23];

assign tmp_address0 = zext_ln37_fu_123_p1;

assign tmp_ce0 = tmp_ce0_local;

assign trunc_ln35_fu_111_p1 = ap_sig_allocacmp_i[7:0];

assign xor_ln37_1_fu_184_p2 = (tmp_5_fu_164_p3 ^ tmp_1_fu_156_p3);

assign xor_ln37_fu_172_p2 = (tmp_1_fu_156_p3 ^ 1'd1);

assign zext_ln37_fu_123_p1 = add_ln37_2_fu_115_p3;

endmodule //top_kernel_top_kernel_Pipeline_VITIS_LOOP_35_5
