// ==============================================================
// Generated by Vitis HLS v2025.1.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="top_kernel_top_kernel,hls_ip_2025_1_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xczu3eg-sbva484-1-e,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.276500,HLS_SYN_LAT=79234,HLS_SYN_TPT=none,HLS_SYN_MEM=22,HLS_SYN_DSP=0,HLS_SYN_FF=4000,HLS_SYN_LUT=4104,HLS_VERSION=2025_1_1}" *)

module top_kernel (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        A_address0,
        A_ce0,
        A_q0,
        C_address0,
        C_ce0,
        C_we0,
        C_d0
);

parameter    ap_ST_fsm_state1 = 10'd1;
parameter    ap_ST_fsm_state2 = 10'd2;
parameter    ap_ST_fsm_state3 = 10'd4;
parameter    ap_ST_fsm_state4 = 10'd8;
parameter    ap_ST_fsm_state5 = 10'd16;
parameter    ap_ST_fsm_state6 = 10'd32;
parameter    ap_ST_fsm_state7 = 10'd64;
parameter    ap_ST_fsm_state8 = 10'd128;
parameter    ap_ST_fsm_state9 = 10'd256;
parameter    ap_ST_fsm_state10 = 10'd512;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [13:0] A_address0;
output   A_ce0;
input  [23:0] A_q0;
output  [13:0] C_address0;
output   C_ce0;
output   C_we0;
output  [23:0] C_d0;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[13:0] A_address0;
reg A_ce0;

(* fsm_encoding = "none" *) reg   [9:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [13:0] tmp_address0;
reg    tmp_ce0;
reg    tmp_we0;
wire   [23:0] tmp_q0;
wire   [13:0] tmp_s_fu_187_p3;
reg   [13:0] tmp_s_reg_494;
wire    ap_CS_fsm_state2;
wire   [23:0] denom_1_fu_265_p3;
reg   [23:0] denom_1_reg_507;
wire    ap_CS_fsm_state4;
wire   [5:0] trunc_ln31_fu_289_p1;
reg   [5:0] trunc_ln31_reg_515;
wire    ap_CS_fsm_state6;
wire  signed [17:0] scale_fu_377_p3;
reg  signed [17:0] scale_reg_521;
wire    ap_CS_fsm_state8;
reg   [0:0] tmp_12_reg_527;
wire   [23:0] scale_1_fu_463_p3;
reg   [23:0] scale_1_reg_533;
wire    ap_CS_fsm_state9;
wire    grp_top_kernel_Pipeline_VITIS_LOOP_15_2_fu_122_ap_start;
wire    grp_top_kernel_Pipeline_VITIS_LOOP_15_2_fu_122_ap_done;
wire    grp_top_kernel_Pipeline_VITIS_LOOP_15_2_fu_122_ap_idle;
wire    grp_top_kernel_Pipeline_VITIS_LOOP_15_2_fu_122_ap_ready;
wire   [13:0] grp_top_kernel_Pipeline_VITIS_LOOP_15_2_fu_122_A_address0;
wire    grp_top_kernel_Pipeline_VITIS_LOOP_15_2_fu_122_A_ce0;
wire   [23:0] grp_top_kernel_Pipeline_VITIS_LOOP_15_2_fu_122_p_out;
wire    grp_top_kernel_Pipeline_VITIS_LOOP_15_2_fu_122_p_out_ap_vld;
wire    grp_top_kernel_Pipeline_VITIS_LOOP_24_3_fu_130_ap_start;
wire    grp_top_kernel_Pipeline_VITIS_LOOP_24_3_fu_130_ap_done;
wire    grp_top_kernel_Pipeline_VITIS_LOOP_24_3_fu_130_ap_idle;
wire    grp_top_kernel_Pipeline_VITIS_LOOP_24_3_fu_130_ap_ready;
wire   [13:0] grp_top_kernel_Pipeline_VITIS_LOOP_24_3_fu_130_A_address0;
wire    grp_top_kernel_Pipeline_VITIS_LOOP_24_3_fu_130_A_ce0;
wire   [13:0] grp_top_kernel_Pipeline_VITIS_LOOP_24_3_fu_130_tmp_address0;
wire    grp_top_kernel_Pipeline_VITIS_LOOP_24_3_fu_130_tmp_ce0;
wire    grp_top_kernel_Pipeline_VITIS_LOOP_24_3_fu_130_tmp_we0;
wire   [23:0] grp_top_kernel_Pipeline_VITIS_LOOP_24_3_fu_130_tmp_d0;
wire    grp_top_kernel_Pipeline_VITIS_LOOP_35_5_fu_140_ap_start;
wire    grp_top_kernel_Pipeline_VITIS_LOOP_35_5_fu_140_ap_done;
wire    grp_top_kernel_Pipeline_VITIS_LOOP_35_5_fu_140_ap_idle;
wire    grp_top_kernel_Pipeline_VITIS_LOOP_35_5_fu_140_ap_ready;
wire   [23:0] grp_top_kernel_Pipeline_VITIS_LOOP_35_5_fu_140_p_out;
wire    grp_top_kernel_Pipeline_VITIS_LOOP_35_5_fu_140_p_out_ap_vld;
wire   [13:0] grp_top_kernel_Pipeline_VITIS_LOOP_35_5_fu_140_tmp_address0;
wire    grp_top_kernel_Pipeline_VITIS_LOOP_35_5_fu_140_tmp_ce0;
wire    grp_top_kernel_Pipeline_VITIS_LOOP_44_6_fu_148_ap_start;
wire    grp_top_kernel_Pipeline_VITIS_LOOP_44_6_fu_148_ap_done;
wire    grp_top_kernel_Pipeline_VITIS_LOOP_44_6_fu_148_ap_idle;
wire    grp_top_kernel_Pipeline_VITIS_LOOP_44_6_fu_148_ap_ready;
wire   [13:0] grp_top_kernel_Pipeline_VITIS_LOOP_44_6_fu_148_C_address0;
wire    grp_top_kernel_Pipeline_VITIS_LOOP_44_6_fu_148_C_ce0;
wire    grp_top_kernel_Pipeline_VITIS_LOOP_44_6_fu_148_C_we0;
wire   [23:0] grp_top_kernel_Pipeline_VITIS_LOOP_44_6_fu_148_C_d0;
wire   [13:0] grp_top_kernel_Pipeline_VITIS_LOOP_44_6_fu_148_tmp_address0;
wire    grp_top_kernel_Pipeline_VITIS_LOOP_44_6_fu_148_tmp_ce0;
reg    grp_top_kernel_Pipeline_VITIS_LOOP_15_2_fu_122_ap_start_reg;
wire   [0:0] icmp_ln11_fu_171_p2;
wire    ap_CS_fsm_state3;
reg    grp_top_kernel_Pipeline_VITIS_LOOP_24_3_fu_130_ap_start_reg;
wire    ap_CS_fsm_state5;
reg    grp_top_kernel_Pipeline_VITIS_LOOP_35_5_fu_140_ap_start_reg;
wire   [0:0] icmp_ln31_fu_277_p2;
wire    ap_CS_fsm_state7;
reg    grp_top_kernel_Pipeline_VITIS_LOOP_44_6_fu_148_ap_start_reg;
wire    ap_CS_fsm_state10;
reg   [8:0] i_fu_106;
wire   [8:0] add_ln11_fu_177_p2;
reg   [6:0] j_fu_118;
wire   [6:0] add_ln31_fu_283_p2;
wire   [41:0] mul_ln41_fu_158_p1;
wire   [7:0] trunc_ln11_fu_183_p1;
wire  signed [24:0] sext_ln21_fu_209_p1;
wire   [24:0] add_ln21_fu_213_p2;
wire   [0:0] tmp_1_fu_219_p3;
wire   [0:0] tmp_8_fu_231_p3;
wire   [0:0] xor_ln21_fu_239_p2;
wire   [0:0] and_ln21_fu_245_p2;
wire   [0:0] xor_ln21_1_fu_251_p2;
wire   [23:0] select_ln21_fu_257_p3;
wire   [23:0] denom_fu_227_p1;
wire  signed [39:0] shl_ln_fu_302_p3;
wire   [80:0] mul_ln41_fu_158_p2;
wire   [80:0] sub_ln41_fu_315_p2;
wire   [0:0] tmp_9_fu_321_p3;
wire   [16:0] tmp_19_cast_fu_329_p4;
wire   [16:0] tmp_20_cast_fu_349_p4;
wire   [16:0] select_ln41_1_fu_359_p3;
wire   [17:0] zext_ln41_fu_367_p1;
wire   [17:0] sub_ln41_1_fu_371_p2;
wire   [17:0] tmp_20_cast8_fu_339_p4;
wire  signed [39:0] sext_ln41_1_fu_393_p1;
wire   [0:0] tmp_11_fu_407_p3;
wire   [0:0] tmp_10_fu_396_p3;
wire   [0:0] or_ln41_fu_415_p2;
wire   [0:0] xor_ln41_fu_420_p2;
wire   [0:0] and_ln41_2_fu_432_p2;
wire   [0:0] xor_ln41_1_fu_437_p2;
wire   [0:0] and_ln41_fu_426_p2;
wire   [0:0] and_ln41_1_fu_443_p2;
wire   [0:0] or_ln41_1_fu_457_p2;
wire   [23:0] select_ln41_fu_449_p3;
wire  signed [23:0] sext_ln41_2_fu_404_p1;
reg   [9:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
reg    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
reg    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
reg    ap_ST_fsm_state10_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 10'd1;
#0 grp_top_kernel_Pipeline_VITIS_LOOP_15_2_fu_122_ap_start_reg = 1'b0;
#0 grp_top_kernel_Pipeline_VITIS_LOOP_24_3_fu_130_ap_start_reg = 1'b0;
#0 grp_top_kernel_Pipeline_VITIS_LOOP_35_5_fu_140_ap_start_reg = 1'b0;
#0 grp_top_kernel_Pipeline_VITIS_LOOP_44_6_fu_148_ap_start_reg = 1'b0;
#0 i_fu_106 = 9'd0;
#0 j_fu_118 = 7'd0;
end

top_kernel_tmp_RAM_AUTO_1R1W #(
    .DataWidth( 24 ),
    .AddressRange( 16384 ),
    .AddressWidth( 14 ))
tmp_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(tmp_address0),
    .ce0(tmp_ce0),
    .we0(tmp_we0),
    .d0(grp_top_kernel_Pipeline_VITIS_LOOP_24_3_fu_130_tmp_d0),
    .q0(tmp_q0)
);

top_kernel_top_kernel_Pipeline_VITIS_LOOP_15_2 grp_top_kernel_Pipeline_VITIS_LOOP_15_2_fu_122(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_top_kernel_Pipeline_VITIS_LOOP_15_2_fu_122_ap_start),
    .ap_done(grp_top_kernel_Pipeline_VITIS_LOOP_15_2_fu_122_ap_done),
    .ap_idle(grp_top_kernel_Pipeline_VITIS_LOOP_15_2_fu_122_ap_idle),
    .ap_ready(grp_top_kernel_Pipeline_VITIS_LOOP_15_2_fu_122_ap_ready),
    .zext_ln26(tmp_s_reg_494),
    .A_address0(grp_top_kernel_Pipeline_VITIS_LOOP_15_2_fu_122_A_address0),
    .A_ce0(grp_top_kernel_Pipeline_VITIS_LOOP_15_2_fu_122_A_ce0),
    .A_q0(A_q0),
    .p_out(grp_top_kernel_Pipeline_VITIS_LOOP_15_2_fu_122_p_out),
    .p_out_ap_vld(grp_top_kernel_Pipeline_VITIS_LOOP_15_2_fu_122_p_out_ap_vld)
);

top_kernel_top_kernel_Pipeline_VITIS_LOOP_24_3 grp_top_kernel_Pipeline_VITIS_LOOP_24_3_fu_130(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_top_kernel_Pipeline_VITIS_LOOP_24_3_fu_130_ap_start),
    .ap_done(grp_top_kernel_Pipeline_VITIS_LOOP_24_3_fu_130_ap_done),
    .ap_idle(grp_top_kernel_Pipeline_VITIS_LOOP_24_3_fu_130_ap_idle),
    .ap_ready(grp_top_kernel_Pipeline_VITIS_LOOP_24_3_fu_130_ap_ready),
    .zext_ln26(tmp_s_reg_494),
    .A_address0(grp_top_kernel_Pipeline_VITIS_LOOP_24_3_fu_130_A_address0),
    .A_ce0(grp_top_kernel_Pipeline_VITIS_LOOP_24_3_fu_130_A_ce0),
    .A_q0(A_q0),
    .conv_i362(denom_1_reg_507),
    .tmp_address0(grp_top_kernel_Pipeline_VITIS_LOOP_24_3_fu_130_tmp_address0),
    .tmp_ce0(grp_top_kernel_Pipeline_VITIS_LOOP_24_3_fu_130_tmp_ce0),
    .tmp_we0(grp_top_kernel_Pipeline_VITIS_LOOP_24_3_fu_130_tmp_we0),
    .tmp_d0(grp_top_kernel_Pipeline_VITIS_LOOP_24_3_fu_130_tmp_d0)
);

top_kernel_top_kernel_Pipeline_VITIS_LOOP_35_5 grp_top_kernel_Pipeline_VITIS_LOOP_35_5_fu_140(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_top_kernel_Pipeline_VITIS_LOOP_35_5_fu_140_ap_start),
    .ap_done(grp_top_kernel_Pipeline_VITIS_LOOP_35_5_fu_140_ap_done),
    .ap_idle(grp_top_kernel_Pipeline_VITIS_LOOP_35_5_fu_140_ap_idle),
    .ap_ready(grp_top_kernel_Pipeline_VITIS_LOOP_35_5_fu_140_ap_ready),
    .zext_ln31(trunc_ln31_reg_515),
    .p_out(grp_top_kernel_Pipeline_VITIS_LOOP_35_5_fu_140_p_out),
    .p_out_ap_vld(grp_top_kernel_Pipeline_VITIS_LOOP_35_5_fu_140_p_out_ap_vld),
    .tmp_address0(grp_top_kernel_Pipeline_VITIS_LOOP_35_5_fu_140_tmp_address0),
    .tmp_ce0(grp_top_kernel_Pipeline_VITIS_LOOP_35_5_fu_140_tmp_ce0),
    .tmp_q0(tmp_q0)
);

top_kernel_top_kernel_Pipeline_VITIS_LOOP_44_6 grp_top_kernel_Pipeline_VITIS_LOOP_44_6_fu_148(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_top_kernel_Pipeline_VITIS_LOOP_44_6_fu_148_ap_start),
    .ap_done(grp_top_kernel_Pipeline_VITIS_LOOP_44_6_fu_148_ap_done),
    .ap_idle(grp_top_kernel_Pipeline_VITIS_LOOP_44_6_fu_148_ap_idle),
    .ap_ready(grp_top_kernel_Pipeline_VITIS_LOOP_44_6_fu_148_ap_ready),
    .zext_ln31(trunc_ln31_reg_515),
    .C_address0(grp_top_kernel_Pipeline_VITIS_LOOP_44_6_fu_148_C_address0),
    .C_ce0(grp_top_kernel_Pipeline_VITIS_LOOP_44_6_fu_148_C_ce0),
    .C_we0(grp_top_kernel_Pipeline_VITIS_LOOP_44_6_fu_148_C_we0),
    .C_d0(grp_top_kernel_Pipeline_VITIS_LOOP_44_6_fu_148_C_d0),
    .conv7_i(scale_1_reg_533),
    .tmp_address0(grp_top_kernel_Pipeline_VITIS_LOOP_44_6_fu_148_tmp_address0),
    .tmp_ce0(grp_top_kernel_Pipeline_VITIS_LOOP_44_6_fu_148_tmp_ce0),
    .tmp_q0(tmp_q0)
);

top_kernel_mul_40s_42ns_81_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 40 ),
    .din1_WIDTH( 42 ),
    .dout_WIDTH( 81 ))
mul_40s_42ns_81_1_1_U19(
    .din0(shl_ln_fu_302_p3),
    .din1(mul_ln41_fu_158_p1),
    .dout(mul_ln41_fu_158_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_top_kernel_Pipeline_VITIS_LOOP_15_2_fu_122_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln11_fu_171_p2 == 1'd0))) begin
            grp_top_kernel_Pipeline_VITIS_LOOP_15_2_fu_122_ap_start_reg <= 1'b1;
        end else if ((grp_top_kernel_Pipeline_VITIS_LOOP_15_2_fu_122_ap_ready == 1'b1)) begin
            grp_top_kernel_Pipeline_VITIS_LOOP_15_2_fu_122_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_top_kernel_Pipeline_VITIS_LOOP_24_3_fu_130_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state4)) begin
            grp_top_kernel_Pipeline_VITIS_LOOP_24_3_fu_130_ap_start_reg <= 1'b1;
        end else if ((grp_top_kernel_Pipeline_VITIS_LOOP_24_3_fu_130_ap_ready == 1'b1)) begin
            grp_top_kernel_Pipeline_VITIS_LOOP_24_3_fu_130_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_top_kernel_Pipeline_VITIS_LOOP_35_5_fu_140_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state6) & (icmp_ln31_fu_277_p2 == 1'd0))) begin
            grp_top_kernel_Pipeline_VITIS_LOOP_35_5_fu_140_ap_start_reg <= 1'b1;
        end else if ((grp_top_kernel_Pipeline_VITIS_LOOP_35_5_fu_140_ap_ready == 1'b1)) begin
            grp_top_kernel_Pipeline_VITIS_LOOP_35_5_fu_140_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_top_kernel_Pipeline_VITIS_LOOP_44_6_fu_148_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state9)) begin
            grp_top_kernel_Pipeline_VITIS_LOOP_44_6_fu_148_ap_start_reg <= 1'b1;
        end else if ((grp_top_kernel_Pipeline_VITIS_LOOP_44_6_fu_148_ap_ready == 1'b1)) begin
            grp_top_kernel_Pipeline_VITIS_LOOP_44_6_fu_148_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        i_fu_106 <= 9'd0;
    end else if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln11_fu_171_p2 == 1'd0))) begin
        i_fu_106 <= add_ln11_fu_177_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln11_fu_171_p2 == 1'd1))) begin
        j_fu_118 <= 7'd0;
    end else if (((1'b1 == ap_CS_fsm_state6) & (icmp_ln31_fu_277_p2 == 1'd0))) begin
        j_fu_118 <= add_ln31_fu_283_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        denom_1_reg_507 <= denom_1_fu_265_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        scale_1_reg_533 <= scale_1_fu_463_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        scale_reg_521 <= scale_fu_377_p3;
        tmp_12_reg_527 <= scale_fu_377_p3[32'd17];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        tmp_s_reg_494[13 : 6] <= tmp_s_fu_187_p3[13 : 6];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        trunc_ln31_reg_515 <= trunc_ln31_fu_289_p1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        A_address0 = grp_top_kernel_Pipeline_VITIS_LOOP_24_3_fu_130_A_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        A_address0 = grp_top_kernel_Pipeline_VITIS_LOOP_15_2_fu_122_A_address0;
    end else begin
        A_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        A_ce0 = grp_top_kernel_Pipeline_VITIS_LOOP_24_3_fu_130_A_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        A_ce0 = grp_top_kernel_Pipeline_VITIS_LOOP_15_2_fu_122_A_ce0;
    end else begin
        A_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((grp_top_kernel_Pipeline_VITIS_LOOP_44_6_fu_148_ap_done == 1'b0)) begin
        ap_ST_fsm_state10_blk = 1'b1;
    end else begin
        ap_ST_fsm_state10_blk = 1'b0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_top_kernel_Pipeline_VITIS_LOOP_15_2_fu_122_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

assign ap_ST_fsm_state4_blk = 1'b0;

always @ (*) begin
    if ((grp_top_kernel_Pipeline_VITIS_LOOP_24_3_fu_130_ap_done == 1'b0)) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

assign ap_ST_fsm_state6_blk = 1'b0;

always @ (*) begin
    if ((grp_top_kernel_Pipeline_VITIS_LOOP_35_5_fu_140_ap_done == 1'b0)) begin
        ap_ST_fsm_state7_blk = 1'b1;
    end else begin
        ap_ST_fsm_state7_blk = 1'b0;
    end
end

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) & (icmp_ln31_fu_277_p2 == 1'd1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) & (icmp_ln31_fu_277_p2 == 1'd1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        tmp_address0 = grp_top_kernel_Pipeline_VITIS_LOOP_44_6_fu_148_tmp_address0;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        tmp_address0 = grp_top_kernel_Pipeline_VITIS_LOOP_35_5_fu_140_tmp_address0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        tmp_address0 = grp_top_kernel_Pipeline_VITIS_LOOP_24_3_fu_130_tmp_address0;
    end else begin
        tmp_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        tmp_ce0 = grp_top_kernel_Pipeline_VITIS_LOOP_44_6_fu_148_tmp_ce0;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        tmp_ce0 = grp_top_kernel_Pipeline_VITIS_LOOP_35_5_fu_140_tmp_ce0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        tmp_ce0 = grp_top_kernel_Pipeline_VITIS_LOOP_24_3_fu_130_tmp_ce0;
    end else begin
        tmp_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        tmp_we0 = grp_top_kernel_Pipeline_VITIS_LOOP_24_3_fu_130_tmp_we0;
    end else begin
        tmp_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln11_fu_171_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((grp_top_kernel_Pipeline_VITIS_LOOP_15_2_fu_122_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            if (((1'b1 == ap_CS_fsm_state5) & (grp_top_kernel_Pipeline_VITIS_LOOP_24_3_fu_130_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state6 : begin
            if (((1'b1 == ap_CS_fsm_state6) & (icmp_ln31_fu_277_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_state7 : begin
            if (((1'b1 == ap_CS_fsm_state7) & (grp_top_kernel_Pipeline_VITIS_LOOP_35_5_fu_140_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            if (((1'b1 == ap_CS_fsm_state10) & (grp_top_kernel_Pipeline_VITIS_LOOP_44_6_fu_148_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign C_address0 = grp_top_kernel_Pipeline_VITIS_LOOP_44_6_fu_148_C_address0;

assign C_ce0 = grp_top_kernel_Pipeline_VITIS_LOOP_44_6_fu_148_C_ce0;

assign C_d0 = grp_top_kernel_Pipeline_VITIS_LOOP_44_6_fu_148_C_d0;

assign C_we0 = grp_top_kernel_Pipeline_VITIS_LOOP_44_6_fu_148_C_we0;

assign add_ln11_fu_177_p2 = (i_fu_106 + 9'd1);

assign add_ln21_fu_213_p2 = ($signed(sext_ln21_fu_209_p1) + $signed(25'd65536));

assign add_ln31_fu_283_p2 = (j_fu_118 + 7'd1);

assign and_ln21_fu_245_p2 = (xor_ln21_fu_239_p2 & tmp_8_fu_231_p3);

assign and_ln41_1_fu_443_p2 = (xor_ln41_1_fu_437_p2 & tmp_10_fu_396_p3);

assign and_ln41_2_fu_432_p2 = (tmp_12_reg_527 & tmp_11_fu_407_p3);

assign and_ln41_fu_426_p2 = (xor_ln41_fu_420_p2 & or_ln41_fu_415_p2);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign denom_1_fu_265_p3 = ((xor_ln21_1_fu_251_p2[0:0] == 1'b1) ? select_ln21_fu_257_p3 : denom_fu_227_p1);

assign denom_fu_227_p1 = add_ln21_fu_213_p2[23:0];

assign grp_top_kernel_Pipeline_VITIS_LOOP_15_2_fu_122_ap_start = grp_top_kernel_Pipeline_VITIS_LOOP_15_2_fu_122_ap_start_reg;

assign grp_top_kernel_Pipeline_VITIS_LOOP_24_3_fu_130_ap_start = grp_top_kernel_Pipeline_VITIS_LOOP_24_3_fu_130_ap_start_reg;

assign grp_top_kernel_Pipeline_VITIS_LOOP_35_5_fu_140_ap_start = grp_top_kernel_Pipeline_VITIS_LOOP_35_5_fu_140_ap_start_reg;

assign grp_top_kernel_Pipeline_VITIS_LOOP_44_6_fu_148_ap_start = grp_top_kernel_Pipeline_VITIS_LOOP_44_6_fu_148_ap_start_reg;

assign icmp_ln11_fu_171_p2 = ((i_fu_106 == 9'd256) ? 1'b1 : 1'b0);

assign icmp_ln31_fu_277_p2 = ((j_fu_118 == 7'd64) ? 1'b1 : 1'b0);

assign mul_ln41_fu_158_p1 = 81'd1099511758849;

assign or_ln41_1_fu_457_p2 = (and_ln41_fu_426_p2 | and_ln41_1_fu_443_p2);

assign or_ln41_fu_415_p2 = (tmp_12_reg_527 | tmp_11_fu_407_p3);

assign scale_1_fu_463_p3 = ((or_ln41_1_fu_457_p2[0:0] == 1'b1) ? select_ln41_fu_449_p3 : sext_ln41_2_fu_404_p1);

assign scale_fu_377_p3 = ((tmp_9_fu_321_p3[0:0] == 1'b1) ? sub_ln41_1_fu_371_p2 : tmp_20_cast8_fu_339_p4);

assign select_ln21_fu_257_p3 = ((and_ln21_fu_245_p2[0:0] == 1'b1) ? 24'd8388607 : 24'd8388608);

assign select_ln41_1_fu_359_p3 = ((tmp_9_fu_321_p3[0:0] == 1'b1) ? tmp_19_cast_fu_329_p4 : tmp_20_cast_fu_349_p4);

assign select_ln41_fu_449_p3 = ((and_ln41_fu_426_p2[0:0] == 1'b1) ? 24'd8388607 : 24'd8388608);

assign sext_ln21_fu_209_p1 = $signed(grp_top_kernel_Pipeline_VITIS_LOOP_15_2_fu_122_p_out);

assign sext_ln41_1_fu_393_p1 = scale_reg_521;

assign sext_ln41_2_fu_404_p1 = scale_reg_521;

assign shl_ln_fu_302_p3 = {{grp_top_kernel_Pipeline_VITIS_LOOP_35_5_fu_140_p_out}, {16'd0}};

assign sub_ln41_1_fu_371_p2 = (18'd0 - zext_ln41_fu_367_p1);

assign sub_ln41_fu_315_p2 = (81'd0 - mul_ln41_fu_158_p2);

assign tmp_10_fu_396_p3 = sext_ln41_1_fu_393_p1[32'd39];

assign tmp_11_fu_407_p3 = sext_ln41_1_fu_393_p1[32'd23];

assign tmp_19_cast_fu_329_p4 = {{sub_ln41_fu_315_p2[79:63]}};

assign tmp_1_fu_219_p3 = add_ln21_fu_213_p2[32'd24];

assign tmp_20_cast8_fu_339_p4 = {{mul_ln41_fu_158_p2[80:63]}};

assign tmp_20_cast_fu_349_p4 = {{mul_ln41_fu_158_p2[79:63]}};

assign tmp_8_fu_231_p3 = add_ln21_fu_213_p2[32'd23];

assign tmp_9_fu_321_p3 = grp_top_kernel_Pipeline_VITIS_LOOP_35_5_fu_140_p_out[32'd23];

assign tmp_s_fu_187_p3 = {{trunc_ln11_fu_183_p1}, {6'd0}};

assign trunc_ln11_fu_183_p1 = i_fu_106[7:0];

assign trunc_ln31_fu_289_p1 = j_fu_118[5:0];

assign xor_ln21_1_fu_251_p2 = (tmp_8_fu_231_p3 ^ tmp_1_fu_219_p3);

assign xor_ln21_fu_239_p2 = (tmp_1_fu_219_p3 ^ 1'd1);

assign xor_ln41_1_fu_437_p2 = (1'd1 ^ and_ln41_2_fu_432_p2);

assign xor_ln41_fu_420_p2 = (tmp_10_fu_396_p3 ^ 1'd1);

assign zext_ln41_fu_367_p1 = select_ln41_1_fu_359_p3;

always @ (posedge ap_clk) begin
    tmp_s_reg_494[5:0] <= 6'b000000;
end

endmodule //top_kernel
