// ==============================================================
// Generated by Vitis HLS v2025.1.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module top_kernel_top_kernel_Pipeline_VITIS_LOOP_44_6 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        zext_ln31,
        C_address0,
        C_ce0,
        C_we0,
        C_d0,
        conv7_i,
        tmp_address0,
        tmp_ce0,
        tmp_q0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [5:0] zext_ln31;
output  [13:0] C_address0;
output   C_ce0;
output   C_we0;
output  [23:0] C_d0;
input  [23:0] conv7_i;
output  [13:0] tmp_address0;
output   tmp_ce0;
input  [23:0] tmp_q0;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln44_fu_138_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire  signed [47:0] conv7_i_cast_fu_126_p1;
reg  signed [47:0] conv7_i_cast_reg_394;
wire    ap_block_pp0_stage0_11001;
wire   [63:0] zext_ln46_1_fu_162_p1;
reg   [63:0] zext_ln46_1_reg_403;
reg   [63:0] zext_ln46_1_reg_403_pp0_iter1_reg;
wire   [23:0] select_ln46_3_fu_379_p3;
reg   [23:0] select_ln46_3_reg_413;
wire    ap_block_pp0_stage0;
reg   [8:0] i_fu_80;
wire   [8:0] add_ln44_fu_144_p2;
wire    ap_loop_init;
reg   [8:0] ap_sig_allocacmp_i_1;
reg    tmp_ce0_local;
reg    C_we0_local;
reg    C_ce0_local;
wire  signed [23:0] mul_ln46_fu_122_p1;
wire   [7:0] trunc_ln44_fu_150_p1;
wire   [13:0] add_ln46_1_fu_154_p3;
wire   [47:0] mul_ln46_fu_122_p2;
wire   [0:0] tmp_1_fu_195_p3;
wire   [23:0] trunc_ln2_fu_185_p4;
wire   [23:0] zext_ln46_fu_211_p1;
wire   [23:0] add_ln46_fu_215_p2;
wire   [0:0] tmp_3_fu_221_p3;
wire   [0:0] tmp_2_fu_203_p3;
wire   [0:0] xor_ln46_fu_229_p2;
wire   [6:0] tmp_s_fu_249_p3;
wire   [7:0] tmp_5_fu_263_p3;
wire   [0:0] and_ln46_fu_235_p2;
wire   [0:0] icmp_ln46_1_fu_271_p2;
wire   [0:0] icmp_ln46_2_fu_277_p2;
wire   [0:0] tmp_4_fu_241_p3;
wire   [0:0] icmp_ln46_fu_257_p2;
wire   [0:0] xor_ln46_1_fu_291_p2;
wire   [0:0] and_ln46_1_fu_297_p2;
wire   [0:0] select_ln46_fu_283_p3;
wire   [0:0] xor_ln46_2_fu_317_p2;
wire   [0:0] tmp_1_1_fu_177_p3;
wire   [0:0] or_ln46_fu_323_p2;
wire   [0:0] xor_ln46_3_fu_329_p2;
wire   [0:0] select_ln46_1_fu_303_p3;
wire   [0:0] and_ln46_2_fu_311_p2;
wire   [0:0] and_ln46_4_fu_341_p2;
wire   [0:0] or_ln46_2_fu_347_p2;
wire   [0:0] xor_ln46_4_fu_353_p2;
wire   [0:0] and_ln46_3_fu_335_p2;
wire   [0:0] and_ln46_5_fu_359_p2;
wire   [0:0] or_ln46_1_fu_373_p2;
wire   [23:0] select_ln46_2_fu_365_p3;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 i_fu_80 = 9'd0;
#0 ap_done_reg = 1'b0;
end

top_kernel_mul_24s_24s_48_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 24 ),
    .din1_WIDTH( 24 ),
    .dout_WIDTH( 48 ))
mul_24s_24s_48_1_1_U13(
    .din0(tmp_q0),
    .din1(mul_ln46_fu_122_p1),
    .dout(mul_ln46_fu_122_p2)
);

top_kernel_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln44_fu_138_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_fu_80 <= add_ln44_fu_144_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_80 <= 9'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        conv7_i_cast_reg_394 <= conv7_i_cast_fu_126_p1;
        select_ln46_3_reg_413 <= select_ln46_3_fu_379_p3;
        zext_ln46_1_reg_403[13 : 0] <= zext_ln46_1_fu_162_p1[13 : 0];
        zext_ln46_1_reg_403_pp0_iter1_reg[13 : 0] <= zext_ln46_1_reg_403[13 : 0];
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        C_ce0_local = 1'b1;
    end else begin
        C_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        C_we0_local = 1'b1;
    end else begin
        C_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln44_fu_138_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_i_1 = 9'd0;
    end else begin
        ap_sig_allocacmp_i_1 = i_fu_80;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        tmp_ce0_local = 1'b1;
    end else begin
        tmp_ce0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign C_address0 = zext_ln46_1_reg_403_pp0_iter1_reg;

assign C_ce0 = C_ce0_local;

assign C_d0 = select_ln46_3_reg_413;

assign C_we0 = C_we0_local;

assign add_ln44_fu_144_p2 = (ap_sig_allocacmp_i_1 + 9'd1);

assign add_ln46_1_fu_154_p3 = {{trunc_ln44_fu_150_p1}, {zext_ln31}};

assign add_ln46_fu_215_p2 = (trunc_ln2_fu_185_p4 + zext_ln46_fu_211_p1);

assign and_ln46_1_fu_297_p2 = (xor_ln46_1_fu_291_p2 & icmp_ln46_fu_257_p2);

assign and_ln46_2_fu_311_p2 = (icmp_ln46_1_fu_271_p2 & and_ln46_fu_235_p2);

assign and_ln46_3_fu_335_p2 = (xor_ln46_3_fu_329_p2 & or_ln46_fu_323_p2);

assign and_ln46_4_fu_341_p2 = (tmp_3_fu_221_p3 & select_ln46_1_fu_303_p3);

assign and_ln46_5_fu_359_p2 = (xor_ln46_4_fu_353_p2 & tmp_1_1_fu_177_p3);

assign and_ln46_fu_235_p2 = (xor_ln46_fu_229_p2 & tmp_2_fu_203_p3);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign conv7_i_cast_fu_126_p1 = $signed(conv7_i);

assign icmp_ln44_fu_138_p2 = ((ap_sig_allocacmp_i_1 == 9'd256) ? 1'b1 : 1'b0);

assign icmp_ln46_1_fu_271_p2 = ((tmp_5_fu_263_p3 == 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln46_2_fu_277_p2 = ((tmp_5_fu_263_p3 == 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_fu_257_p2 = ((tmp_s_fu_249_p3 == 7'd127) ? 1'b1 : 1'b0);

assign mul_ln46_fu_122_p1 = conv7_i_cast_reg_394;

assign or_ln46_1_fu_373_p2 = (and_ln46_5_fu_359_p2 | and_ln46_3_fu_335_p2);

assign or_ln46_2_fu_347_p2 = (and_ln46_4_fu_341_p2 | and_ln46_2_fu_311_p2);

assign or_ln46_fu_323_p2 = (xor_ln46_2_fu_317_p2 | tmp_3_fu_221_p3);

assign select_ln46_1_fu_303_p3 = ((and_ln46_fu_235_p2[0:0] == 1'b1) ? and_ln46_1_fu_297_p2 : icmp_ln46_1_fu_271_p2);

assign select_ln46_2_fu_365_p3 = ((and_ln46_3_fu_335_p2[0:0] == 1'b1) ? 24'd8388607 : 24'd8388608);

assign select_ln46_3_fu_379_p3 = ((or_ln46_1_fu_373_p2[0:0] == 1'b1) ? select_ln46_2_fu_365_p3 : add_ln46_fu_215_p2);

assign select_ln46_fu_283_p3 = ((and_ln46_fu_235_p2[0:0] == 1'b1) ? icmp_ln46_1_fu_271_p2 : icmp_ln46_2_fu_277_p2);

assign tmp_1_1_fu_177_p3 = mul_ln46_fu_122_p2[32'd47];

assign tmp_1_fu_195_p3 = mul_ln46_fu_122_p2[32'd15];

assign tmp_2_fu_203_p3 = mul_ln46_fu_122_p2[32'd39];

assign tmp_3_fu_221_p3 = add_ln46_fu_215_p2[32'd23];

assign tmp_4_fu_241_p3 = mul_ln46_fu_122_p2[32'd40];

assign tmp_5_fu_263_p3 = {{mul_ln46_fu_122_p2[47:40]}};

assign tmp_address0 = zext_ln46_1_fu_162_p1;

assign tmp_ce0 = tmp_ce0_local;

assign tmp_s_fu_249_p3 = {{mul_ln46_fu_122_p2[47:41]}};

assign trunc_ln2_fu_185_p4 = {{mul_ln46_fu_122_p2[39:16]}};

assign trunc_ln44_fu_150_p1 = ap_sig_allocacmp_i_1[7:0];

assign xor_ln46_1_fu_291_p2 = (tmp_4_fu_241_p3 ^ 1'd1);

assign xor_ln46_2_fu_317_p2 = (select_ln46_fu_283_p3 ^ 1'd1);

assign xor_ln46_3_fu_329_p2 = (tmp_1_1_fu_177_p3 ^ 1'd1);

assign xor_ln46_4_fu_353_p2 = (or_ln46_2_fu_347_p2 ^ 1'd1);

assign xor_ln46_fu_229_p2 = (tmp_3_fu_221_p3 ^ 1'd1);

assign zext_ln46_1_fu_162_p1 = add_ln46_1_fu_154_p3;

assign zext_ln46_fu_211_p1 = tmp_1_fu_195_p3;

always @ (posedge ap_clk) begin
    zext_ln46_1_reg_403[63:14] <= 50'b00000000000000000000000000000000000000000000000000;
    zext_ln46_1_reg_403_pp0_iter1_reg[63:14] <= 50'b00000000000000000000000000000000000000000000000000;
end

endmodule //top_kernel_top_kernel_Pipeline_VITIS_LOOP_44_6
