-- ==============================================================
-- Generated by Vitis HLS v2025.1.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity top_kernel is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    A_address0 : OUT STD_LOGIC_VECTOR (13 downto 0);
    A_ce0 : OUT STD_LOGIC;
    A_q0 : IN STD_LOGIC_VECTOR (23 downto 0);
    C_address0 : OUT STD_LOGIC_VECTOR (13 downto 0);
    C_ce0 : OUT STD_LOGIC;
    C_we0 : OUT STD_LOGIC;
    C_d0 : OUT STD_LOGIC_VECTOR (23 downto 0) );
end;


architecture behav of top_kernel is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "top_kernel_top_kernel,hls_ip_2025_1_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xczu3eg-sbva484-1-e,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.276500,HLS_SYN_LAT=852994,HLS_SYN_TPT=none,HLS_SYN_MEM=22,HLS_SYN_DSP=0,HLS_SYN_FF=864,HLS_SYN_LUT=1775,HLS_VERSION=2025_1_1}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (55 downto 0) := "00000000000000000000000000000000000000000000000000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (55 downto 0) := "00000000000000000000000000000000000000000000000000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (55 downto 0) := "00000000000000000000000000000000000000000000000000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (55 downto 0) := "00000000000000000000000000000000000000000000000000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (55 downto 0) := "00000000000000000000000000000000000000000000000000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (55 downto 0) := "00000000000000000000000000000000000000000000000000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (55 downto 0) := "00000000000000000000000000000000000000000000000001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (55 downto 0) := "00000000000000000000000000000000000000000000000010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (55 downto 0) := "00000000000000000000000000000000000000000000000100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (55 downto 0) := "00000000000000000000000000000000000000000000001000000000";
    constant ap_ST_fsm_state11 : STD_LOGIC_VECTOR (55 downto 0) := "00000000000000000000000000000000000000000000010000000000";
    constant ap_ST_fsm_state12 : STD_LOGIC_VECTOR (55 downto 0) := "00000000000000000000000000000000000000000000100000000000";
    constant ap_ST_fsm_state13 : STD_LOGIC_VECTOR (55 downto 0) := "00000000000000000000000000000000000000000001000000000000";
    constant ap_ST_fsm_state14 : STD_LOGIC_VECTOR (55 downto 0) := "00000000000000000000000000000000000000000010000000000000";
    constant ap_ST_fsm_state15 : STD_LOGIC_VECTOR (55 downto 0) := "00000000000000000000000000000000000000000100000000000000";
    constant ap_ST_fsm_state16 : STD_LOGIC_VECTOR (55 downto 0) := "00000000000000000000000000000000000000001000000000000000";
    constant ap_ST_fsm_state17 : STD_LOGIC_VECTOR (55 downto 0) := "00000000000000000000000000000000000000010000000000000000";
    constant ap_ST_fsm_state18 : STD_LOGIC_VECTOR (55 downto 0) := "00000000000000000000000000000000000000100000000000000000";
    constant ap_ST_fsm_state19 : STD_LOGIC_VECTOR (55 downto 0) := "00000000000000000000000000000000000001000000000000000000";
    constant ap_ST_fsm_state20 : STD_LOGIC_VECTOR (55 downto 0) := "00000000000000000000000000000000000010000000000000000000";
    constant ap_ST_fsm_state21 : STD_LOGIC_VECTOR (55 downto 0) := "00000000000000000000000000000000000100000000000000000000";
    constant ap_ST_fsm_state22 : STD_LOGIC_VECTOR (55 downto 0) := "00000000000000000000000000000000001000000000000000000000";
    constant ap_ST_fsm_state23 : STD_LOGIC_VECTOR (55 downto 0) := "00000000000000000000000000000000010000000000000000000000";
    constant ap_ST_fsm_state24 : STD_LOGIC_VECTOR (55 downto 0) := "00000000000000000000000000000000100000000000000000000000";
    constant ap_ST_fsm_state25 : STD_LOGIC_VECTOR (55 downto 0) := "00000000000000000000000000000001000000000000000000000000";
    constant ap_ST_fsm_state26 : STD_LOGIC_VECTOR (55 downto 0) := "00000000000000000000000000000010000000000000000000000000";
    constant ap_ST_fsm_state27 : STD_LOGIC_VECTOR (55 downto 0) := "00000000000000000000000000000100000000000000000000000000";
    constant ap_ST_fsm_state28 : STD_LOGIC_VECTOR (55 downto 0) := "00000000000000000000000000001000000000000000000000000000";
    constant ap_ST_fsm_state29 : STD_LOGIC_VECTOR (55 downto 0) := "00000000000000000000000000010000000000000000000000000000";
    constant ap_ST_fsm_state30 : STD_LOGIC_VECTOR (55 downto 0) := "00000000000000000000000000100000000000000000000000000000";
    constant ap_ST_fsm_state31 : STD_LOGIC_VECTOR (55 downto 0) := "00000000000000000000000001000000000000000000000000000000";
    constant ap_ST_fsm_state32 : STD_LOGIC_VECTOR (55 downto 0) := "00000000000000000000000010000000000000000000000000000000";
    constant ap_ST_fsm_state33 : STD_LOGIC_VECTOR (55 downto 0) := "00000000000000000000000100000000000000000000000000000000";
    constant ap_ST_fsm_state34 : STD_LOGIC_VECTOR (55 downto 0) := "00000000000000000000001000000000000000000000000000000000";
    constant ap_ST_fsm_state35 : STD_LOGIC_VECTOR (55 downto 0) := "00000000000000000000010000000000000000000000000000000000";
    constant ap_ST_fsm_state36 : STD_LOGIC_VECTOR (55 downto 0) := "00000000000000000000100000000000000000000000000000000000";
    constant ap_ST_fsm_state37 : STD_LOGIC_VECTOR (55 downto 0) := "00000000000000000001000000000000000000000000000000000000";
    constant ap_ST_fsm_state38 : STD_LOGIC_VECTOR (55 downto 0) := "00000000000000000010000000000000000000000000000000000000";
    constant ap_ST_fsm_state39 : STD_LOGIC_VECTOR (55 downto 0) := "00000000000000000100000000000000000000000000000000000000";
    constant ap_ST_fsm_state40 : STD_LOGIC_VECTOR (55 downto 0) := "00000000000000001000000000000000000000000000000000000000";
    constant ap_ST_fsm_state41 : STD_LOGIC_VECTOR (55 downto 0) := "00000000000000010000000000000000000000000000000000000000";
    constant ap_ST_fsm_state42 : STD_LOGIC_VECTOR (55 downto 0) := "00000000000000100000000000000000000000000000000000000000";
    constant ap_ST_fsm_state43 : STD_LOGIC_VECTOR (55 downto 0) := "00000000000001000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state44 : STD_LOGIC_VECTOR (55 downto 0) := "00000000000010000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state45 : STD_LOGIC_VECTOR (55 downto 0) := "00000000000100000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state46 : STD_LOGIC_VECTOR (55 downto 0) := "00000000001000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state47 : STD_LOGIC_VECTOR (55 downto 0) := "00000000010000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state48 : STD_LOGIC_VECTOR (55 downto 0) := "00000000100000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state49 : STD_LOGIC_VECTOR (55 downto 0) := "00000001000000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state50 : STD_LOGIC_VECTOR (55 downto 0) := "00000010000000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state51 : STD_LOGIC_VECTOR (55 downto 0) := "00000100000000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state52 : STD_LOGIC_VECTOR (55 downto 0) := "00001000000000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state53 : STD_LOGIC_VECTOR (55 downto 0) := "00010000000000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state54 : STD_LOGIC_VECTOR (55 downto 0) := "00100000000000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state55 : STD_LOGIC_VECTOR (55 downto 0) := "01000000000000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state56 : STD_LOGIC_VECTOR (55 downto 0) := "10000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_31 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110001";
    constant ap_const_lv32_32 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110010";
    constant ap_const_lv32_33 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110011";
    constant ap_const_lv32_34 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110100";
    constant ap_const_lv32_35 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110101";
    constant ap_const_lv32_36 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110110";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv24_0 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_30 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110000";
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    constant ap_const_lv32_37 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110111";
    constant ap_const_lv81_10000020001 : STD_LOGIC_VECTOR (80 downto 0) := "000000000000000000000000000000000000000010000000000000000000000100000000000000001";
    constant ap_const_lv9_100 : STD_LOGIC_VECTOR (8 downto 0) := "100000000";
    constant ap_const_lv9_1 : STD_LOGIC_VECTOR (8 downto 0) := "000000001";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv7_40 : STD_LOGIC_VECTOR (6 downto 0) := "1000000";
    constant ap_const_lv7_1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    constant ap_const_lv25_10000 : STD_LOGIC_VECTOR (24 downto 0) := "0000000010000000000000000";
    constant ap_const_lv32_18 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011000";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv24_7FFFFF : STD_LOGIC_VECTOR (23 downto 0) := "011111111111111111111111";
    constant ap_const_lv24_800000 : STD_LOGIC_VECTOR (23 downto 0) := "100000000000000000000000";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv32_27 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100111";
    constant ap_const_lv16_FFFF : STD_LOGIC_VECTOR (15 downto 0) := "1111111111111111";
    constant ap_const_lv81_0 : STD_LOGIC_VECTOR (80 downto 0) := "000000000000000000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv32_4F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001001111";
    constant ap_const_lv32_50 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001010000";
    constant ap_const_lv18_0 : STD_LOGIC_VECTOR (17 downto 0) := "000000000000000000";
    constant ap_const_lv32_11 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010001";
    constant ap_const_lv32_2F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101111";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv32_28 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101000";
    constant ap_const_lv32_29 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101001";
    constant ap_const_lv7_7F : STD_LOGIC_VECTOR (6 downto 0) := "1111111";
    constant ap_const_lv8_FF : STD_LOGIC_VECTOR (7 downto 0) := "11111111";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";

    signal ap_CS_fsm : STD_LOGIC_VECTOR (55 downto 0) := "00000000000000000000000000000000000000000000000000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal tmp_q0 : STD_LOGIC_VECTOR (23 downto 0);
    signal add_ln11_fu_298_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln11_reg_1188 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal tmp_s_fu_308_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal tmp_s_reg_1193 : STD_LOGIC_VECTOR (13 downto 0);
    signal add_ln15_fu_327_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln15_reg_1209 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal conv_i362_fu_411_p1 : STD_LOGIC_VECTOR (39 downto 0);
    signal conv_i362_reg_1219 : STD_LOGIC_VECTOR (39 downto 0);
    signal row_sum_fu_477_p3 : STD_LOGIC_VECTOR (23 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal add_ln23_fu_491_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln23_reg_1232 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal zext_ln24_1_fu_506_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln24_1_reg_1237 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal add_ln29_fu_638_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln29_reg_1255 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_CS_fsm_state50 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state50 : signal is "none";
    signal zext_ln29_fu_644_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal zext_ln29_reg_1260 : STD_LOGIC_VECTOR (13 downto 0);
    signal add_ln33_fu_654_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln33_reg_1269 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_CS_fsm_state51 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state51 : signal is "none";
    signal scale_fu_757_p3 : STD_LOGIC_VECTOR (17 downto 0);
    signal scale_reg_1279 : STD_LOGIC_VECTOR (17 downto 0);
    signal tmp_7_reg_1285 : STD_LOGIC_VECTOR (0 downto 0);
    signal col_sum_fu_835_p3 : STD_LOGIC_VECTOR (23 downto 0);
    signal ap_CS_fsm_state52 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state52 : signal is "none";
    signal conv7_i_fu_921_p1 : STD_LOGIC_VECTOR (47 downto 0);
    signal conv7_i_reg_1296 : STD_LOGIC_VECTOR (47 downto 0);
    signal ap_CS_fsm_state53 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state53 : signal is "none";
    signal add_ln41_fu_931_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln41_reg_1304 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_CS_fsm_state54 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state54 : signal is "none";
    signal zext_ln42_1_fu_954_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln42_1_reg_1309 : STD_LOGIC_VECTOR (63 downto 0);
    signal select_ln42_3_fu_1170_p3 : STD_LOGIC_VECTOR (23 downto 0);
    signal select_ln42_3_reg_1319 : STD_LOGIC_VECTOR (23 downto 0);
    signal ap_CS_fsm_state55 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state55 : signal is "none";
    signal j_1_reg_207 : STD_LOGIC_VECTOR (6 downto 0);
    signal icmp_ln11_fu_292_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal empty_reg_218 : STD_LOGIC_VECTOR (23 downto 0);
    signal j_2_reg_230 : STD_LOGIC_VECTOR (6 downto 0);
    signal icmp_ln15_fu_321_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state49 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state49 : signal is "none";
    signal i_1_reg_241 : STD_LOGIC_VECTOR (8 downto 0);
    signal icmp_ln29_fu_632_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal empty_17_reg_252 : STD_LOGIC_VECTOR (23 downto 0);
    signal i_2_reg_264 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_CS_fsm_state56 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state56 : signal is "none";
    signal zext_ln16_1_fu_342_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal icmp_ln23_fu_485_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln34_fu_677_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal icmp_ln33_fu_648_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln41_fu_925_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal i_fu_136 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    signal j_fu_140 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    signal A_ce0_local : STD_LOGIC;
    signal A_address0_local : STD_LOGIC_VECTOR (13 downto 0);
    signal tmp_we0_local : STD_LOGIC;
    signal select_ln24_1_fu_620_p3 : STD_LOGIC_VECTOR (23 downto 0);
    signal tmp_ce0_local : STD_LOGIC;
    signal tmp_address0_local : STD_LOGIC_VECTOR (13 downto 0);
    signal C_we0_local : STD_LOGIC;
    signal C_ce0_local : STD_LOGIC;
    signal mul_ln42_fu_275_p1 : STD_LOGIC_VECTOR (23 downto 0);
    signal mul_ln38_fu_279_p1 : STD_LOGIC_VECTOR (41 downto 0);
    signal trunc_ln11_fu_304_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln16_fu_333_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal add_ln16_2_fu_337_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal sext_ln20_fu_347_p1 : STD_LOGIC_VECTOR (24 downto 0);
    signal add_ln20_fu_351_p2 : STD_LOGIC_VECTOR (24 downto 0);
    signal tmp_1_1_fu_357_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_1_fu_369_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln20_fu_377_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln20_fu_383_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln20_1_fu_389_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln20_fu_395_p3 : STD_LOGIC_VECTOR (23 downto 0);
    signal denom_fu_365_p1 : STD_LOGIC_VECTOR (23 downto 0);
    signal denom_1_fu_403_p3 : STD_LOGIC_VECTOR (23 downto 0);
    signal sext_ln16_1_fu_419_p0 : STD_LOGIC_VECTOR (23 downto 0);
    signal add_ln16_fu_423_p0 : STD_LOGIC_VECTOR (23 downto 0);
    signal sext_ln16_1_fu_419_p1 : STD_LOGIC_VECTOR (24 downto 0);
    signal sext_ln16_fu_415_p1 : STD_LOGIC_VECTOR (24 downto 0);
    signal add_ln16_1_fu_429_p2 : STD_LOGIC_VECTOR (24 downto 0);
    signal add_ln16_fu_423_p2 : STD_LOGIC_VECTOR (23 downto 0);
    signal tmp_2_fu_435_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_3_fu_443_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln16_fu_451_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln16_fu_457_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln16_1_fu_463_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln16_fu_469_p3 : STD_LOGIC_VECTOR (23 downto 0);
    signal zext_ln24_fu_497_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal add_ln24_fu_501_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal grp_fu_523_p0 : STD_LOGIC_VECTOR (39 downto 0);
    signal grp_fu_523_p1 : STD_LOGIC_VECTOR (23 downto 0);
    signal grp_fu_523_p2 : STD_LOGIC_VECTOR (39 downto 0);
    signal tmp_10_fu_548_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_13_fu_540_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln24_1_fu_564_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_12_fu_528_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln24_fu_570_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln24_fu_576_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln24_fu_558_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln24_1_fu_588_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln24_1_fu_594_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln24_fu_582_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln24_1_fu_600_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln24_2_fu_614_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln24_fu_606_p3 : STD_LOGIC_VECTOR (23 downto 0);
    signal trunc_ln24_fu_536_p1 : STD_LOGIC_VECTOR (23 downto 0);
    signal trunc_ln33_fu_660_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_8_fu_664_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal add_ln34_2_fu_672_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal shl_ln_fu_682_p3 : STD_LOGIC_VECTOR (39 downto 0);
    signal mul_ln38_fu_279_p2 : STD_LOGIC_VECTOR (80 downto 0);
    signal sub_ln38_fu_695_p2 : STD_LOGIC_VECTOR (80 downto 0);
    signal tmp_4_fu_701_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_19_cast_fu_709_p4 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_20_cast_fu_729_p4 : STD_LOGIC_VECTOR (16 downto 0);
    signal select_ln38_1_fu_739_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal zext_ln38_fu_747_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal sub_ln38_1_fu_751_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal tmp_20_cast3_fu_719_p4 : STD_LOGIC_VECTOR (17 downto 0);
    signal sext_ln34_1_fu_777_p0 : STD_LOGIC_VECTOR (23 downto 0);
    signal add_ln34_fu_781_p0 : STD_LOGIC_VECTOR (23 downto 0);
    signal sext_ln34_1_fu_777_p1 : STD_LOGIC_VECTOR (24 downto 0);
    signal sext_ln34_fu_773_p1 : STD_LOGIC_VECTOR (24 downto 0);
    signal add_ln34_1_fu_787_p2 : STD_LOGIC_VECTOR (24 downto 0);
    signal add_ln34_fu_781_p2 : STD_LOGIC_VECTOR (23 downto 0);
    signal tmp_9_fu_793_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_11_fu_801_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln34_fu_809_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln34_fu_815_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln34_1_fu_821_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln34_fu_827_p3 : STD_LOGIC_VECTOR (23 downto 0);
    signal sext_ln38_1_fu_843_p1 : STD_LOGIC_VECTOR (39 downto 0);
    signal tmp_6_fu_857_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_5_fu_846_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln38_fu_865_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln38_fu_870_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln38_2_fu_882_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln38_1_fu_887_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln38_fu_876_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln38_1_fu_893_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln38_1_fu_907_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln38_fu_899_p3 : STD_LOGIC_VECTOR (23 downto 0);
    signal sext_ln38_2_fu_854_p1 : STD_LOGIC_VECTOR (23 downto 0);
    signal scale_1_fu_913_p3 : STD_LOGIC_VECTOR (23 downto 0);
    signal trunc_ln41_fu_937_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_14_fu_941_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal add_ln42_1_fu_949_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal mul_ln42_fu_275_p2 : STD_LOGIC_VECTOR (47 downto 0);
    signal tmp_18_fu_986_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln2_fu_976_p4 : STD_LOGIC_VECTOR (23 downto 0);
    signal zext_ln42_fu_1002_p1 : STD_LOGIC_VECTOR (23 downto 0);
    signal add_ln42_fu_1006_p2 : STD_LOGIC_VECTOR (23 downto 0);
    signal tmp_20_fu_1012_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_19_fu_994_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln42_fu_1020_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_16_fu_1040_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_17_fu_1054_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal and_ln42_fu_1026_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln42_1_fu_1062_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln42_2_fu_1068_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_21_fu_1032_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln42_fu_1048_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln42_1_fu_1082_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln42_1_fu_1088_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln42_fu_1074_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln42_2_fu_1108_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_15_fu_968_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln42_fu_1114_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln42_3_fu_1120_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln42_1_fu_1094_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln42_2_fu_1102_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln42_4_fu_1132_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln42_2_fu_1138_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln42_4_fu_1144_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln42_3_fu_1126_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln42_5_fu_1150_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln42_1_fu_1164_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln42_2_fu_1156_p3 : STD_LOGIC_VECTOR (23 downto 0);
    signal grp_fu_523_ap_start : STD_LOGIC;
    signal grp_fu_523_ap_done : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (55 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_ST_fsm_state9_blk : STD_LOGIC;
    signal ap_ST_fsm_state10_blk : STD_LOGIC;
    signal ap_ST_fsm_state11_blk : STD_LOGIC;
    signal ap_ST_fsm_state12_blk : STD_LOGIC;
    signal ap_ST_fsm_state13_blk : STD_LOGIC;
    signal ap_ST_fsm_state14_blk : STD_LOGIC;
    signal ap_ST_fsm_state15_blk : STD_LOGIC;
    signal ap_ST_fsm_state16_blk : STD_LOGIC;
    signal ap_ST_fsm_state17_blk : STD_LOGIC;
    signal ap_ST_fsm_state18_blk : STD_LOGIC;
    signal ap_ST_fsm_state19_blk : STD_LOGIC;
    signal ap_ST_fsm_state20_blk : STD_LOGIC;
    signal ap_ST_fsm_state21_blk : STD_LOGIC;
    signal ap_ST_fsm_state22_blk : STD_LOGIC;
    signal ap_ST_fsm_state23_blk : STD_LOGIC;
    signal ap_ST_fsm_state24_blk : STD_LOGIC;
    signal ap_ST_fsm_state25_blk : STD_LOGIC;
    signal ap_ST_fsm_state26_blk : STD_LOGIC;
    signal ap_ST_fsm_state27_blk : STD_LOGIC;
    signal ap_ST_fsm_state28_blk : STD_LOGIC;
    signal ap_ST_fsm_state29_blk : STD_LOGIC;
    signal ap_ST_fsm_state30_blk : STD_LOGIC;
    signal ap_ST_fsm_state31_blk : STD_LOGIC;
    signal ap_ST_fsm_state32_blk : STD_LOGIC;
    signal ap_ST_fsm_state33_blk : STD_LOGIC;
    signal ap_ST_fsm_state34_blk : STD_LOGIC;
    signal ap_ST_fsm_state35_blk : STD_LOGIC;
    signal ap_ST_fsm_state36_blk : STD_LOGIC;
    signal ap_ST_fsm_state37_blk : STD_LOGIC;
    signal ap_ST_fsm_state38_blk : STD_LOGIC;
    signal ap_ST_fsm_state39_blk : STD_LOGIC;
    signal ap_ST_fsm_state40_blk : STD_LOGIC;
    signal ap_ST_fsm_state41_blk : STD_LOGIC;
    signal ap_ST_fsm_state42_blk : STD_LOGIC;
    signal ap_ST_fsm_state43_blk : STD_LOGIC;
    signal ap_ST_fsm_state44_blk : STD_LOGIC;
    signal ap_ST_fsm_state45_blk : STD_LOGIC;
    signal ap_ST_fsm_state46_blk : STD_LOGIC;
    signal ap_ST_fsm_state47_blk : STD_LOGIC;
    signal ap_ST_fsm_state48_blk : STD_LOGIC;
    signal ap_ST_fsm_state49_blk : STD_LOGIC;
    signal ap_ST_fsm_state50_blk : STD_LOGIC;
    signal ap_ST_fsm_state51_blk : STD_LOGIC;
    signal ap_ST_fsm_state52_blk : STD_LOGIC;
    signal ap_ST_fsm_state53_blk : STD_LOGIC;
    signal ap_ST_fsm_state54_blk : STD_LOGIC;
    signal ap_ST_fsm_state55_blk : STD_LOGIC;
    signal ap_ST_fsm_state56_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component top_kernel_mul_24s_24s_48_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (23 downto 0);
        din1 : IN STD_LOGIC_VECTOR (23 downto 0);
        dout : OUT STD_LOGIC_VECTOR (47 downto 0) );
    end component;


    component top_kernel_mul_40s_42ns_81_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (39 downto 0);
        din1 : IN STD_LOGIC_VECTOR (41 downto 0);
        dout : OUT STD_LOGIC_VECTOR (80 downto 0) );
    end component;


    component top_kernel_sdiv_40ns_24s_40_44_seq_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        start : IN STD_LOGIC;
        done : OUT STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (39 downto 0);
        din1 : IN STD_LOGIC_VECTOR (23 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (39 downto 0) );
    end component;


    component top_kernel_tmp_RAM_AUTO_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (13 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (23 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (23 downto 0) );
    end component;



begin
    tmp_U : component top_kernel_tmp_RAM_AUTO_1R1W
    generic map (
        DataWidth => 24,
        AddressRange => 16384,
        AddressWidth => 14)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => tmp_address0_local,
        ce0 => tmp_ce0_local,
        we0 => tmp_we0_local,
        d0 => select_ln24_1_fu_620_p3,
        q0 => tmp_q0);

    mul_24s_24s_48_1_1_U1 : component top_kernel_mul_24s_24s_48_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 24,
        din1_WIDTH => 24,
        dout_WIDTH => 48)
    port map (
        din0 => tmp_q0,
        din1 => mul_ln42_fu_275_p1,
        dout => mul_ln42_fu_275_p2);

    mul_40s_42ns_81_1_1_U2 : component top_kernel_mul_40s_42ns_81_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 40,
        din1_WIDTH => 42,
        dout_WIDTH => 81)
    port map (
        din0 => shl_ln_fu_682_p3,
        din1 => mul_ln38_fu_279_p1,
        dout => mul_ln38_fu_279_p2);

    sdiv_40ns_24s_40_44_seq_1_U3 : component top_kernel_sdiv_40ns_24s_40_44_seq_1
    generic map (
        ID => 1,
        NUM_STAGE => 44,
        din0_WIDTH => 40,
        din1_WIDTH => 24,
        dout_WIDTH => 40)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        start => grp_fu_523_ap_start,
        done => grp_fu_523_ap_done,
        din0 => grp_fu_523_p0,
        din1 => grp_fu_523_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_523_p2);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    empty_17_reg_252_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state52)) then 
                empty_17_reg_252 <= col_sum_fu_835_p3;
            elsif (((icmp_ln29_fu_632_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state50))) then 
                empty_17_reg_252 <= ap_const_lv24_0;
            end if; 
        end if;
    end process;

    empty_reg_218_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
                empty_reg_218 <= row_sum_fu_477_p3;
            elsif (((icmp_ln11_fu_292_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                empty_reg_218 <= ap_const_lv24_0;
            end if; 
        end if;
    end process;

    i_1_reg_241_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state52)) then 
                i_1_reg_241 <= add_ln33_reg_1269;
            elsif (((icmp_ln29_fu_632_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state50))) then 
                i_1_reg_241 <= ap_const_lv9_0;
            end if; 
        end if;
    end process;

    i_2_reg_264_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state56)) then 
                i_2_reg_264 <= add_ln41_reg_1304;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state53)) then 
                i_2_reg_264 <= ap_const_lv9_0;
            end if; 
        end if;
    end process;

    i_fu_136_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                i_fu_136 <= ap_const_lv9_0;
            elsif (((icmp_ln23_fu_485_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
                i_fu_136 <= add_ln11_reg_1188;
            end if; 
        end if;
    end process;

    j_1_reg_207_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
                j_1_reg_207 <= add_ln15_reg_1209;
            elsif (((icmp_ln11_fu_292_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                j_1_reg_207 <= ap_const_lv7_0;
            end if; 
        end if;
    end process;

    j_2_reg_230_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state49)) then 
                j_2_reg_230 <= add_ln23_reg_1232;
            elsif (((icmp_ln15_fu_321_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                j_2_reg_230 <= ap_const_lv7_0;
            end if; 
        end if;
    end process;

    j_fu_140_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln11_fu_292_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                j_fu_140 <= ap_const_lv7_0;
            elsif (((icmp_ln41_fu_925_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state54))) then 
                j_fu_140 <= add_ln29_reg_1255;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                add_ln11_reg_1188 <= add_ln11_fu_298_p2;
                    tmp_s_reg_1193(13 downto 6) <= tmp_s_fu_308_p3(13 downto 6);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                add_ln15_reg_1209 <= add_ln15_fu_327_p2;
                conv_i362_reg_1219 <= conv_i362_fu_411_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then
                add_ln23_reg_1232 <= add_ln23_fu_491_p2;
                    zext_ln24_1_reg_1237(13 downto 0) <= zext_ln24_1_fu_506_p1(13 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state50)) then
                add_ln29_reg_1255 <= add_ln29_fu_638_p2;
                    zext_ln29_reg_1260(6 downto 0) <= zext_ln29_fu_644_p1(6 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state51)) then
                add_ln33_reg_1269 <= add_ln33_fu_654_p2;
                scale_reg_1279 <= scale_fu_757_p3;
                tmp_7_reg_1285 <= scale_fu_757_p3(17 downto 17);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state54)) then
                add_ln41_reg_1304 <= add_ln41_fu_931_p2;
                    zext_ln42_1_reg_1309(13 downto 0) <= zext_ln42_1_fu_954_p1(13 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state53)) then
                conv7_i_reg_1296 <= conv7_i_fu_921_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state55)) then
                select_ln42_3_reg_1319 <= select_ln42_3_fu_1170_p3;
            end if;
        end if;
    end process;
    tmp_s_reg_1193(5 downto 0) <= "000000";
    zext_ln24_1_reg_1237(63 downto 14) <= "00000000000000000000000000000000000000000000000000";
    zext_ln29_reg_1260(13 downto 7) <= "0000000";
    zext_ln42_1_reg_1309(63 downto 14) <= "00000000000000000000000000000000000000000000000000";

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state5, ap_CS_fsm_state50, ap_CS_fsm_state51, ap_CS_fsm_state54, icmp_ln11_fu_292_p2, icmp_ln15_fu_321_p2, icmp_ln29_fu_632_p2, icmp_ln23_fu_485_p2, icmp_ln33_fu_648_p2, icmp_ln41_fu_925_p2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((icmp_ln11_fu_292_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state50;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state3 => 
                if (((icmp_ln15_fu_321_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state5 => 
                if (((icmp_ln23_fu_485_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state6;
                end if;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state9;
            when ap_ST_fsm_state9 => 
                ap_NS_fsm <= ap_ST_fsm_state10;
            when ap_ST_fsm_state10 => 
                ap_NS_fsm <= ap_ST_fsm_state11;
            when ap_ST_fsm_state11 => 
                ap_NS_fsm <= ap_ST_fsm_state12;
            when ap_ST_fsm_state12 => 
                ap_NS_fsm <= ap_ST_fsm_state13;
            when ap_ST_fsm_state13 => 
                ap_NS_fsm <= ap_ST_fsm_state14;
            when ap_ST_fsm_state14 => 
                ap_NS_fsm <= ap_ST_fsm_state15;
            when ap_ST_fsm_state15 => 
                ap_NS_fsm <= ap_ST_fsm_state16;
            when ap_ST_fsm_state16 => 
                ap_NS_fsm <= ap_ST_fsm_state17;
            when ap_ST_fsm_state17 => 
                ap_NS_fsm <= ap_ST_fsm_state18;
            when ap_ST_fsm_state18 => 
                ap_NS_fsm <= ap_ST_fsm_state19;
            when ap_ST_fsm_state19 => 
                ap_NS_fsm <= ap_ST_fsm_state20;
            when ap_ST_fsm_state20 => 
                ap_NS_fsm <= ap_ST_fsm_state21;
            when ap_ST_fsm_state21 => 
                ap_NS_fsm <= ap_ST_fsm_state22;
            when ap_ST_fsm_state22 => 
                ap_NS_fsm <= ap_ST_fsm_state23;
            when ap_ST_fsm_state23 => 
                ap_NS_fsm <= ap_ST_fsm_state24;
            when ap_ST_fsm_state24 => 
                ap_NS_fsm <= ap_ST_fsm_state25;
            when ap_ST_fsm_state25 => 
                ap_NS_fsm <= ap_ST_fsm_state26;
            when ap_ST_fsm_state26 => 
                ap_NS_fsm <= ap_ST_fsm_state27;
            when ap_ST_fsm_state27 => 
                ap_NS_fsm <= ap_ST_fsm_state28;
            when ap_ST_fsm_state28 => 
                ap_NS_fsm <= ap_ST_fsm_state29;
            when ap_ST_fsm_state29 => 
                ap_NS_fsm <= ap_ST_fsm_state30;
            when ap_ST_fsm_state30 => 
                ap_NS_fsm <= ap_ST_fsm_state31;
            when ap_ST_fsm_state31 => 
                ap_NS_fsm <= ap_ST_fsm_state32;
            when ap_ST_fsm_state32 => 
                ap_NS_fsm <= ap_ST_fsm_state33;
            when ap_ST_fsm_state33 => 
                ap_NS_fsm <= ap_ST_fsm_state34;
            when ap_ST_fsm_state34 => 
                ap_NS_fsm <= ap_ST_fsm_state35;
            when ap_ST_fsm_state35 => 
                ap_NS_fsm <= ap_ST_fsm_state36;
            when ap_ST_fsm_state36 => 
                ap_NS_fsm <= ap_ST_fsm_state37;
            when ap_ST_fsm_state37 => 
                ap_NS_fsm <= ap_ST_fsm_state38;
            when ap_ST_fsm_state38 => 
                ap_NS_fsm <= ap_ST_fsm_state39;
            when ap_ST_fsm_state39 => 
                ap_NS_fsm <= ap_ST_fsm_state40;
            when ap_ST_fsm_state40 => 
                ap_NS_fsm <= ap_ST_fsm_state41;
            when ap_ST_fsm_state41 => 
                ap_NS_fsm <= ap_ST_fsm_state42;
            when ap_ST_fsm_state42 => 
                ap_NS_fsm <= ap_ST_fsm_state43;
            when ap_ST_fsm_state43 => 
                ap_NS_fsm <= ap_ST_fsm_state44;
            when ap_ST_fsm_state44 => 
                ap_NS_fsm <= ap_ST_fsm_state45;
            when ap_ST_fsm_state45 => 
                ap_NS_fsm <= ap_ST_fsm_state46;
            when ap_ST_fsm_state46 => 
                ap_NS_fsm <= ap_ST_fsm_state47;
            when ap_ST_fsm_state47 => 
                ap_NS_fsm <= ap_ST_fsm_state48;
            when ap_ST_fsm_state48 => 
                ap_NS_fsm <= ap_ST_fsm_state49;
            when ap_ST_fsm_state49 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state50 => 
                if (((icmp_ln29_fu_632_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state50))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state51;
                end if;
            when ap_ST_fsm_state51 => 
                if (((icmp_ln33_fu_648_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state51))) then
                    ap_NS_fsm <= ap_ST_fsm_state53;
                else
                    ap_NS_fsm <= ap_ST_fsm_state52;
                end if;
            when ap_ST_fsm_state52 => 
                ap_NS_fsm <= ap_ST_fsm_state51;
            when ap_ST_fsm_state53 => 
                ap_NS_fsm <= ap_ST_fsm_state54;
            when ap_ST_fsm_state54 => 
                if (((icmp_ln41_fu_925_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state54))) then
                    ap_NS_fsm <= ap_ST_fsm_state50;
                else
                    ap_NS_fsm <= ap_ST_fsm_state55;
                end if;
            when ap_ST_fsm_state55 => 
                ap_NS_fsm <= ap_ST_fsm_state56;
            when ap_ST_fsm_state56 => 
                ap_NS_fsm <= ap_ST_fsm_state54;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end case;
    end process;
    A_address0 <= A_address0_local;

    A_address0_local_assign_proc : process(ap_CS_fsm_state3, ap_CS_fsm_state5, zext_ln24_1_fu_506_p1, zext_ln16_1_fu_342_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            A_address0_local <= zext_ln24_1_fu_506_p1(14 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            A_address0_local <= zext_ln16_1_fu_342_p1(14 - 1 downto 0);
        else 
            A_address0_local <= "XXXXXXXXXXXXXX";
        end if; 
    end process;

    A_ce0 <= A_ce0_local;

    A_ce0_local_assign_proc : process(ap_CS_fsm_state3, ap_CS_fsm_state5)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            A_ce0_local <= ap_const_logic_1;
        else 
            A_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    C_address0 <= zext_ln42_1_reg_1309(14 - 1 downto 0);
    C_ce0 <= C_ce0_local;

    C_ce0_local_assign_proc : process(ap_CS_fsm_state56)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state56)) then 
            C_ce0_local <= ap_const_logic_1;
        else 
            C_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    C_d0 <= select_ln42_3_reg_1319;
    C_we0 <= C_we0_local;

    C_we0_local_assign_proc : process(ap_CS_fsm_state56)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state56)) then 
            C_we0_local <= ap_const_logic_1;
        else 
            C_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    add_ln11_fu_298_p2 <= std_logic_vector(unsigned(i_fu_136) + unsigned(ap_const_lv9_1));
    add_ln15_fu_327_p2 <= std_logic_vector(unsigned(j_1_reg_207) + unsigned(ap_const_lv7_1));
    add_ln16_1_fu_429_p2 <= std_logic_vector(signed(sext_ln16_1_fu_419_p1) + signed(sext_ln16_fu_415_p1));
    add_ln16_2_fu_337_p2 <= std_logic_vector(unsigned(tmp_s_reg_1193) + unsigned(zext_ln16_fu_333_p1));
    add_ln16_fu_423_p0 <= A_q0;
    add_ln16_fu_423_p2 <= std_logic_vector(signed(add_ln16_fu_423_p0) + signed(empty_reg_218));
    add_ln20_fu_351_p2 <= std_logic_vector(signed(sext_ln20_fu_347_p1) + signed(ap_const_lv25_10000));
    add_ln23_fu_491_p2 <= std_logic_vector(unsigned(j_2_reg_230) + unsigned(ap_const_lv7_1));
    add_ln24_fu_501_p2 <= std_logic_vector(unsigned(tmp_s_reg_1193) + unsigned(zext_ln24_fu_497_p1));
    add_ln29_fu_638_p2 <= std_logic_vector(unsigned(j_fu_140) + unsigned(ap_const_lv7_1));
    add_ln33_fu_654_p2 <= std_logic_vector(unsigned(i_1_reg_241) + unsigned(ap_const_lv9_1));
    add_ln34_1_fu_787_p2 <= std_logic_vector(signed(sext_ln34_1_fu_777_p1) + signed(sext_ln34_fu_773_p1));
    add_ln34_2_fu_672_p2 <= std_logic_vector(unsigned(tmp_8_fu_664_p3) + unsigned(zext_ln29_reg_1260));
    add_ln34_fu_781_p0 <= tmp_q0;
    add_ln34_fu_781_p2 <= std_logic_vector(signed(add_ln34_fu_781_p0) + signed(empty_17_reg_252));
    add_ln41_fu_931_p2 <= std_logic_vector(unsigned(i_2_reg_264) + unsigned(ap_const_lv9_1));
    add_ln42_1_fu_949_p2 <= std_logic_vector(unsigned(tmp_14_fu_941_p3) + unsigned(zext_ln29_reg_1260));
    add_ln42_fu_1006_p2 <= std_logic_vector(unsigned(trunc_ln2_fu_976_p4) + unsigned(zext_ln42_fu_1002_p1));
    and_ln16_fu_457_p2 <= (xor_ln16_fu_451_p2 and tmp_3_fu_443_p3);
    and_ln20_fu_383_p2 <= (xor_ln20_fu_377_p2 and tmp_1_fu_369_p3);
    and_ln24_1_fu_600_p2 <= (tmp_12_fu_528_p3 and or_ln24_1_fu_594_p2);
    and_ln24_fu_582_p2 <= (xor_ln24_fu_576_p2 and or_ln24_fu_570_p2);
    and_ln34_fu_815_p2 <= (xor_ln34_fu_809_p2 and tmp_11_fu_801_p3);
    and_ln38_1_fu_893_p2 <= (xor_ln38_1_fu_887_p2 and tmp_5_fu_846_p3);
    and_ln38_2_fu_882_p2 <= (tmp_7_reg_1285 and tmp_6_fu_857_p3);
    and_ln38_fu_876_p2 <= (xor_ln38_fu_870_p2 and or_ln38_fu_865_p2);
    and_ln42_1_fu_1088_p2 <= (xor_ln42_1_fu_1082_p2 and icmp_ln42_fu_1048_p2);
    and_ln42_2_fu_1102_p2 <= (icmp_ln42_1_fu_1062_p2 and and_ln42_fu_1026_p2);
    and_ln42_3_fu_1126_p2 <= (xor_ln42_3_fu_1120_p2 and or_ln42_fu_1114_p2);
    and_ln42_4_fu_1132_p2 <= (tmp_20_fu_1012_p3 and select_ln42_1_fu_1094_p3);
    and_ln42_5_fu_1150_p2 <= (xor_ln42_4_fu_1144_p2 and tmp_15_fu_968_p3);
    and_ln42_fu_1026_p2 <= (xor_ln42_fu_1020_p2 and tmp_19_fu_994_p3);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state49 <= ap_CS_fsm(48);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state50 <= ap_CS_fsm(49);
    ap_CS_fsm_state51 <= ap_CS_fsm(50);
    ap_CS_fsm_state52 <= ap_CS_fsm(51);
    ap_CS_fsm_state53 <= ap_CS_fsm(52);
    ap_CS_fsm_state54 <= ap_CS_fsm(53);
    ap_CS_fsm_state55 <= ap_CS_fsm(54);
    ap_CS_fsm_state56 <= ap_CS_fsm(55);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_ST_fsm_state10_blk <= ap_const_logic_0;
    ap_ST_fsm_state11_blk <= ap_const_logic_0;
    ap_ST_fsm_state12_blk <= ap_const_logic_0;
    ap_ST_fsm_state13_blk <= ap_const_logic_0;
    ap_ST_fsm_state14_blk <= ap_const_logic_0;
    ap_ST_fsm_state15_blk <= ap_const_logic_0;
    ap_ST_fsm_state16_blk <= ap_const_logic_0;
    ap_ST_fsm_state17_blk <= ap_const_logic_0;
    ap_ST_fsm_state18_blk <= ap_const_logic_0;
    ap_ST_fsm_state19_blk <= ap_const_logic_0;

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state20_blk <= ap_const_logic_0;
    ap_ST_fsm_state21_blk <= ap_const_logic_0;
    ap_ST_fsm_state22_blk <= ap_const_logic_0;
    ap_ST_fsm_state23_blk <= ap_const_logic_0;
    ap_ST_fsm_state24_blk <= ap_const_logic_0;
    ap_ST_fsm_state25_blk <= ap_const_logic_0;
    ap_ST_fsm_state26_blk <= ap_const_logic_0;
    ap_ST_fsm_state27_blk <= ap_const_logic_0;
    ap_ST_fsm_state28_blk <= ap_const_logic_0;
    ap_ST_fsm_state29_blk <= ap_const_logic_0;
    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state30_blk <= ap_const_logic_0;
    ap_ST_fsm_state31_blk <= ap_const_logic_0;
    ap_ST_fsm_state32_blk <= ap_const_logic_0;
    ap_ST_fsm_state33_blk <= ap_const_logic_0;
    ap_ST_fsm_state34_blk <= ap_const_logic_0;
    ap_ST_fsm_state35_blk <= ap_const_logic_0;
    ap_ST_fsm_state36_blk <= ap_const_logic_0;
    ap_ST_fsm_state37_blk <= ap_const_logic_0;
    ap_ST_fsm_state38_blk <= ap_const_logic_0;
    ap_ST_fsm_state39_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;
    ap_ST_fsm_state40_blk <= ap_const_logic_0;
    ap_ST_fsm_state41_blk <= ap_const_logic_0;
    ap_ST_fsm_state42_blk <= ap_const_logic_0;
    ap_ST_fsm_state43_blk <= ap_const_logic_0;
    ap_ST_fsm_state44_blk <= ap_const_logic_0;
    ap_ST_fsm_state45_blk <= ap_const_logic_0;
    ap_ST_fsm_state46_blk <= ap_const_logic_0;
    ap_ST_fsm_state47_blk <= ap_const_logic_0;
    ap_ST_fsm_state48_blk <= ap_const_logic_0;
    ap_ST_fsm_state49_blk <= ap_const_logic_0;
    ap_ST_fsm_state4_blk <= ap_const_logic_0;
    ap_ST_fsm_state50_blk <= ap_const_logic_0;
    ap_ST_fsm_state51_blk <= ap_const_logic_0;
    ap_ST_fsm_state52_blk <= ap_const_logic_0;
    ap_ST_fsm_state53_blk <= ap_const_logic_0;
    ap_ST_fsm_state54_blk <= ap_const_logic_0;
    ap_ST_fsm_state55_blk <= ap_const_logic_0;
    ap_ST_fsm_state56_blk <= ap_const_logic_0;
    ap_ST_fsm_state5_blk <= ap_const_logic_0;
    ap_ST_fsm_state6_blk <= ap_const_logic_0;
    ap_ST_fsm_state7_blk <= ap_const_logic_0;
    ap_ST_fsm_state8_blk <= ap_const_logic_0;
    ap_ST_fsm_state9_blk <= ap_const_logic_0;

    ap_done_assign_proc : process(ap_CS_fsm_state50, icmp_ln29_fu_632_p2)
    begin
        if (((icmp_ln29_fu_632_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state50))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state50, icmp_ln29_fu_632_p2)
    begin
        if (((icmp_ln29_fu_632_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state50))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    col_sum_fu_835_p3 <= 
        select_ln34_fu_827_p3 when (xor_ln34_1_fu_821_p2(0) = '1') else 
        add_ln34_fu_781_p2;
        conv7_i_fu_921_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(scale_1_fu_913_p3),48));

        conv_i362_fu_411_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(denom_1_fu_403_p3),40));

    denom_1_fu_403_p3 <= 
        select_ln20_fu_395_p3 when (xor_ln20_1_fu_389_p2(0) = '1') else 
        denom_fu_365_p1;
    denom_fu_365_p1 <= add_ln20_fu_351_p2(24 - 1 downto 0);

    grp_fu_523_ap_start_assign_proc : process(ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            grp_fu_523_ap_start <= ap_const_logic_1;
        else 
            grp_fu_523_ap_start <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_523_p0 <= (A_q0 & ap_const_lv16_0);
    grp_fu_523_p1 <= conv_i362_reg_1219(24 - 1 downto 0);
    icmp_ln11_fu_292_p2 <= "1" when (i_fu_136 = ap_const_lv9_100) else "0";
    icmp_ln15_fu_321_p2 <= "1" when (j_1_reg_207 = ap_const_lv7_40) else "0";
    icmp_ln23_fu_485_p2 <= "1" when (j_2_reg_230 = ap_const_lv7_40) else "0";
    icmp_ln24_1_fu_564_p2 <= "0" when (tmp_10_fu_548_p4 = ap_const_lv16_0) else "1";
    icmp_ln24_fu_558_p2 <= "0" when (tmp_10_fu_548_p4 = ap_const_lv16_FFFF) else "1";
    icmp_ln29_fu_632_p2 <= "1" when (j_fu_140 = ap_const_lv7_40) else "0";
    icmp_ln33_fu_648_p2 <= "1" when (i_1_reg_241 = ap_const_lv9_100) else "0";
    icmp_ln41_fu_925_p2 <= "1" when (i_2_reg_264 = ap_const_lv9_100) else "0";
    icmp_ln42_1_fu_1062_p2 <= "1" when (tmp_17_fu_1054_p3 = ap_const_lv8_FF) else "0";
    icmp_ln42_2_fu_1068_p2 <= "1" when (tmp_17_fu_1054_p3 = ap_const_lv8_0) else "0";
    icmp_ln42_fu_1048_p2 <= "1" when (tmp_16_fu_1040_p3 = ap_const_lv7_7F) else "0";
    mul_ln38_fu_279_p1 <= ap_const_lv81_10000020001(42 - 1 downto 0);
    mul_ln42_fu_275_p1 <= conv7_i_reg_1296(24 - 1 downto 0);
    or_ln24_1_fu_594_p2 <= (xor_ln24_1_fu_588_p2 or icmp_ln24_fu_558_p2);
    or_ln24_2_fu_614_p2 <= (and_ln24_fu_582_p2 or and_ln24_1_fu_600_p2);
    or_ln24_fu_570_p2 <= (tmp_13_fu_540_p3 or icmp_ln24_1_fu_564_p2);
    or_ln38_1_fu_907_p2 <= (and_ln38_fu_876_p2 or and_ln38_1_fu_893_p2);
    or_ln38_fu_865_p2 <= (tmp_7_reg_1285 or tmp_6_fu_857_p3);
    or_ln42_1_fu_1164_p2 <= (and_ln42_5_fu_1150_p2 or and_ln42_3_fu_1126_p2);
    or_ln42_2_fu_1138_p2 <= (and_ln42_4_fu_1132_p2 or and_ln42_2_fu_1102_p2);
    or_ln42_fu_1114_p2 <= (xor_ln42_2_fu_1108_p2 or tmp_20_fu_1012_p3);
    row_sum_fu_477_p3 <= 
        select_ln16_fu_469_p3 when (xor_ln16_1_fu_463_p2(0) = '1') else 
        add_ln16_fu_423_p2;
    scale_1_fu_913_p3 <= 
        select_ln38_fu_899_p3 when (or_ln38_1_fu_907_p2(0) = '1') else 
        sext_ln38_2_fu_854_p1;
    scale_fu_757_p3 <= 
        sub_ln38_1_fu_751_p2 when (tmp_4_fu_701_p3(0) = '1') else 
        tmp_20_cast3_fu_719_p4;
    select_ln16_fu_469_p3 <= 
        ap_const_lv24_7FFFFF when (and_ln16_fu_457_p2(0) = '1') else 
        ap_const_lv24_800000;
    select_ln20_fu_395_p3 <= 
        ap_const_lv24_7FFFFF when (and_ln20_fu_383_p2(0) = '1') else 
        ap_const_lv24_800000;
    select_ln24_1_fu_620_p3 <= 
        select_ln24_fu_606_p3 when (or_ln24_2_fu_614_p2(0) = '1') else 
        trunc_ln24_fu_536_p1;
    select_ln24_fu_606_p3 <= 
        ap_const_lv24_7FFFFF when (and_ln24_fu_582_p2(0) = '1') else 
        ap_const_lv24_800000;
    select_ln34_fu_827_p3 <= 
        ap_const_lv24_7FFFFF when (and_ln34_fu_815_p2(0) = '1') else 
        ap_const_lv24_800000;
    select_ln38_1_fu_739_p3 <= 
        tmp_19_cast_fu_709_p4 when (tmp_4_fu_701_p3(0) = '1') else 
        tmp_20_cast_fu_729_p4;
    select_ln38_fu_899_p3 <= 
        ap_const_lv24_7FFFFF when (and_ln38_fu_876_p2(0) = '1') else 
        ap_const_lv24_800000;
    select_ln42_1_fu_1094_p3 <= 
        and_ln42_1_fu_1088_p2 when (and_ln42_fu_1026_p2(0) = '1') else 
        icmp_ln42_1_fu_1062_p2;
    select_ln42_2_fu_1156_p3 <= 
        ap_const_lv24_7FFFFF when (and_ln42_3_fu_1126_p2(0) = '1') else 
        ap_const_lv24_800000;
    select_ln42_3_fu_1170_p3 <= 
        select_ln42_2_fu_1156_p3 when (or_ln42_1_fu_1164_p2(0) = '1') else 
        add_ln42_fu_1006_p2;
    select_ln42_fu_1074_p3 <= 
        icmp_ln42_1_fu_1062_p2 when (and_ln42_fu_1026_p2(0) = '1') else 
        icmp_ln42_2_fu_1068_p2;
    sext_ln16_1_fu_419_p0 <= A_q0;
        sext_ln16_1_fu_419_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln16_1_fu_419_p0),25));

        sext_ln16_fu_415_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(empty_reg_218),25));

        sext_ln20_fu_347_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(empty_reg_218),25));

    sext_ln34_1_fu_777_p0 <= tmp_q0;
        sext_ln34_1_fu_777_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln34_1_fu_777_p0),25));

        sext_ln34_fu_773_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(empty_17_reg_252),25));

        sext_ln38_1_fu_843_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(scale_reg_1279),40));

        sext_ln38_2_fu_854_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(scale_reg_1279),24));

    shl_ln_fu_682_p3 <= (empty_17_reg_252 & ap_const_lv16_0);
    sub_ln38_1_fu_751_p2 <= std_logic_vector(unsigned(ap_const_lv18_0) - unsigned(zext_ln38_fu_747_p1));
    sub_ln38_fu_695_p2 <= std_logic_vector(unsigned(ap_const_lv81_0) - unsigned(mul_ln38_fu_279_p2));
    tmp_10_fu_548_p4 <= grp_fu_523_p2(39 downto 24);
    tmp_11_fu_801_p3 <= add_ln34_fu_781_p2(23 downto 23);
    tmp_12_fu_528_p3 <= grp_fu_523_p2(39 downto 39);
    tmp_13_fu_540_p3 <= grp_fu_523_p2(23 downto 23);
    tmp_14_fu_941_p3 <= (trunc_ln41_fu_937_p1 & ap_const_lv6_0);
    tmp_15_fu_968_p3 <= mul_ln42_fu_275_p2(47 downto 47);
    tmp_16_fu_1040_p3 <= mul_ln42_fu_275_p2(47 downto 41);
    tmp_17_fu_1054_p3 <= mul_ln42_fu_275_p2(47 downto 40);
    tmp_18_fu_986_p3 <= mul_ln42_fu_275_p2(15 downto 15);
    tmp_19_cast_fu_709_p4 <= sub_ln38_fu_695_p2(79 downto 63);
    tmp_19_fu_994_p3 <= mul_ln42_fu_275_p2(39 downto 39);
    tmp_1_1_fu_357_p3 <= add_ln20_fu_351_p2(24 downto 24);
    tmp_1_fu_369_p3 <= add_ln20_fu_351_p2(23 downto 23);
    tmp_20_cast3_fu_719_p4 <= mul_ln38_fu_279_p2(80 downto 63);
    tmp_20_cast_fu_729_p4 <= mul_ln38_fu_279_p2(79 downto 63);
    tmp_20_fu_1012_p3 <= add_ln42_fu_1006_p2(23 downto 23);
    tmp_21_fu_1032_p3 <= mul_ln42_fu_275_p2(40 downto 40);
    tmp_2_fu_435_p3 <= add_ln16_1_fu_429_p2(24 downto 24);
    tmp_3_fu_443_p3 <= add_ln16_fu_423_p2(23 downto 23);
    tmp_4_fu_701_p3 <= empty_17_reg_252(23 downto 23);
    tmp_5_fu_846_p3 <= sext_ln38_1_fu_843_p1(39 downto 39);
    tmp_6_fu_857_p3 <= sext_ln38_1_fu_843_p1(23 downto 23);
    tmp_8_fu_664_p3 <= (trunc_ln33_fu_660_p1 & ap_const_lv6_0);
    tmp_9_fu_793_p3 <= add_ln34_1_fu_787_p2(24 downto 24);

    tmp_address0_local_assign_proc : process(zext_ln24_1_reg_1237, ap_CS_fsm_state51, ap_CS_fsm_state54, zext_ln42_1_fu_954_p1, ap_CS_fsm_state49, zext_ln34_fu_677_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state54)) then 
            tmp_address0_local <= zext_ln42_1_fu_954_p1(14 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state51)) then 
            tmp_address0_local <= zext_ln34_fu_677_p1(14 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state49)) then 
            tmp_address0_local <= zext_ln24_1_reg_1237(14 - 1 downto 0);
        else 
            tmp_address0_local <= "XXXXXXXXXXXXXX";
        end if; 
    end process;


    tmp_ce0_local_assign_proc : process(ap_CS_fsm_state51, ap_CS_fsm_state54, ap_CS_fsm_state49)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state49) or (ap_const_logic_1 = ap_CS_fsm_state54) or (ap_const_logic_1 = ap_CS_fsm_state51))) then 
            tmp_ce0_local <= ap_const_logic_1;
        else 
            tmp_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    tmp_s_fu_308_p3 <= (trunc_ln11_fu_304_p1 & ap_const_lv6_0);

    tmp_we0_local_assign_proc : process(ap_CS_fsm_state49)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state49)) then 
            tmp_we0_local <= ap_const_logic_1;
        else 
            tmp_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    trunc_ln11_fu_304_p1 <= i_fu_136(8 - 1 downto 0);
    trunc_ln24_fu_536_p1 <= grp_fu_523_p2(24 - 1 downto 0);
    trunc_ln2_fu_976_p4 <= mul_ln42_fu_275_p2(39 downto 16);
    trunc_ln33_fu_660_p1 <= i_1_reg_241(8 - 1 downto 0);
    trunc_ln41_fu_937_p1 <= i_2_reg_264(8 - 1 downto 0);
    xor_ln16_1_fu_463_p2 <= (tmp_3_fu_443_p3 xor tmp_2_fu_435_p3);
    xor_ln16_fu_451_p2 <= (tmp_2_fu_435_p3 xor ap_const_lv1_1);
    xor_ln20_1_fu_389_p2 <= (tmp_1_fu_369_p3 xor tmp_1_1_fu_357_p3);
    xor_ln20_fu_377_p2 <= (tmp_1_1_fu_357_p3 xor ap_const_lv1_1);
    xor_ln24_1_fu_588_p2 <= (tmp_13_fu_540_p3 xor ap_const_lv1_1);
    xor_ln24_fu_576_p2 <= (tmp_12_fu_528_p3 xor ap_const_lv1_1);
    xor_ln34_1_fu_821_p2 <= (tmp_9_fu_793_p3 xor tmp_11_fu_801_p3);
    xor_ln34_fu_809_p2 <= (tmp_9_fu_793_p3 xor ap_const_lv1_1);
    xor_ln38_1_fu_887_p2 <= (ap_const_lv1_1 xor and_ln38_2_fu_882_p2);
    xor_ln38_fu_870_p2 <= (tmp_5_fu_846_p3 xor ap_const_lv1_1);
    xor_ln42_1_fu_1082_p2 <= (tmp_21_fu_1032_p3 xor ap_const_lv1_1);
    xor_ln42_2_fu_1108_p2 <= (select_ln42_fu_1074_p3 xor ap_const_lv1_1);
    xor_ln42_3_fu_1120_p2 <= (tmp_15_fu_968_p3 xor ap_const_lv1_1);
    xor_ln42_4_fu_1144_p2 <= (or_ln42_2_fu_1138_p2 xor ap_const_lv1_1);
    xor_ln42_fu_1020_p2 <= (tmp_20_fu_1012_p3 xor ap_const_lv1_1);
    zext_ln16_1_fu_342_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln16_2_fu_337_p2),64));
    zext_ln16_fu_333_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(j_1_reg_207),14));
    zext_ln24_1_fu_506_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln24_fu_501_p2),64));
    zext_ln24_fu_497_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(j_2_reg_230),14));
    zext_ln29_fu_644_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(j_fu_140),14));
    zext_ln34_fu_677_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln34_2_fu_672_p2),64));
    zext_ln38_fu_747_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln38_1_fu_739_p3),18));
    zext_ln42_1_fu_954_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln42_1_fu_949_p2),64));
    zext_ln42_fu_1002_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_18_fu_986_p3),24));
end behav;
